const {test,expect}=require('playwright/test'),{fixture}=require('../fixtures/weekly-coaching');
const hub=page=>page.locator('[data-training-hub="full"]');
test.beforeEach(async({page})=>{await page.clock.install({time:new Date('2026-10-04T19:00:00Z')});await page.goto('/');await expect(page.locator('.ex-name')).toHaveCount(1);});
test('new athlete saves setup then reaches the existing reviewed planner without an account',async({page})=>{
 await expect(hub(page)).toContainText('Getting started · 0/3');await hub(page).locator('[data-hub-primary]').click();const d=page.locator('#programming-profile-dialog');await expect(d).toBeVisible();
 for(const key of ['barbell','plates','rack','bench'])await d.locator('[data-profile-equipment][value='+key+']').check();
 await d.getByRole('button',{name:'Save programming profile',exact:true}).click();await expect(d).toBeHidden();await expect(hub(page)).toContainText('Getting started · 1/3');await hub(page).locator('[data-hub-primary]').click();await expect(page.locator('#programming-workspace-primary')).toBeFocused();expect(await page.evaluate(()=>data.workouts.length)).toBe(0);expect(await page.evaluate(()=>data.phasePrograms.length)).toBe(0);
});
test('athlete logs a workout, reloads offline and resumes exact actual entries before saving',async({page})=>{
 await hub(page).getByText('Training tools',{exact:true}).click();await hub(page).locator('[data-hub-train]').click();await page.locator('.ex-name').fill('Bench Press');await page.locator('.set-reps').fill('5');await page.locator('.set-weight').fill('100');await page.locator('.set-rpe').fill('8');await page.evaluate(()=>saveLoggerDraft());
 await page.reload();await expect(page.locator('.ex-name')).toHaveValue('Bench Press');await page.context().setOffline(true);await expect(page.getByRole('button',{name:'Resume workout',exact:true})).toHaveCount(1);await page.locator('#today-training [data-today-resume]').click();await expect(page.locator('.set-weight')).toHaveValue('100');await expect(page.locator('.set-rpe')).toHaveValue('8');
 await page.locator('#training-cockpit [data-cockpit-review]').click();await page.locator('#confirm-workout-save').click();await expect(page.locator('#workout-review')).not.toBeVisible();expect(await page.evaluate(()=>data.workouts[0].exercises[0].sets[0].rpe)).toBe(8);await page.context().setOffline(false);await page.reload();await expect(page.locator('.ex-name')).toHaveCount(1);expect(await page.evaluate(()=>data.workouts.length)).toBe(1);await expect(hub(page)).toContainText('Keep your training moving');
});
test('Home Coach and Decisions share evidence and no read-only visit changes targets',async({page})=>{
 await page.evaluate(async s=>{data=normalizeDataShape({...data,...s});await persistNow(data);invalidateViews();renderDashboard();},fixture());const before=await page.evaluate(()=>JSON.stringify(data));const detail=await hub(page).locator('.training-hub-review').textContent();await hub(page).locator('[data-hub-week]').click();await expect(page.getByRole('dialog',{name:'Weekly review',exact:true})).toContainText('Squat');await page.keyboard.press('Escape');
 await page.evaluate(()=>{showTab('coach');showSubTab('coach','co-today');});await expect(page.locator('[aria-label="Coach training hub"] .training-hub-review')).toHaveText(detail);await page.evaluate(()=>showSubTab('coach','co-programs'));await expect(page.locator('[aria-label="Decisions training hub"] .training-hub-review')).toHaveText(detail);expect(await page.evaluate(()=>JSON.stringify(data))).toBe(before);
});
test('library filters keep focus, unknown movements stay unknown and nested guidance is read-only',async({page},info)=>{
 if(info.project.name==='mobile-chromium')await page.setViewportSize({width:320,height:844});await page.evaluate(()=>{data.exerciseCatalog.push({id:'my-machine',name:'My unusual machine',aliases:['custom machine']});LoadnoteTrainingHubUI.render();});const before=await page.evaluate(()=>JSON.stringify(data));await hub(page).getByText('Training tools',{exact:true}).click();await hub(page).locator('[data-hub-library]').click();const d=page.getByRole('dialog',{name:'Exercise library',exact:true});await d.getByLabel('Search movements').fill('custom machine');await expect(d).toContainText('Equipment not confirmed');await expect(d.getByLabel('Search movements')).toBeFocused();await d.getByLabel('Equipment',{exact:true}).selectOption('cable');await expect(d).toContainText('No matches');await d.getByLabel('Equipment',{exact:true}).selectOption('');await d.getByLabel('Search movements').fill('Bench Press');const row=d.locator('article').filter({has:page.getByRole('heading',{name:'Bench Press',exact:true})});await row.getByText('Instructions & notes',{exact:true}).click();await row.getByRole('button',{name:'Open exercise guidance'}).click();await expect(page.locator('#movement-guidance-dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(d).toBeVisible();
 for(const theme of ['light','dark']){await page.evaluate(t=>document.body.classList.toggle('dark',t==='dark'),theme);await d.screenshot({path:info.outputPath('exercise-library-'+theme+'.png')});expect(await d.evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);}await page.keyboard.press('Escape');await expect(hub(page).locator('[data-hub-library]')).toBeFocused();expect(await page.evaluate(()=>JSON.stringify(data))).toBe(before);
});
test('session constraint routes reach existing previews without modifying a plan',async({page},info)=>{
 const before=await page.evaluate(()=>JSON.stringify(data));await hub(page).getByText('Training tools',{exact:true}).click();await hub(page).locator('[data-hub-adjust]').click();let d=page.getByRole('dialog',{name:'Adjust your session',exact:true});await d.screenshot({path:info.outputPath('session-options.png')});await d.locator('[data-session-option=edit]').click();await expect(page.locator('#program-edit-dialog')).toBeVisible();expect(await page.evaluate(()=>JSON.stringify(data))).toBe(before);await page.keyboard.press('Escape');
});
test('hub fits narrow screens with large text in both themes',async({page},info)=>{
 await page.setViewportSize({width:320,height:844});await page.addStyleTag({content:'html{font-size:20px}'});for(const theme of ['light','dark']){await page.evaluate(t=>document.body.classList.toggle('dark',t==='dark'),theme);await hub(page).screenshot({path:info.outputPath('training-hub-'+theme+'.png')});expect(await hub(page).evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);}
});
test('unreadable sport work stays recoverable and does not duplicate strength Resume',async({page})=>{
 await page.evaluate(()=>{localStorage.setItem('loadnote-sport-draft-v1','unreadable');LoadnoteTrainingHubUI.render();});const before=await page.evaluate(()=>JSON.stringify(data));await hub(page).locator('[data-hub-primary]').click();await expect(page.locator('#sport-planner-panel')).toHaveAttribute('open','');await expect(page.locator('#sp-status')).toContainText('has not been discarded');expect(await page.evaluate(()=>localStorage.getItem('loadnote-sport-draft-v1'))).toBe('unreadable');expect(await page.evaluate(()=>JSON.stringify(data))).toBe(before);
 await page.evaluate(()=>{fillWorkoutForm([{name:'Manual bench',type:'strength',trackBy:'reps',sets:[{weight:100,reps:5}]}],'',false);openFastStartLogger({compact:true});});await page.locator('.set-rpe').fill('8');await page.evaluate(()=>{saveLoggerDraft();showTab('dashboard');renderDashboard();});await expect(page.getByRole('button',{name:'Resume workout',exact:true})).toHaveCount(1);await page.locator('#today-training [data-today-resume]').click();await expect(page.locator('.ex-name')).toHaveValue('Manual bench');await expect(page.locator('.set-weight')).toHaveValue('100');await expect(page.locator('.set-rpe')).toHaveValue('8');expect(await page.evaluate(()=>localStorage.getItem('loadnote-sport-draft-v1'))).toBe('unreadable');
});
