const {test,expect}=require('playwright/test'),{fixture}=require('../fixtures/weekly-coaching');
const hub=page=>page.locator('[data-training-hub="full"]');
test.beforeEach(async({page})=>{await page.clock.install({time:new Date('2026-10-08T18:00:00Z')});await page.goto('/');await expect(page.locator('.ex-name')).toHaveCount(1);});
test('fresh Profile intake guides setup then saves history through actual buttons',async({page},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.getByRole('button',{name:'Profile',exact:true}).click();await page.locator('#profile-athlete-intake').click();await expect(page.locator('#intake-setup-dialog')).toBeVisible();await page.getByRole('button',{name:'Set up and continue',exact:true}).click();await expect(page.locator('#programming-profile-dialog')).toContainText('continue to athlete intake');
 await page.getByRole('button',{name:'Save programming profile',exact:true}).click();await expect(page.locator('#athlete-intake-dialog')).toBeVisible();await page.locator('#intake-years').fill('5');await page.locator('#intake-confirm').check();await page.locator('#athlete-intake-form button[type=submit]').click();await expect(page.locator('#athlete-intake-dialog')).not.toBeVisible();await expect(page.locator('#profile-intake-hint')).toContainText('Recorded');await page.reload();await expect(page.locator('.ex-name')).toHaveCount(1);await page.getByRole('button',{name:'Profile',exact:true}).click();await page.locator('#profile-athlete-intake').click();await expect(page.locator('#intake-years')).toHaveValue('5');
 await page.setViewportSize({width:320,height:844});await page.locator('#athlete-intake-dialog').screenshot({path:info.outputPath('athlete-intake-320.png')});expect(await page.locator('#athlete-intake-dialog').evaluate(d=>d.scrollWidth<=d.clientWidth+1)).toBe(true);expect(errors).toEqual([]);
});
test('cancelled or failed prerequisite cannot create intake or silently save setup',async({page})=>{
 await page.getByRole('button',{name:'Profile',exact:true}).click();await page.locator('#profile-athlete-intake').click();await page.locator('#intake-setup-dialog [data-review-close]').click();expect(await page.evaluate(()=>data.programmingProfiles.length)).toBe(0);
 await page.locator('#profile-athlete-intake').click();await page.getByRole('button',{name:'Set up and continue',exact:true}).click();await page.locator('#profile-close').click();await expect(page.locator('#athlete-intake-dialog')).toHaveCount(0);
 await page.locator('#profile-athlete-intake').click();await page.getByRole('button',{name:'Set up and continue',exact:true}).click();await page.evaluate(()=>{window.originalPersist=persistNow;persistNow=async()=>{throw Error('Storage full');};});await page.getByRole('button',{name:'Save programming profile',exact:true}).click();await expect(page.locator('#profile-error')).toContainText('Storage full');await expect(page.locator('#athlete-intake-dialog')).toHaveCount(0);expect(await page.evaluate(()=>data.programmingProfiles.length)).toBe(0);await page.evaluate(()=>persistNow=window.originalPersist);await page.getByRole('button',{name:'Save programming profile',exact:true}).click();await expect(page.locator('#athlete-intake-dialog')).toBeVisible();
});
test('Decisions intake opens from its real control with saved setup',async({page})=>{
 await page.evaluate(async s=>{data=normalizeDataShape({...data,...s});await persistNow(data);invalidateViews();},fixture());await page.locator('#tab-coach, button[data-tab="coach"]').filter({visible:true}).click();await page.getByRole('button',{name:'Your program',exact:true}).click();await page.locator('#athlete-planning-tools summary').click();await page.locator('#athlete-planning-tools').getByRole('button',{name:'Athlete intake',exact:true}).click();await expect(page.locator('#athlete-intake-form')).toBeVisible();
});
test('a week keeps skipped, unconfirmed and unknown effort separate after corrections and reload',async({page},info)=>{
 await page.evaluate(async s=>{data=normalizeDataShape({...data,...s});const rows=LoadnoteSchedule.list(data.scheduledSessions).filter(r=>r.date>='2026-10-05'&&r.date<='2026-10-08');data.scheduledSessions=LoadnoteSchedule.change(data.scheduledSessions,rows[0].id,{status:'skipped',reason:'Could not train'},'2026-10-08T12:00:00.000Z');const r=rows[1];data.workouts.push({id:'week-actual',date:r.date,createdAt:r.date+'T18:00:00.000Z',sessionIntent:{prescription:r.prescription,schedule:{id:r.id,revisionAt:r.revisionAt}},exercises:[{name:'Squat',type:'strength',sets:[{weight:100,reps:5,rpe:null}]}]});await persistNow(data);invalidateViews();renderDashboard();},fixture({logged:false}));
 const before=await page.evaluate(()=>JSON.stringify(data));await hub(page).locator('.training-week summary').click();await expect(hub(page).locator('.training-week')).toContainText('1 with unknown effort');const text=await hub(page).locator('.training-week').textContent();await hub(page).locator('[data-hub-brief]').click();await expect(page.locator('#workout-brief-dialog')).toBeVisible();await page.keyboard.press('Escape');await page.locator('#tab-coach, button[data-tab="coach"]').filter({visible:true}).click();await page.getByRole('button',{name:'Today',exact:true}).click();await expect(page.locator('[aria-label="Coach training hub"] .training-week')).toHaveText(text);expect(await page.evaluate(()=>JSON.stringify(data))).toBe(before);
 await page.reload();await expect(page.locator('.ex-name')).toHaveCount(1);await page.getByRole('button',{name:'Home',exact:true}).click();await hub(page).locator('.training-week summary').click();await expect(hub(page).locator('.training-week')).toContainText('Unconfirmed is not missed');await page.setViewportSize({width:320,height:844});await hub(page).screenshot({path:info.outputPath('training-week-320.png')});expect(await hub(page).evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);
});
