const {test,expect}=require('playwright/test'),F=require('../fixtures/coaching');
test.beforeEach(async({page})=>{await page.clock.install({time:new Date('2026-10-04T12:00:00Z')});await page.goto('/');await expect(page.locator('#coach-companion-launcher')).toBeVisible();});
async function seed(page,state){await page.evaluate(async s=>{data=normalizeDataShape({...data,...s});await persistNow(data);showTab('coach');showSubTab('coach','co-programs');renderProgrammingWorkspace();document.getElementById('shared-coaching-panel').open=true;renderCoachingReview();},state);}
function growth(){const s=F.hypertrophy();s.hypertrophyPrograms=[];s.scheduledSessions=[];s.workouts=[];s.workloadProfiles=[];s.exerciseCatalog.push({id:'chest',name:'Chest press',muscles:{confirmed:true,mode:'resistance',primary:['chest'],secondary:['triceps']}},{id:'row',name:'Upper back row',muscles:{confirmed:true,mode:'resistance',primary:['upper-back'],secondary:['biceps']}});return s;}
test('guided muscle-growth route reuses goals and creates editable slots, then saves and schedules after review',async({page},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await seed(page,growth());await page.locator('#programming-workspace-primary').click();await expect(page.locator('#guided-plan-dialog')).toBeVisible();await page.locator('#guided-goal').selectOption({label:'Muscle growth'});await page.locator('[data-guided-role=lower]').selectOption('press');await page.locator('[data-guided-role=push]').selectOption('chest');await page.locator('[data-guided-role=pull]').selectOption('row');await page.screenshot({path:info.outputPath('guided-growth.png')});await page.locator('#guided-plan-dialog button[type=submit]').click();await expect(page.locator('#hyp-dialog')).toBeVisible();await expect(page.locator('[data-hyp-slot]')).toHaveCount(3);await expect(page.locator('#hyp-minutes')).toHaveValue('60');
 for(const el of await page.locator('[data-hyp-slot]').all()){await expect(el.locator('[data-slot=load]')).toHaveValue('');await expect(el.locator('[data-slot=confirmed]')).not.toBeChecked();await el.locator('[data-slot=equipment]').selectOption('machine');await el.locator('[data-slot=load]').fill('60');await el.locator('[data-slot=increment]').fill('5');await el.locator('[data-slot=confirmed]').check();}
 expect(await page.evaluate(()=>data.hypertrophyPrograms.length)).toBe(0);await page.locator('#hyp-dialog button[type=submit]').click();await expect(page.locator('#hyp-preview')).toContainText('Review every week');await page.locator('#hyp-preview details').first().locator('summary').click();await page.screenshot({path:info.outputPath('guided-growth-preview.png')});await page.locator('#hyp-workload').check();await page.locator('#hyp-confirm').check();await page.locator('#hyp-save').click();await expect(page.locator('#hyp-dialog')).not.toBeVisible();expect(await page.evaluate(()=>data.scheduledSessions.length)).toBe(0);
 await page.evaluate(()=>LoadnoteHypertrophyBuilderUI.show(data.hypertrophyPrograms[0].id));page.once('dialog',d=>d.accept());await page.locator('[data-hyp-schedule]').click();await expect.poll(()=>page.evaluate(()=>data.scheduledSessions.length)).toBe(4);await page.reload();expect(await page.evaluate(()=>data.hypertrophyPrograms[0].config.slots.length)).toBe(3);expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
for(const mode of ['weightlifting','athlete'])test('guided '+mode+' route keeps technical/drill inputs and review explicit',async({page},info)=>{
 const s=F.sport(mode);s.sportPrograms=[];s.scheduledSessions=[];s.exerciseCatalog.push({id:'support',name:'Squat support',muscles:{confirmed:true,mode:'resistance',primary:['quadriceps'],secondary:['glutes']}});await seed(page,s);await page.locator('#programming-workspace-primary').click();await page.locator('#guided-goal').selectOption({label:'Sport development'});await page.locator('[data-guided-role='+(mode==='weightlifting'?'technical':'quality')+']').selectOption(mode==='weightlifting'?'snatch':'sprint');await page.locator('[data-guided-role=support]').selectOption('support');await page.screenshot({path:info.outputPath('guided-'+mode+'.png')});await page.locator('#guided-plan-dialog button[type=submit]').click();await expect(page.locator('#sp-dialog')).toBeVisible();await expect(page.locator('[data-sp-slot]')).toHaveCount(2);const first=page.locator('[data-sp-slot]').first();await expect(first.locator('[data-sp-field=kind]')).toHaveValue(mode==='weightlifting'?'weightlifting':'speed');await expect(first.locator('[data-sp-field=protocol]')).toHaveValue('');await expect(first.locator('[data-sp-field=confirmed]')).not.toBeChecked();await expect(page.locator('#sp-adult')).not.toBeChecked();await expect(page.locator('#sp-coach')).not.toBeChecked();await page.locator('#sp-dialog button[type=submit]').click();await expect(page.locator('#sp-error')).not.toHaveText('');expect(await page.evaluate(()=>data.sportPrograms.length)).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('guided missing goal and mapping actions work without creating training',async({page})=>{
 await seed(page,{athleteGoals:[],exerciseCatalog:[]});await page.evaluate(()=>LoadnoteGuidedPlanUI.open('weightlifting'));await expect(page.locator('#guided-context')).toContainText('Create an active goal');await page.locator('#guided-plan-dialog button[type=submit]').click();await expect(page.locator('#guided-error')).toContainText('Complete the matching goal');await page.locator('#guided-goals').click();await expect(page.locator('[data-panel=coach][data-sub=co-goals]')).toBeVisible();await page.evaluate(()=>LoadnoteGuidedPlanUI.open('hypertrophy'));await page.locator('#guided-mapping').click();await expect(page.locator('#muscle-workload')).toBeVisible();expect(await page.evaluate(()=>data.scheduledSessions.length)).toBe(0);
});
async function approve(page){await page.locator('#coaching-proposals summary').click();await page.locator('[data-coaching-proposal]').click();await page.locator('#coaching-response').selectOption('accepted');await page.locator('#coaching-proposal-confirm').check();await page.getByRole('button',{name:'Save reviewed response'}).click();await expect(page.locator('#coaching-proposal-dialog')).not.toBeVisible();}
test('second reviewed increase uses two new sessions at the approved dose and survives reload',async({page},info)=>{
 await page.clock.setSystemTime(new Date('2026-10-12T20:00:00Z'));await seed(page,F.hypertrophy(8));await approve(page);expect(await page.evaluate(()=>data.coachingReviews[0].proposal.toKg)).toBe(65);expect(await page.evaluate(()=>LoadnoteCoachingReview.proposals(data,{asOf:today()}).proposals.length)).toBe(0);
 await page.clock.setSystemTime(new Date('2026-10-26T20:00:00Z'));await page.evaluate(async()=>{for(const row of LoadnoteSchedule.list(data.scheduledSessions).slice(2,4))data.workouts.push({id:'follow-'+row.id,date:row.date,createdAt:row.date+'T18:00:00.000Z',sessionIntent:{schedule:{id:row.id,revisionAt:row.revisionAt},prescription:structuredClone(row.prescription),deviationReason:'none'},exercises:[{exerciseId:'press',name:'Leg press',type:'strength',sets:Array.from({length:3},()=>({weight:65,reps:12,rpe:8}))}]});data=LoadnoteMuscleReview.save(data,{coverage:'complete',from:'2026-10-01',through:today(),tolerance:'tolerated',targets:{}},{now:'2026-10-26T19:00:00.000Z',expected:LoadnoteMuscleReview.current(data.workloadProfiles)});await persistNow(data);renderCoachingReview();});await page.locator('#coaching-proposals summary').click();await expect(page.locator('#coaching-proposals')).toContainText('65 → 70');await page.locator('[data-coaching-proposal]').click();await page.locator('#coaching-proposal-dialog details summary').first().click();await page.screenshot({path:info.outputPath('second-progression-preview.png')});await page.locator('#coaching-response').selectOption('accepted');await page.locator('#coaching-proposal-confirm').check();await page.getByRole('button',{name:'Save reviewed response'}).click();await expect(page.locator('#coaching-proposal-dialog')).not.toBeVisible();await page.reload();expect(await page.evaluate(()=>data.coachingReviews.filter(r=>r.response==='accepted').length)).toBe(2);expect(await page.evaluate(()=>data.hypertrophyPrograms[0].config.slots[0].weightKg)).toBe(60);expect(await page.evaluate(()=>data.workouts.map(w=>w.exercises[0].sets[0].weight))).toEqual([60,60,65,65]);expect(await page.evaluate(()=>LoadnoteHypertrophyBuilder.progression(data,'hyp',{asOf:'2026-10-26'}).findings[0].currentKg)).toBe(70);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
