const {test,expect}=require('playwright/test'),{fixture}=require('../fixtures/program-review');
test.beforeEach(async({page})=>{
 await page.clock.install({time:new Date('2026-09-24T12:00:00Z')});
 await page.route('**/api/auth/session',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({authenticated:false,authConfigured:false})}));
 await page.goto('/');await expect(page.locator('#coach-companion-launcher')).toBeVisible();
 await page.evaluate(seed=>{data=normalizeDataShape({...data,...seed});window.localRequests=[];window.onlineCalls=0;window.voiceStops=0;window.LoadnoteCoachVoiceUI={stop:()=>voiceStops++};window.LoadnoteCoachClient={ensureSignedIn:async()=>{onlineCalls++;return true;},ask:async()=>{onlineCalls++;throw Error('Online must not run');}};window.LoadnoteLocalCoachAI=LoadnoteLocalCoachAI.create({gpu:()=>({requestAdapter:async()=>({})}),loadRuntime:async()=>({prebuiltAppConfig:{model_list:[{model_id:'Test-Instruct',vram_required_MB:500}]},CreateMLCEngine:async()=>({unload:async()=>{},interruptGenerate:async()=>{},chat:{completions:{create:async request=>{const p=JSON.parse(request.messages[1].content);localRequests.push(p);const text=p.training!==undefined?(window.rejectLocal?'Use 100 kg.':'A manageable routine can help you stay consistent. What gets in your way?'):/injury/.test(p.question)?'I cannot decide that; ask a qualified professional.':'Speed intent preserves controlled technique.';return {choices:[{message:{content:JSON.stringify({text})}}]};}}}})})});},fixture());
});
async function setup(page,context=true){await page.locator('#coach-companion-launcher').click();await page.locator('#cc-local-ai').click();const d=page.locator('#coaching-library-dialog');await expect(d.locator('#local-ai-details')).toHaveAttribute('open','');await d.locator('#local-ai-consent').check();if(context)await d.locator('#local-ai-context-consent').check();await d.locator('#local-ai-enable').click();await expect(d.locator('#local-ai-status')).toContainText('ready');await d.locator('[data-review-close]').click();}
async function ask(page,q){await page.locator('#cc-input').fill(q);await page.locator('#cc-form button').click();await expect(page.locator('#cc-form button')).toBeEnabled();}
test('local conversation reads fresh context and shares replies with full Coach without online calls',async({page})=>{
 await setup(page);await page.locator('#coach-companion-launcher').click();await expect(page.locator('#cc-context')).toContainText('Local AI ready');const before=await page.evaluate(()=>JSON.stringify(data));await ask(page,'Help me stay consistent');await expect(page.locator('#cc-messages .assistant').last()).toContainText('Local AI conversation (experimental)');expect(await page.evaluate(()=>localRequests.at(-1).training.weekly.loggedSessions)).toBe(0);
 expect(await page.evaluate(()=>JSON.stringify(data))).toBe(before);await page.evaluate(()=>{data.workouts[0].date='2026-09-24';});await ask(page,'What tends to help with consistency?');expect(await page.evaluate(()=>localRequests.at(-1).training.weekly.loggedSessions)).toBe(1);expect(await page.evaluate(()=>localRequests.at(-1).history.length)).toBeGreaterThan(0);
 await page.evaluate(()=>{LoadnoteCoachCompanionUI.close();showTab('coach');showSubTab('coach','co-chat');});await expect(page.locator('#chat-messages')).toContainText('A manageable routine');expect(await page.evaluate(()=>onlineCalls)).toBe(0);expect(await page.evaluate(()=>voiceStops)).toBeGreaterThan(0);await page.evaluate(()=>refreshCoachAnalysis());expect(await page.evaluate(()=>onlineCalls)).toBe(0);await page.evaluate(()=>LoadnoteCoachCompanionUI.clearConversation());await expect(page.locator('#chat-messages')).not.toContainText('A manageable routine');expect(await page.evaluate(()=>LoadnoteCoachCompanionUI.history())).toEqual([]);
});
test('context consent is separate; medical, changes and rejected output keep reviewed local guidance',async({page})=>{
 await setup(page,false);expect(await page.evaluate(()=>LoadnoteLocalCoachAI.snapshot().conversationConsent)).toBe(false);await page.evaluate(()=>LoadnoteCoachingLibraryUI.open({localAI:true}));const d=page.locator('#coaching-library-dialog');await d.locator('#local-ai-context-consent').check();await d.locator('#local-ai-enable').click();await expect(d.locator('#local-ai-status')).toContainText('private Coach conversation selected');await d.locator('[data-review-close]').click();await page.locator('#coach-companion-launcher').click();const before=await page.evaluate(()=>JSON.stringify(data));
 await ask(page,'My Achilles hurts');await expect(page.locator('#cc-messages .assistant').last()).toContainText('cannot');expect(await page.evaluate(()=>localRequests.length)).toBe(2);await ask(page,'Should I add weight?');expect(await page.evaluate(()=>localRequests.length)).toBe(2);
 await page.evaluate(()=>window.rejectLocal=true);await ask(page,'Help me stay consistent');await expect(page.locator('#cc-messages .assistant').last()).not.toContainText('100 kg');expect(await page.evaluate(()=>onlineCalls)).toBe(0);expect(await page.evaluate(()=>JSON.stringify(data))).toBe(before);
 await page.locator('#cc-local-ai').click();await d.locator('#local-ai-disable').click();await expect(d.locator('#local-ai-status')).toContainText('off');expect(await page.evaluate(()=>LoadnoteLocalCoachAI.snapshot().conversationConsent)).toBe(false);
});
