const {test,expect}=require('playwright/test'),{phaseFixture}=require('../fixtures/phase-builder');
test.use({serviceWorkers:'allow'});
test.beforeEach(async({page})=>{
 await page.clock.install({time:new Date('2026-12-19T17:00:00.000Z')});
 await page.goto('/');await expect(page.locator('.ex-name')).toHaveCount(1);
 await page.evaluate(seed=>{
  data=normalizeDataShape({...data,...seed.state});
  const args={asOf:'2026-09-24',now:'2026-09-24T12:00:00.000Z'};
  data=LoadnotePhaseBuilder.save(data,LoadnotePhaseBuilder.prepare(data,seed.config,args),{confirmed:true},{...args,id:'setup'});
  const plan=LoadnoteMeetCycle.prepare(data,data.phasePrograms[0],{version:1,weeks:12,peakWeeks:2,taperWeeks:1,meetDate:'2026-12-19'},args);
  data=LoadnoteMeetCycle.save(data,plan,{confirmed:true},{...args,id:'meet12'});
  data=LoadnoteMeetCycle.schedule(data,'meet12',{...args,now:'2026-09-24T13:00:00.000Z'});
  showTab('coach');showSubTab('coach','co-programs');document.getElementById('phase-builder-panel').open=true;renderPhaseBuilder();
 },phaseFixture());
 await page.locator('[data-cycle="meet12"] > summary').click();
 await page.locator('[data-mock-meet="meet12"] .mock-meet-results > summary').click();
});
test('meet execution captures only athlete-entered made/missed/passed attempts, preserves schedule, survives reload',async({page})=>{
 const host=page.locator('[data-mock-meet="meet12"]');
 await expect(host.locator('[data-meet-status]')).toHaveCount(9);
 const before=await page.evaluate(()=>JSON.stringify({workouts:data.workouts,scheduledSessions:data.scheduledSessions,original:data.meetCycles[0].sessions}));
 await host.locator('[data-meet-status="squat-0"]').selectOption('made');
 await host.locator('[data-meet-weight="squat-0"]').fill('150');
 await host.locator('[data-meet-status="squat-1"]').selectOption('missed');
 await host.locator('[data-meet-weight="squat-1"]').fill('165');
 await host.locator('[data-meet-status="bench-0"]').selectOption('made');
 await host.locator('[data-meet-weight="bench-0"]').fill('90');
 await host.locator('[data-meet-status="deadlift-0"]').selectOption('made');
 await host.locator('[data-meet-weight="deadlift-0"]').fill('190');
 await host.locator('[data-meet-status="deadlift-1"]').selectOption('passed');
 await expect(host.locator('[data-meet-weight="deadlift-1"]')).toBeDisabled();
 await host.locator('[data-meet-save]').click();
 await expect(host.locator('[data-meet-error]')).toContainText('confirm');
 await host.locator('[data-meet-confirm]').check();
 await host.locator('[data-meet-save]').click();
 await expect.poll(()=>page.evaluate(()=>data.meetCycles[0].mockMeet?.revisions.length)).toBe(1);
 expect(await page.evaluate(()=>JSON.stringify({workouts:data.workouts,scheduledSessions:data.scheduledSessions,original:data.meetCycles[0].sessions}))).toBe(before);
 const report=await page.evaluate(()=>LoadnoteMockMeet.inspect(data,{cycleId:'meet12',asOf:today()}));
 expect(report.totalKg).toBe(430);expect(report.lifts.squat.missed).toBe(1);
 await page.reload();await page.evaluate(()=>{showTab('coach');showSubTab('coach','co-programs');document.getElementById('phase-builder-panel').open=true;renderPhaseBuilder();});
 await page.locator('[data-cycle="meet12"] > summary').click();
 await page.locator('[data-mock-meet="meet12"] .mock-meet-results > summary').click();
 await expect(page.locator('[data-mock-meet="meet12"]')).toContainText('430');
 await expect(page.locator('[data-mock-meet="meet12"] .mock-meet-recap')).toContainText('Post-cycle training recap');
});
test('mobile lb entry converts once to stored kg, corrections are auditable, incomplete total stays blank',async({page})=>{
 await page.setViewportSize({width:375,height:812});
 await page.evaluate(()=>{data.unit='lb';renderMeetCycle();});
 await page.locator('[data-cycle="meet12"] > summary').click();
 await page.locator('[data-mock-meet="meet12"] .mock-meet-results > summary').click();
 const host=page.locator('[data-mock-meet="meet12"]');
 await expect(host).toContainText('lb');
 await host.locator('[data-meet-status="squat-0"]').selectOption('made');
 await host.locator('[data-meet-weight="squat-0"]').fill('220.46');
 await host.locator('[data-meet-confirm]').check();
 await host.locator('[data-meet-save]').click();
 await expect.poll(()=>page.evaluate(()=>data.meetCycles[0].mockMeet?.revisions.length)).toBe(1);
 expect(await page.evaluate(()=>data.meetCycles[0].mockMeet.revisions[0].context.attempts.squat[0].weightKg)).toBeCloseTo(100,1);
 expect(await page.evaluate(()=>LoadnoteMockMeet.inspect(data,{cycleId:'meet12',asOf:today()}).totalKg)).toBeNull();
 await page.locator('[data-mock-meet="meet12"] .mock-meet-results > summary').click();
 const refreshed=page.locator('[data-mock-meet="meet12"]');
 await refreshed.locator('[data-meet-status="bench-0"]').selectOption('made');await refreshed.locator('[data-meet-weight="bench-0"]').fill('198.42');
 await refreshed.locator('[data-meet-status="deadlift-0"]').selectOption('made');await refreshed.locator('[data-meet-weight="deadlift-0"]').fill('440.92');
 await refreshed.locator('[data-meet-confirm]').check();await refreshed.locator('[data-meet-save]').click();
 await expect.poll(()=>page.evaluate(()=>data.meetCycles[0].mockMeet?.revisions.length)).toBe(2);
 expect(await page.evaluate(()=>LoadnoteMockMeet.inspect(data,{cycleId:'meet12',asOf:today()}).totalKg)).toBeCloseTo(390,1);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});

test('competition meet stays distinct from mock meet in UI and result storage',async({page})=>{
 await page.evaluate(()=>{
  const args={asOf:'2026-09-24',now:'2026-09-24T12:00:00.000Z'};
  data.meetCycles=[];data.scheduledSessions=[];
  const plan=LoadnoteMeetCycle.prepare(data,data.phasePrograms[0],{version:1,weeks:12,peakWeeks:2,taperWeeks:1,meetDate:'2026-12-16',eventType:'competition',eventName:'State Championships'},args);
  data=LoadnoteMeetCycle.save(data,plan,{confirmed:true},{...args,id:'real12'});
  data=LoadnoteMeetCycle.schedule(data,'real12',{...args,now:'2026-09-24T13:00:00.000Z'});
  renderMeetCycle();
 });
 await page.locator('[data-cycle="real12"] > summary').click();
 const host=page.locator('[data-meet-result="real12"]');await host.locator('.mock-meet-results > summary').click();
 await expect(host).toContainText('Competition meet');
 await expect(host).toContainText('State Championships');
 await expect(host).toContainText('does not verify official federation results');
 await host.locator('[data-meet-status="squat-0"]').selectOption('made');await host.locator('[data-meet-weight="squat-0"]').fill('170');
 await host.locator('[data-meet-status="bench-0"]').selectOption('made');await host.locator('[data-meet-weight="bench-0"]').fill('100');
 await host.locator('[data-meet-status="deadlift-0"]').selectOption('made');await host.locator('[data-meet-weight="deadlift-0"]').fill('220');
 await host.locator('[data-meet-confirm]').check();await host.locator('[data-meet-save]').click();
 await expect.poll(()=>page.evaluate(()=>data.meetCycles[0].meetResult?.revisions.length)).toBe(1);
 expect(await page.evaluate(()=>data.meetCycles[0].mockMeet)).toBeUndefined();
 const report=await page.evaluate(()=>LoadnoteMeetResult.inspect(data,{cycleId:'real12',asOf:today()}));
 expect(report.eventType).toBe('competition');expect(report.eventLabel).toBe('State Championships');expect(report.totalKg).toBe(490);
});
