const {test,expect}=require('playwright/test'),{fixture}=require('../fixtures/program-review');
test.use({serviceWorkers:'allow'});
test.beforeEach(async({page})=>{await page.clock.install({time:new Date('2026-09-01T12:00:00Z')});await page.goto('/');await expect(page.locator('.ex-name')).toHaveCount(1);await page.evaluate(seed=>{data=normalizeDataShape({...data,...seed});showTab('coach');showSubTab('coach','co-programs');renderProgrammingProfile();},fixture());await page.locator('#programming-profile-panel > summary').click();await page.locator('#profile-edit').click();});
async function equipment(page){for(const k of ['barbell','plates','rack','bench'])await page.locator(`[data-profile-equipment="${k}"]`).check();}
async function builder(page){await page.locator('#reviewed-builder-panel > summary').click();await page.locator('#builder-new').click();for(const [k,v]of Object.entries({squat:'160',bench:'120',deadlift:'220'}))await page.locator('#builder-'+k).fill(v);await page.locator('#builder-equipment').check();await page.locator('#builder-dialog button[type="submit"]').click();}
test('profile snapshot informs builder and survives offline reload without changing history',async({page,context})=>{
 const history=await page.evaluate(()=>JSON.stringify({workouts:data.workouts,programs:data.reviewedPrograms,schedule:data.scheduledSessions}));await equipment(page);await page.locator('#profile-priorities').fill('Upper back — reported priority');await page.locator('#programming-profile-dialog button[type="submit"]').click();await expect(page.locator('#programming-profile-dialog')).not.toBeVisible();expect(await page.evaluate(()=>data.programmingProfiles.length)).toBe(1);
 await builder(page);await expect(page.locator('#builder-preview')).toContainText('Programming profile used');await page.locator('#builder-preview details').first().locator('summary').click();await expect(page.locator('#builder-preview')).toContainText('Upper back — reported priority');expect(await page.evaluate(()=>document.getElementById('builder-dialog').scrollWidth<=document.getElementById('builder-dialog').clientWidth+1)).toBe(true);await page.locator('#builder-close').click();
 expect(await page.evaluate(()=>JSON.stringify({workouts:data.workouts,programs:data.reviewedPrograms,schedule:data.scheduledSessions}))).toBe(history);
 expect(await page.evaluate(()=>JSON.stringify(normalizeDataShape(JSON.parse(JSON.stringify(data))).programmingProfiles)===JSON.stringify(data.programmingProfiles))).toBe(true);
 await page.evaluate(()=>navigator.serviceWorker.ready);await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);await context.setOffline(true);await page.reload();await expect(page.locator('.ex-name')).toHaveCount(1);expect(await page.evaluate(()=>data.programmingProfiles[0].context.priorities)).toBe('Upper back — reported priority');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('failed profile write preserves data and avoided lift blocks generation',async({page})=>{
 await equipment(page);await page.evaluate(()=>{window.realProfilePersist=persistNow;persistNow=async()=>{throw Error('Storage full');};});await page.locator('#programming-profile-dialog button[type="submit"]').click();await expect(page.locator('#profile-error')).toContainText('Storage full');expect(await page.evaluate(()=>data.programmingProfiles.length)).toBe(0);
 await page.evaluate(()=>persistNow=window.realProfilePersist);await page.locator('#programming-profile-dialog details > summary').click();await page.locator('[data-profile-exercise="s"]').selectOption('avoided');await page.locator('#programming-profile-dialog button[type="submit"]').click();await expect(page.locator('#programming-profile-dialog')).not.toBeVisible();await builder(page);await expect(page.locator('#builder-error')).toContainText('marked avoided');await expect(page.locator('#builder-preview')).toBeEmpty();await page.locator('#builder-close').click();
 page.once('dialog',d=>d.accept());await page.locator('#profile-clear').click();await expect.poll(()=>page.evaluate(()=>data.programmingProfiles.length)).toBe(2);expect(await page.evaluate(()=>LoadnoteProgrammingProfile.current(data.programmingProfiles))).toBe(null);expect(await page.evaluate(()=>data.workouts.length)).toBe(3);
});
