const {test,expect}=require('playwright/test');
test.use({serviceWorkers:'allow'});
test.beforeEach(async({page})=>{await page.goto('/');await expect(page.locator('.ex-name')).toHaveCount(1);await page.evaluate(()=>{data.exerciseCatalog=[{id:'s',name:'Competition Squat',aliases:[]},{id:'b',name:'Competition Bench',aliases:[]},{id:'d',name:'Competition Sumo Deadlift',aliases:[]}];data.exerciseRoles=[];['squat','bench','deadlift'].forEach((l,i)=>{data.exerciseRoles=LoadnoteReadiness.upsert(data.exerciseRoles,{exerciseId:data.exerciseCatalog[i].id,role:'competition',competitionLift:l});});showTab('coach');showSubTab('coach','co-programs');renderPowerliftingBuilder();});await page.locator('#reviewed-builder-panel > summary').click();});
async function preview(page){await page.locator('#builder-new').click();await page.locator('#builder-equipment').check();await page.locator('#builder-squat').fill('160');await page.locator('#builder-bench').fill('120');await page.locator('#builder-deadlift').fill('220');await page.getByRole('button',{name:'Generate preview',exact:true}).click();await expect(page.locator('#builder-preview')).toContainText('12 sessions');}
test('review, save, offline reload and explicit scheduling preserve existing drafts',async({page,context})=>{
 await page.evaluate(()=>{document.querySelector('.ex-name').value='Keep my draft';saveLoggerDraft();});const draft=await page.evaluate(()=>localStorage.getItem(LOGGER_DRAFT_KEY));await preview(page);await page.locator('#builder-save').click();await expect(page.locator('#builder-error')).toContainText('confirm before saving');expect(await page.evaluate(()=>data.reviewedPrograms.length)).toBe(0);
 await page.locator('#builder-confirm').check();await page.locator('#builder-save').click();await expect(page.locator('#builder-dialog')).not.toBeVisible();expect(await page.evaluate(()=>data.scheduledSessions.length)).toBe(0);expect(await page.evaluate(()=>localStorage.getItem(LOGGER_DRAFT_KEY))).toBe(draft);
 expect(await page.evaluate(()=>JSON.stringify(normalizeDataShape(JSON.parse(JSON.stringify(data))).reviewedPrograms)===JSON.stringify(data.reviewedPrograms))).toBe(true);
 await page.evaluate(()=>navigator.serviceWorker.ready);await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);await context.setOffline(true);await page.reload();await expect(page.locator('.ex-name')).toHaveCount(1);await page.evaluate(()=>{showTab('coach');showSubTab('coach','co-programs');renderPowerliftingBuilder();document.getElementById('reviewed-builder-panel').open=true;});
 await page.locator('#reviewed-builder > div > details > summary').click();page.once('dialog',d=>d.accept());await page.locator('[data-builder-schedule]').click();await expect.poll(()=>page.evaluate(()=>data.scheduledSessions.length)).toBe(12);await expect(page.locator('#reviewed-builder')).toContainText('Scheduled');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('edited inputs invalidate preview and failed saves keep reviewed programs unchanged',async({page})=>{
 await preview(page);await page.locator('#builder-sets').fill('2');await expect(page.locator('#builder-preview')).toBeEmpty();await page.getByRole('button',{name:'Generate preview',exact:true}).click();await page.locator('#builder-confirm').check();await page.evaluate(()=>{persistNow=async()=>{throw Error('Storage full');};});await page.locator('#builder-save').click();await expect(page.locator('#builder-error')).toContainText('Storage full');expect(await page.evaluate(()=>data.reviewedPrograms.length)).toBe(0);
});
