const {test,expect}=require('playwright/test'),{fixture}=require('../fixtures/program-review');
test.use({serviceWorkers:'allow'});
test.beforeEach(async({page})=>{await page.clock.install({time:new Date('2026-09-13T22:00:00Z')});await page.goto('/');await expect(page.locator('.ex-name')).toHaveCount(1);await page.evaluate(seed=>{data=normalizeDataShape({...data,...seed});showTab('coach');showSubTab('coach','co-programs');renderProgramWeekReview();},fixture());await page.locator('#program-week-review-panel > summary').click();});
async function review(page){await page.locator('#week-review-program').selectOption('p');await page.locator('[data-review-check="discomfort"]').selectOption('none');await page.locator('#week-review-generate').click();await expect(page.locator('#week-review-report')).toContainText('Consider reducing');await page.locator('[data-review-choice="squat"]').selectOption('reduce');}
test('approved future changes persist offline and preserve original plans and history',async({page,context})=>{
 await review(page);const original=await page.evaluate(()=>JSON.stringify({workouts:data.workouts,programs:data.reviewedPrograms,first:data.scheduledSessions[3].revisions[0]}));await page.locator('#week-review-apply').click();await expect(page.locator('#week-review-error')).toContainText('Confirm');expect(await page.evaluate(()=>data.programReviews.length)).toBe(0);
 await page.locator('#week-review-confirm').check();await page.locator('#week-review-apply').click();await expect.poll(()=>page.evaluate(()=>data.programReviews.length)).toBe(1);expect(await page.evaluate(()=>JSON.stringify({workouts:data.workouts,programs:data.reviewedPrograms,first:data.scheduledSessions[3].revisions[0]}))).toBe(original);
 expect(await page.evaluate(()=>data.scheduledSessions[3].revisions.length)).toBe(2);expect(await page.evaluate(()=>JSON.stringify(normalizeDataShape(JSON.parse(JSON.stringify(data))).programReviews)===JSON.stringify(data.programReviews))).toBe(true);
 await page.evaluate(()=>navigator.serviceWorker.ready);await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);await context.setOffline(true);await page.reload();await expect(page.locator('.ex-name')).toHaveCount(1);expect(await page.evaluate(()=>data.programReviews.length)).toBe(1);expect(await page.evaluate(()=>data.scheduledSessions[3].revisions.length)).toBe(2);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('failed storage and open target draft prevent changes',async({page})=>{
 await review(page);await page.locator('#week-review-confirm').check();await page.evaluate(()=>{window.realPersist=persistNow;persistNow=async()=>{throw Error('Storage full');};});await page.locator('#week-review-apply').click();await expect(page.locator('#week-review-error')).toContainText('Storage full');expect(await page.evaluate(()=>data.scheduledSessions[3].revisions.length)).toBe(1);
 await page.evaluate(()=>{persistNow=window.realPersist;pendingScheduledSession={id:data.scheduledSessions[3].id};});await page.locator('#week-review-apply').click();await expect(page.locator('#week-review-error')).toContainText('workout draft');expect(await page.evaluate(()=>data.programReviews.length)).toBe(0);
});
