const {test,expect}=require('playwright/test');
test.beforeEach(async({page})=>{
 await page.clock.install({time:new Date('2026-10-04T12:00:00Z')});
 await page.route('**/api/auth/session',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({authenticated:false,authConfigured:false})}));
 await page.goto('/');await expect(page.locator('#coach-companion-launcher')).toBeVisible();
 await page.evaluate(()=>{data=normalizeDataShape({...data,exerciseCatalog:[{id:'clean',name:'Hang power clean',aliases:[]}],workouts:[],prs:[]});showTab('dashboard');renderSchedule();document.getElementById('home-week-plan').open=true;});
});
async function createGoal(page,primary='athlete'){
 await page.locator('#goal-new').click();await page.locator('#goal-name').fill(primary==='athlete'?'Basketball season':'Olympic practice');await page.locator('#goal-sport').fill(primary==='athlete'?'Basketball':'Weightlifting');await page.locator('#goal-minutes').fill('60');await page.locator('#goal-equipment').fill('Rack and dumbbells');await page.locator('[data-goal-day][value="0"]').check();await page.locator('#goal-context-toggle').click();
 await page.locator('#goal-primary').selectOption(primary);await page.locator('#goal-season').selectOption('in-season');await page.locator('#goal-schedule-known').check();await page.locator('[data-goal-practice][value="0"]').check();await page.locator('#goal-dialog button[type=submit]').click();await expect(page.locator('#goal-dialog')).not.toBeVisible();
}
async function decisions(page){await page.evaluate(()=>{showTab('coach');showSubTab('coach','co-programs');renderDecisionReadiness();});await page.locator('summary').filter({hasText:'Muscle workload & training knowledge'}).click();await page.locator('#sport-training-review > summary').click();}
async function attemptForm(page){
 await page.locator('#olympic-practice-open').click();await page.locator('#practice-goal').selectOption({label:'Olympic practice'});await page.locator('#practice-exercise').selectOption('clean');await page.locator('#practice-family').selectOption('clean');await page.locator('#practice-variation').fill('Hang power clean');await page.locator('.practice-load').fill('132.277357');await page.locator('.practice-outcome').selectOption('missed');await page.locator('.practice-quality').selectOption('inconsistent');
}
test('structured goals persist and shared review exposes declared scheduling constraints',async({page})=>{
 const before=await page.evaluate(()=>JSON.stringify({workouts:data.workouts,programs:data.programs,programmingProfiles:data.programmingProfiles}));await createGoal(page);await decisions(page);await expect(page.locator('#sport-review-explanation')).toContainText('Gym and declared sport days overlap');await expect(page.locator('#sport-review-explanation')).toContainText('not completed workload');
 expect(await page.evaluate(()=>JSON.stringify({workouts:data.workouts,programs:data.programs,programmingProfiles:data.programmingProfiles}))).toBe(before);await page.screenshot({path:test.info().outputPath('sport-review.png')});
 await page.reload();await expect(page.locator('#coach-companion-launcher')).toBeVisible();expect(await page.evaluate(()=>LoadnoteGoals.list(data.athleteGoals)[0].trainingContext.practiceDays)).toEqual([0]);expect(await page.evaluate(()=>data.schemaVersion)).toBe(30);
});
test('Olympic practice handles failure, units, correction and void without touching strength PRs',async({page})=>{
 await createGoal(page,'weightlifting');await page.evaluate(()=>{data.unit='lb';});await decisions(page);await attemptForm(page);const before=await page.evaluate(()=>JSON.stringify(data));await page.screenshot({path:test.info().outputPath('practice-dialog.png')});
 await page.evaluate(()=>{window.originalPersist=persistNow;persistNow=async()=>{throw Error('Practice write failed');};});await page.locator('#olympic-practice-dialog button[type=submit]').click();await expect(page.locator('#practice-status')).toContainText('Practice write failed');expect(await page.evaluate(()=>JSON.stringify(data))).toBe(before);
 await page.evaluate(()=>{persistNow=window.originalPersist;});await page.locator('#olympic-practice-dialog button[type=submit]').click();await expect(page.locator('#olympic-practice-dialog')).not.toBeVisible();expect(await page.evaluate(()=>data.workouts.length)).toBe(0);expect(await page.evaluate(()=>data.prs.length)).toBe(0);expect(await page.evaluate(()=>LoadnoteSportContext.listPractice(data.olympicPractice)[0].attempts[0].kg)).toBeCloseTo(60,4);
 const exactKg=await page.evaluate(()=>LoadnoteSportContext.listPractice(data.olympicPractice)[0].attempts[0].kg);
 await page.locator('#sport-training-review details > summary').click();await page.locator('[data-practice-edit]').click();await page.locator('.practice-outcome').selectOption('made');await page.locator('#olympic-practice-dialog button[type=submit]').click();await expect(page.locator('#olympic-practice-dialog')).not.toBeVisible();expect(await page.evaluate(()=>data.olympicPractice[0].revisions.length)).toBe(2);await expect(page.locator('#sport-review-explanation')).toContainText('1 made, 0 missed');
 expect(await page.evaluate(()=>LoadnoteSportContext.listPractice(data.olympicPractice)[0].attempts[0].kg)).toBe(exactKg);
 await page.reload();await expect(page.locator('#coach-companion-launcher')).toBeVisible();expect(await page.evaluate(()=>data.olympicPractice[0].revisions.length)).toBe(2);await decisions(page);await page.locator('#sport-training-review details > summary').click();page.once('dialog',d=>d.accept());await page.locator('[data-practice-void]').click();await expect.poll(()=>page.evaluate(()=>LoadnoteSportContext.listPractice(data.olympicPractice).length)).toBe(0);expect(await page.evaluate(()=>data.olympicPractice[0].revisions.length)).toBe(3);
});
test('Coach and Companion share fresh sport evidence and bounded follow-up context',async({page})=>{
 await createGoal(page,'weightlifting');await decisions(page);await attemptForm(page);await page.locator('#olympic-practice-dialog button[type=submit]').click();await expect(page.locator('#olympic-practice-dialog')).not.toBeVisible();const before=await page.evaluate(()=>JSON.stringify(data));await page.evaluate(()=>showSubTab('coach','co-chat'));
 async function ask(q){await page.locator('#chat-input').fill(q);await page.locator('#chat-send-btn').click();await expect(page.locator('#chat-send-btn')).toBeEnabled();}
 await ask('How is my Olympic practice?');await expect(page.locator('#chat-messages')).toContainText('0 made, 1 missed');await ask('Should I add weight?');await expect(page.locator('#chat-messages')).toContainText('no estimated 1RM or load increase');
 await page.locator('#coach-companion-launcher').click();await page.locator('#cc-input').fill('How is my Olympic practice?');await page.locator('#cc-form button').click();await expect(page.locator('#cc-form button')).toBeEnabled();await expect(page.locator('#cc-messages')).toContainText('0 made, 1 missed');expect(await page.evaluate(()=>JSON.stringify(data))).toBe(before);
});
test('malformed practice imports are rejected and ambiguous priorities are not guessed',async({page})=>{
 expect(await page.evaluate(()=>{try{normalizeDataShape({olympicPractice:[{id:'broken'}]});return false;}catch{return true;}})).toBe(true);
 await createGoal(page);await page.evaluate(()=>{data.athleteGoals=LoadnoteGoals.upsert(data.athleteGoals,{...LoadnoteGoals.list(data.athleteGoals)[0],name:'Second sport'},{now:'2026-10-04T12:00:01.000Z'});});await decisions(page);await expect(page.locator('#sport-review-explanation')).toContainText('Multiple active goals');const id=await page.evaluate(()=>data.athleteGoals[0].id);await page.locator('#sport-review-goal').selectOption(id);await expect(page.locator('#sport-review-explanation')).toContainText('Basketball season');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('a new technical identity can be logged without a placeholder strength workout',async({page})=>{
 await createGoal(page,'weightlifting');await decisions(page);await page.locator('#olympic-practice-open').click();await page.locator('#practice-exercise').selectOption('__practice_new__');await page.locator('#practice-new-name').fill('Block snatch');await page.locator('#practice-family').selectOption('snatch');await page.locator('.practice-load').fill('40');await page.locator('#olympic-practice-dialog button[type=submit]').click();await expect(page.locator('#olympic-practice-dialog')).not.toBeVisible();expect(await page.evaluate(()=>data.exerciseCatalog.some(e=>e.name==='Block snatch'))).toBe(true);expect(await page.evaluate(()=>data.workouts.length)).toBe(0);expect(await page.evaluate(()=>data.prs.length)).toBe(0);expect(await page.evaluate(()=>LoadnoteSportContext.listPractice(data.olympicPractice)[0].attempts[0].outcome)).toBe('unknown');
});
