const {test,expect}=require('playwright/test'),F=require('../fixtures/coaching'),P=require('../../src/product/phase-builder'),A=require('../../src/product/accessory-programming'),{phaseFixture}=require('../fixtures/phase-builder');
test.beforeEach(async({page})=>{await page.clock.install({time:new Date('2026-10-12T20:00:00Z')});await page.goto('/');await expect(page.locator('#coach-companion-launcher')).toBeVisible();});
async function seed(page,s){await page.evaluate(async s=>{data=normalizeDataShape({...data,...s});await persistNow(data);showTab('coach');showSubTab('coach','co-programs');renderProgramLifecycle();renderProgrammingWorkspace();document.getElementById('shared-coaching-panel').open=true;renderCoachingReview();},s);}
function phased(){const {state,config}=phaseFixture();state.workouts=[];state.exerciseCatalog.push({id:'row',name:'Chest-supported Row'});config.accessories=[{policy:A.POLICY,exerciseId:'row',name:'Chest-supported Row',day:0,group:'upper-back',purpose:'hypertrophy',equipment:'dumbbells',equipmentConfirmed:true,mode:'reps',sets:2,weightKg:30,targetRpe:7,minReps:8,maxReps:12}];const args={asOf:'2026-09-24',now:'2026-09-24T12:00:00.000Z'};const saved=P.save(state,P.prepare(state,{...config,periodization:'wave'},args),{confirmed:true},{...args,id:'v3'});return P.schedule(saved,'v3',{...args,now:'2026-09-24T13:00:00.000Z'});}
async function screenshot(page,info,name){await page.screenshot({path:info.outputPath(name)});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}
test('daily brief and Companion share reports, offer working review actions and preserve data',async({page},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await seed(page,F.hypertrophy(8));await page.evaluate(async()=>{data=LoadnoteCoachingReview.weekly(data,{sleep:'poor',fatigue:'elevated',soreness:'usual',notes:'Synthetic check-in'},{asOf:today()});await persistNow(data);renderProgramLifecycle();renderCoachingReview();});const before=await page.evaluate(()=>JSON.stringify({workouts:data.workouts,sessions:data.scheduledSessions,plans:data.hypertrophyPrograms}));await expect(page.locator('#smart-coach-brief')).toContainText('poor sleep');await page.locator('#smart-coach-brief details').first().locator('summary').click();await screenshot(page,info,'daily-coach-brief.png');await page.locator('#coach-companion-launcher').click();await page.locator('#cc-input').fill('What should I focus on today?');await page.locator('#cc-form button').click();await expect(page.locator('#cc-messages')).toContainText('poor sleep');await expect(page.locator('#cc-messages .smart-coach-actions')).toBeVisible();await page.locator('#cc-messages .coach-follow-up').filter({hasText:'What evidence is missing?'}).click();await expect(page.locator('#cc-messages')).toContainText('Record actual sets');await screenshot(page,info,'companion-coaching-actions.png');await page.locator('#cc-messages .smart-coach-actions .btn-secondary').last().click();await expect(page.locator('#coach-companion-panel')).not.toBeVisible();expect(await page.evaluate(()=>JSON.stringify({workouts:data.workouts,sessions:data.scheduledSessions,plans:data.hypertrophyPrograms}))).toBe(before);expect(errors).toEqual([]);
});
test('wave designer creates reviewed real prescriptions and survives reload',async({page},info)=>{
 const {state}=phaseFixture();state.workouts=[];await seed(page,state);await page.evaluate(()=>LoadnotePhaseBuilderUI.open(null,{periodization:'wave'}));await expect(page.locator('#phase-periodization')).toHaveValue('wave');for(const [i,l] of ['squat','bench','deadlift'].entries()){await page.locator('.phase-lift > summary').nth(i).click();await page.locator('#phase-'+l+'-tm').fill(String([160,120,220][i]));}await page.locator('#phase-accumulation').fill('3');await page.locator('#phase-strength').fill('3');await page.locator('#phase-dialog button[type=submit]').click();await expect(page.locator('#phase-preview')).toContainText('Wave 1 / step 1');await page.locator('#phase-preview details').filter({hasText:'Week 1 · accumulation · Wave 1'}).last().locator('summary').first().click();await screenshot(page,info,'wave-loading-preview.png');await page.locator('#phase-confirm').check();await page.locator('#phase-save').click();await expect(page.locator('#phase-dialog')).not.toBeVisible();await page.reload();expect(await page.evaluate(()=>data.phasePrograms.at(-1).config.periodization)).toBe('wave');const reps=await page.evaluate(()=>data.phasePrograms.at(-1).sessions.filter(s=>s.exercises.some(e=>e.lift==='squat'&&e.role==='primary')).slice(0,3).map(s=>s.exercises.find(e=>e.lift==='squat').sets[0].reps));expect(reps).toEqual([5,4,3]);
});
test('cancellation preview preserves completed work, cancels remaining dates, restores and survives reload',async({page},info)=>{
 await seed(page,F.hypertrophy(8));const before=await page.evaluate(()=>JSON.stringify({workouts:data.workouts,plan:data.hypertrophyPrograms}));await page.locator('[data-manage-program]').click();await expect(page.locator('#cancel-preview')).toContainText('2 completed session(s) preserved');await page.locator('#cancel-apply').click();await expect(page.locator('#cancel-error')).toContainText('Confirm cancellation');await page.locator('#cancel-reason').fill('Practice calendar changed');await page.locator('#cancel-confirm').check();await page.locator('#cancel-preview details summary').click();await screenshot(page,info,'cancel-program-preview.png');await page.locator('#cancel-apply').click();await expect(page.locator('#program-cancellation-dialog')).not.toBeVisible();expect(await page.evaluate(()=>LoadnoteProgramLifecycle.programs(data).length)).toBe(0);expect(await page.evaluate(()=>LoadnoteProgrammingWorkspace.route(data,{asOf:today()}).status)).not.toBe('scheduled');expect(await page.evaluate(()=>JSON.stringify({workouts:data.workouts,plan:data.hypertrophyPrograms}))).toBe(before);await page.reload();expect(await page.evaluate(()=>data.programCancellations[0].revisions.at(-1).status)).toBe('cancelled');await page.evaluate(()=>{showTab('coach');showSubTab('coach','co-programs');renderProgramLifecycle();});await page.locator('[data-manage-program]').click();await page.locator('#cancel-confirm').check();await page.clock.setSystemTime(new Date('2026-10-12T20:01:00Z'));await page.locator('#cancel-restore').click();await expect(page.locator('#program-cancellation-dialog')).not.toBeVisible();expect(await page.evaluate(()=>LoadnoteProgramLifecycle.programs(data).length)).toBe(1);expect(await page.evaluate(()=>data.programCancellations[0].revisions.length)).toBe(2);
});
test('failed cancellation write and stale preview never commit in-memory training',async({page})=>{
 await seed(page,F.hypertrophy(8));await page.locator('[data-manage-program]').click();await page.locator('#cancel-reason').fill('Test');await page.locator('#cancel-confirm').check();const before=await page.evaluate(()=>JSON.stringify(data));await page.evaluate(()=>{persistNow=async()=>{throw Error('Storage full');};});await page.locator('#cancel-apply').click();await expect(page.locator('#cancel-error')).toContainText('Storage full');expect(await page.evaluate(()=>JSON.stringify(data))).toBe(before);await page.evaluate(()=>{const r=LoadnoteSchedule.list(data.scheduledSessions).at(-1);data.scheduledSessions=LoadnoteSchedule.change(data.scheduledSessions,r.id,{reason:'Changed after preview'},new Date().toISOString());});await page.locator('#cancel-apply').click();await expect(page.locator('#cancel-error')).toContainText('changed; reopen');expect(await page.evaluate(()=>data.programCancellations.length)).toBe(0);
});
test('shorter future session previews exact accessory omission and persists approved Calendar targets',async({page},info)=>{
 await page.clock.setSystemTime(new Date('2026-09-24T20:00:00Z'));await seed(page,phased());await page.locator('#coaching-proposals summary').click();await expect(page.locator('#coaching-proposals')).toContainText('optional shorter session');await page.locator('[data-coaching-proposal]').click();await expect(page.locator('#coaching-proposal-dialog .proposal-targets')).toBeVisible();await expect(page.locator('#coaching-proposal-dialog')).toContainText('Chest-supported Row');await screenshot(page,info,'shorter-session-review.png');const original=await page.evaluate(()=>JSON.stringify(data.phasePrograms));await page.locator('#coaching-response').selectOption('accepted');await page.locator('#coaching-proposal-confirm').check();await page.getByRole('button',{name:'Save reviewed response'}).click();await expect(page.locator('#coaching-proposal-dialog')).not.toBeVisible();await page.reload();expect(await page.evaluate(()=>JSON.stringify(data.phasePrograms))).toBe(original);expect(await page.evaluate(()=>LoadnoteSchedule.list(data.scheduledSessions)[0].prescription.plannedExercises.some(e=>e.exerciseId==='row'))).toBe(false);expect(await page.evaluate(()=>data.coachingReviews[0].proposal.kind)).toBe('session-trim');
});
test('full Coach uses the same intelligent answer and action buttons without online replacement',async({page})=>{
 let onlineRequests=0;await page.route('**/api/auth/session',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({authenticated:true,account:{id:'v3-test-account',displayName:'Athlete',providers:['test']},expiresAt:'2030-01-01T00:00:00.000Z',csrf:'test-csrf',transport:'cookie',authConfigured:true,authRequired:true,loginAvailable:true})}));await page.route('**/api/coach',r=>{onlineRequests++;return r.fulfill({status:500,body:'Unexpected remote replacement'});});await page.reload();await expect.poll(()=>page.evaluate(()=>LoadnoteAccountSession.snapshot().status)).toBe('authenticated');await seed(page,F.hypertrophy(8));await page.evaluate(()=>{showTab('coach');showSubTab('coach','co-chat');});await page.locator('#chat-input').fill('What evidence is missing?');await page.locator('#chat-send-btn').click();await expect(page.locator('#chat-messages')).toContainText('Shared coaching · daily intelligence');await expect(page.locator('#chat-messages .smart-coach-actions')).toBeVisible();await page.locator('#chat-messages .smart-coach-actions .btn-secondary').first().click();await expect(page.locator('#shared-coaching-review')).toBeVisible();expect(onlineRequests).toBe(0);
});
test('Companion action leaves the Olympic recorder while preserving its draft and cancellation guard',async({page})=>{
 await page.clock.setSystemTime(new Date('2026-10-05T20:00:00Z'));await seed(page,F.sport('weightlifting'));await page.evaluate(()=>LoadnoteSportPlannerUI.record(LoadnoteSchedule.list(data.scheduledSessions)[0].id));await expect(page.locator('#sp-record-dialog')).toBeVisible();await page.locator('[data-sp-value=load]').first().fill('40');await page.evaluate(()=>LoadnoteCoachCompanionUI.open());await page.locator('#cc-input').fill('Cancel my program');await page.locator('#cc-form button').click();await page.locator('#cc-messages .smart-coach-actions button').filter({hasText:'Manage programs'}).click();await expect(page.locator('#sp-record-dialog')).not.toBeVisible();await expect(page.locator('#program-cancellation-dialog')).toBeVisible();await expect(page.locator('#cancel-error')).toContainText('open workout draft');expect(await page.evaluate(()=>LoadnoteSportPlannerUI.hasDraft())).toBe(true);expect(await page.evaluate(()=>data.programCancellations.length)).toBe(0);
});
