const {test,expect}=require('playwright/test'),{fixture,logWeek}=require('../fixtures/weekly-coaching');
test.beforeEach(async({page})=>{await page.clock.install({time:new Date('2026-10-04T19:00:00Z')});await page.goto('/');await expect(page.locator('.ex-name')).toHaveCount(1);await seed(page,fixture());});
async function seed(page,state){await page.evaluate(async s=>{data=normalizeDataShape({...data,...s,meetCycles:s.meetCycles||[],phasePrograms:s.phasePrograms||[],phaseReviews:s.phaseReviews||[],workoutRevisions:s.workoutRevisions||[],hypertrophyPrograms:s.hypertrophyPrograms||[],sportPrograms:s.sportPrograms||[],unit:'kg'});await persistNow(data);showTab('coach');showSubTab('coach','co-programs');},state);}
async function open(page){await page.getByRole('button',{name:'Review my week',exact:true}).click();return page.getByRole('dialog',{name:'Weekly review',exact:true});}
test('Companion and Decisions share a canonical read-only weekly answer for signed-in users',async({page})=>{
 await page.evaluate(()=>{window.remoteCalls=0;LoadnoteCoachClient.ensureSignedIn=async()=>true;LoadnoteCoachClient.ask=async()=>{window.remoteCalls++;throw Error('Must stay local');};showTab('dashboard');});const before=await page.evaluate(()=>JSON.stringify(data));
 await page.locator('#coach-companion-launcher').click();await page.locator('#cc-input').fill('How did this week go, and what should I do next week?');await page.locator('#cc-form button').click();const answer=page.locator('#cc-messages .assistant').last();await expect(answer).toContainText('Squat: Review adjustment');await expect(answer).toContainText('Bench: Maintain');await answer.getByRole('button',{name:'See weekly review',exact:true}).click();const d=page.getByRole('dialog',{name:'Weekly review',exact:true});await expect(d).toContainText('2 sessions');await expect(d).toContainText('Next week');expect(await page.evaluate(()=>window.remoteCalls)).toBe(0);expect(await page.evaluate(()=>JSON.stringify(data))).toBe(before);
});
test('weekly summary and exact targets fit 320px in both themes with keyboard dismissal',async({page},info)=>{
 if(info.project.name==='mobile-chromium')await page.setViewportSize({width:320,height:844});const d=await open(page);await expect(d.locator('#weekly-completed-week')).toHaveValue('1');const before=await page.evaluate(()=>JSON.stringify(data));
 for(const theme of ['light','dark']){await page.evaluate(t=>document.body.classList.toggle('dark',t==='dark'),theme);await page.screenshot({path:info.outputPath('weekly-review-'+theme+'.png'),animations:'disabled'});expect(await d.evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);}
 await d.getByText('Proposed targets · 2 sessions',{exact:true}).click();await expect(d).toContainText('2026-10-05');await expect(d).toContainText('Before');await expect(d).toContainText('Proposed');await d.evaluate(d=>{const body=d.querySelector('.adaptive-dialog-body'),section=d.querySelector('[aria-labelledby=weekly-next-heading]');body.scrollTop+=section.getBoundingClientRect().top-body.getBoundingClientRect().top;});await expect(d.locator('#weekly-next-heading')).toBeInViewport();await page.screenshot({path:info.outputPath('weekly-exact-targets.png'),animations:'disabled'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(await page.evaluate(()=>JSON.stringify(data))).toBe(before);await page.keyboard.press('Escape');await expect(d).toBeHidden();await expect(page.getByRole('button',{name:'Review my week',exact:true})).toBeFocused();
});
test('review choices refresh exact dates and targets, reset approval and retain a failed durable save',async({page})=>{
 const d=await open(page);await d.getByRole('button',{name:'Review in Decisions',exact:true}).click();await page.locator('#cycle-review-analyze').click();const host=page.locator('#cycle-week-review');await expect(host.locator('#cycle-review-preview')).toContainText('no Calendar targets');const before=await page.evaluate(()=>JSON.stringify(data));
 await host.locator('#cycle-controller-use').click();await expect(host.locator('#cycle-review-preview')).toContainText('2 sets');await expect(host.locator('#cycle-review-preview')).toContainText('2026-10-05');expect(await page.evaluate(()=>JSON.stringify(data))).toBe(before);await host.locator('#cycle-review-confirm').check();await host.locator('[data-cycle-review-choice=squat]').selectOption('reduce-load');await expect(host.locator('#cycle-review-confirm')).not.toBeChecked();await expect(host.locator('#cycle-review-preview')).toContainText('Proposed');await host.locator('#cycle-review-notes').fill('Reviewed exact targets');await host.locator('#cycle-review-confirm').check();
 await page.evaluate(()=>{window.weeklyPersist=persistNow;persistNow=async()=>{throw Error('Weekly storage unavailable');};});await host.locator('#cycle-review-save').click();await expect(host.locator('#cycle-review-error')).toContainText('storage unavailable');await expect(host.locator('[data-cycle-review-choice=squat]')).toHaveValue('reduce-load');expect(await page.evaluate(()=>JSON.stringify(data))).toBe(before);await page.evaluate(()=>{persistNow=window.weeklyPersist;});await host.locator('#cycle-review-save').click();await expect.poll(()=>page.evaluate(()=>data.meetCycles[0].weeklyReviews.length)).toBe(1);expect(await page.evaluate(()=>data.meetCycles[0].weeklyReviews[0].changes.length)).toBe(2);await page.reload();await expect(page.locator('.ex-name')).toHaveCount(1);expect(await page.evaluate(()=>data.meetCycles[0].weeklyReviews[0].choices.squat)).toBe('reduce-load');
});
test('stale Calendar evidence cannot apply a previously previewed next-week change',async({page})=>{
 const d=await open(page);await d.getByRole('button',{name:'Review in Decisions',exact:true}).click();await page.locator('#cycle-review-analyze').click();await page.locator('#cycle-controller-use').click();await page.locator('#cycle-review-confirm').check();await page.evaluate(()=>{data.scheduledSessions=LoadnoteSchedule.change(data.scheduledSessions,'meet:weekly:w2d0',{reason:'Manual Calendar edit'},'2026-10-04T18:59:00.000Z');});const before=await page.evaluate(()=>JSON.stringify(data));await page.locator('#cycle-review-save').click();await expect(page.locator('#cycle-review-error')).toContainText('changed');expect(await page.evaluate(()=>JSON.stringify(data))).toBe(before);
});
test('primary-lift follow-ups show the matched approved revision and corrected missing effort',async({page},info)=>{
 await page.clock.setSystemTime(new Date('2026-10-11T20:00:00Z'));const state=logWeek(fixture({approved:true}),2);await seed(page,state);await page.evaluate(()=>LoadnoteWeeklyCoachingUI.openFollowups());let d=page.getByRole('dialog',{name:'Primary-lift follow-ups',exact:true});await expect(d).toContainText('Within effort cap');await d.locator('summary').first().click();await expect(d).toContainText('Previous target');await expect(d).toContainText('Approved target');await expect(d).toContainText('Recorded performance');await d.screenshot({path:info.outputPath('primary-lift-follow-up.png'),animations:'disabled'});await page.keyboard.press('Escape');
 await page.evaluate(()=>{const w=data.workouts.find(w=>w.sessionIntent.schedule.id==='meet:weekly:w2d0');w.exercises[0].sets[0].rpe=null;});const before=await page.evaluate(()=>JSON.stringify(data));await page.evaluate(()=>LoadnoteWeeklyCoachingUI.openFollowups());d=page.getByRole('dialog',{name:'Primary-lift follow-ups',exact:true});await expect(d).toContainText('Needs evidence');expect(await page.evaluate(()=>JSON.stringify(data))).toBe(before);
});
test('missing logs stay unknown and phase programs keep completed-phase review boundaries',async({page})=>{
 await seed(page,fixture({logged:false}));let d=await open(page);await expect(d).toContainText('Gather evidence');await expect(d).toContainText('Keep targets; gather evidence');await expect(d).toContainText('No weekly target changes');await page.keyboard.press('Escape');await seed(page,require('../fixtures/phase-review').fixture());d=await open(page);await expect(d).toContainText('completed-phase review');await expect(d.getByRole('button',{name:'Review in Decisions',exact:true})).toHaveCount(0);await expect(d).toContainText('No weekly target changes');
});

test('program and completed-week selections preserve keyboard focus and keep source evidence separate',async({page})=>{
 const state=fixture({approved:true}),other=structuredClone(state.meetCycles[0]);other.id='other';other.weeklyReviews=[];state.meetCycles.push(other);await seed(page,state);let d=await open(page);await expect(d).toContainText('More than one program');await d.locator('#weekly-program').selectOption({label:'Phased strength · meet-cycle · weekly'});await expect(d.locator('#weekly-completed-week')).toBeFocused();await expect(d).toContainText('Weekly review already approved');await page.keyboard.press('Escape');
 await page.clock.setSystemTime(new Date('2026-10-11T20:00:00Z'));await seed(page,fixture({approved:true}));d=await open(page);await expect(d.locator('#weekly-completed-week')).toHaveValue('2');await d.locator('#weekly-completed-week').selectOption('1');await expect(d.locator('#weekly-completed-week')).toBeFocused();await expect(d).toContainText('Weekly review already approved');await expect(d.locator('#weekly-completed-week option').first()).toHaveText('Week 1');
});
