const assert=require('node:assert/strict');
const A=require('../src/product/accessory-programming'),P=require('../src/product/phase-builder'),B=require('../src/product/program-builder'),M=require('../src/product/meet-cycle'),Q=require('../src/product/program-quality-gate'),I=require('../src/product/data-integrity'),Profile=require('../src/product/programming-profile');
const {phaseFixture}=require('./fixtures/phase-builder');
const {state,config}=phaseFixture(),args={asOf:'2026-09-24',now:'2026-09-24T12:00:00.000Z'};
const row={policy:A.POLICY,exerciseId:I.stableExerciseId('Chest-supported Row'),name:'Chest-supported Row',day:0,group:'upper-back',purpose:'hypertrophy',equipment:'dumbbells',equipmentConfirmed:true,mode:'reps',sets:2,weightKg:30,targetRpe:7,minReps:8,maxReps:12};
const hold={...row,exerciseId:I.stableExerciseId('Plank'),name:'Plank',day:2,group:'trunk',purpose:'trunk',equipment:'bodyweight',mode:'duration',weightKg:0,seconds:30};
const cardio={policy:A.POLICY,exerciseId:I.stableExerciseId('Cycling'),name:'Cycling',day:4,group:'conditioning',purpose:'conditioning',equipment:'cardio',equipmentConfirmed:true,mode:'cardio',minutes:10};
const cfg={...config,accessories:[row,hold,cardio]},before=JSON.stringify(state),base=P.prepare(state,config,args),p=P.prepare(state,cfg,args);
assert.equal(JSON.stringify(state),before);assert.deepEqual(p.weekly.map(w=>w.lifts),base.weekly.map(w=>w.lifts));
assert.deepEqual(p.weekly[0].accessoryWorkload,{strengthSets:4,conditioningMinutes:10,groups:{'upper-back':2,trunk:2}});
assert.equal(p.sessions[0].estimatedMinutes,base.sessions[0].estimatedMinutes+9);
assert.equal(p.sessions[0].exercises.at(-1).sets[0].weight,30);assert.equal(p.sessions[0].exercises.at(-1).sets[0].reps,8);
assert.equal(p.sessions.find(s=>s.phase==='deload').exercises.at(-1).sets.length,1);
assert.equal(p.sessions.find(s=>s.phase==='deload'&&s.exercises.some(e=>e.type==='cardio')).exercises.at(-1).duration,5);
assert(p.sessions[0].exercises.at(-1).progression.includes('never auto-apply'));
const saved=P.save(state,p,{confirmed:true}, {...args,id:'accessories'});
assert(saved.exerciseCatalog.some(e=>e.id===row.exerciseId));assert.deepEqual(P.validate(JSON.parse(JSON.stringify(saved.phasePrograms))),saved.phasePrograms);
const scheduled=P.schedule(saved,'accessories',{...args,now:'2026-09-24T13:00:00.000Z'});
assert.equal(scheduled.scheduledSessions[0].revisions[0].context.prescription.plannedExercises.at(-1).exerciseId,row.exerciseId);
assert.equal(scheduled.scheduledSessions[1].revisions[0].context.prescription.plannedExercises.at(-1).trackBy,'duration');
assert.equal(scheduled.scheduledSessions[2].revisions[0].context.prescription.plannedExercises.at(-1).duration,10);
const Intent=require('../src/product/session-intent');
const rangePlan=Intent.createPrescription(A.exercises([row],0,'strength'),{type:'manual'},args.now);
const rangeWorkout={sessionIntent:{prescription:rangePlan},exercises:[{...rangePlan.plannedExercises[0],sets:rangePlan.plannedExercises[0].sets.map(s=>({...s,reps:10,rpe:7}))}]};
assert.equal(Intent.compare(rangeWorkout).status,'as-planned');rangeWorkout.exercises[0].sets[0].reps=21;assert.equal(Intent.compare(rangeWorkout).status,'modified');
assert.deepEqual(Intent.prescription(JSON.parse(JSON.stringify(rangePlan))),rangePlan);
assert.throws(()=>Intent.createPrescription([{name:'Bad',sets:[{weight:10,reps:8,minReps:12,maxReps:8}]}],{type:'manual'},args.now),/rep range/);
assert.deepEqual(saved.workouts,state.workouts);assert.deepEqual(saved.reviewedPrograms,state.reviewedPrograms);
const cycle=M.build(saved.phasePrograms[0],{version:1,weeks:12,peakWeeks:2,taperWeeks:1,meetDate:'2026-12-19'});
assert(cycle.sessions.filter(s=>s.phase==='accumulation').some(s=>s.exercises.some(e=>e.role==='accessory')));
assert(cycle.sessions.filter(s=>['peaking','taper'].includes(s.phase)).every(s=>s.exercises.every(e=>e.role!=='accessory')));
assert.equal(Q.inspect(cycle).counts.blocking,0);
const drift=structuredClone(cycle);drift.sessions[0].exercises.at(-1).sets[0].weight=999;assert(Q.inspect(drift).findings.some(i=>i.code==='accessory-drift'));
const meetProposal=M.prepare(saved,saved.phasePrograms[0],{version:1,weeks:12,peakWeeks:2,taperWeeks:1,meetDate:'2026-12-19'},args);
const meetSaved=M.save(saved,meetProposal,{confirmed:true},{...args,id:'accessory-cycle'}),meetScheduled=M.schedule(meetSaved,'accessory-cycle',args);
assert(meetScheduled.scheduledSessions[0].revisions[0].context.prescription.plannedExercises.some(e=>e.exerciseId===row.exerciseId));
assert.deepEqual(M.validate(JSON.parse(JSON.stringify(meetSaved.meetCycles))),meetSaved.meetCycles);
const quick={...state.reviewedPrograms[0].config,startDate:config.startDate,sessionMinutes:90,accessories:[row,cardio]};
const qp=B.prepare(state,quick,args),qs=B.save(state,qp,{confirmed:true}, {...args,id:'quick-accessories'});
assert.equal(qp.sessions[0].exercises.at(-1).exerciseId,row.exerciseId);assert.deepEqual(B.validate(qs.reviewedPrograms),qs.reviewedPrograms);
for(const change of [{day:1},{sets:4},{weightKg:0},{targetRpe:10},{maxReps:99},{equipmentConfirmed:false},{exerciseId:config.lifts.squat.exerciseId,name:config.lifts.squat.name},{exerciseId:'wrong-id'}])assert.throws(()=>P.prepare(state,{...config,accessories:[{...row,...change}]},args));
assert.throws(()=>P.build({...config,sessionMinutes:60,accessories:[row]}),/needs about/);
assert.throws(()=>P.build({...config,accessories:[row,row]}),/duplicate/);
const avoided={...state,programmingProfiles:Profile.save([],{...Profile.current(state.programmingProfiles).context,avoidedExerciseIds:[row.exerciseId]}, {id:'avoided',now:'2026-09-23T12:00:00.000Z'})};
assert.throws(()=>P.prepare(avoided,cfg,args),/avoided/);
const stale={...state,exerciseCatalog:[...state.exerciseCatalog,{id:row.exerciseId,name:'Renamed Row'}]};assert.throws(()=>P.save(stale,p,{confirmed:true},args),/identity changed/);
const bad=structuredClone(saved.phasePrograms);bad[0].sessions[0].exercises.at(-1).sets[0].reps=99;assert.throws(()=>P.validate(bad),/differ/);
assert.deepEqual(P.build({...config,accessories:[]}).sessions,P.build(config).sessions);assert(!Object.hasOwn(P.config(config),'accessories'));
const R=require('../src/product/phase-review');let effort={...scheduled,workouts:[]};
for(const s of effort.scheduledSessions.slice(0,9)){const v=s.revisions[0],c=v.context;effort.workouts.push({id:'observed-'+s.id,date:c.date,createdAt:c.date+'T20:00:00.000Z',sessionIntent:{prescription:c.prescription,schedule:{id:s.id,revisionAt:v.recordedAt}},exercises:c.prescription.plannedExercises.map(e=>e.type==='cardio'?{...e}:{...e,sets:e.sets.map(x=>({...x,rpe:x.targetRpe+(['s','ss'].includes(e.exerciseId)?1:0),...(e.exerciseId===row.exerciseId?{reps:10}:{})}))})});}
const reviewArgs={programId:'accessories',phase:'accumulation',asOf:'2026-10-18',now:'2026-10-18T22:00:00.000Z',recovery:{sleep:'usual',fatigue:'usual',soreness:'usual',discomfort:'none'}};
const report=R.analyze(effort,reviewArgs),adjusted=R.apply(effort,report,{squat:'reduce-load',bench:'keep',deadlift:'keep'},{...reviewArgs,confirmed:true});
assert(!Object.hasOwn(adjusted.phaseReviews[0].exerciseLifts,row.exerciseId));assert.deepEqual(R.validate(adjusted.phaseReviews),adjusted.phaseReviews);
for(const change of adjusted.phaseReviews[0].changes){const prior=change.before.context.prescription.plannedExercises.filter(e=>[row.exerciseId,hold.exerciseId,cardio.exerciseId].includes(e.exerciseId)),after=change.after.context.prescription.plannedExercises.filter(e=>[row.exerciseId,hold.exerciseId,cardio.exerciseId].includes(e.exerciseId));assert.deepEqual(after,prior);}
console.log('Accessory identity, workload/time, reps/holds/cardio, review/scheduling, deload, meet exclusion, drift and legacy compatibility passed');
