const assert=require('node:assert/strict'),F=require('../src/product/accessory-follow-up'),C=require('../src/product/coach-conversation'),S=require('../src/product/schedule'),{fixture,args,reviewArgs,row}=require('./fixtures/accessory-follow-up');
const state=fixture(),original=JSON.stringify(state),report=F.inspect(state,args),r=report.rows[0];
assert.equal(r.status,'within');assert.equal(r.before.sets[0].weight,30);assert.equal(r.approved.sets[0].weight,31);assert.equal(r.actual.sets[0].reps,10);assert.equal(r.effortSets,2);assert.equal(JSON.stringify(state),original);
function changed(change,{logged=true}={}){const s=fixture({logged});change(s);return F.inspect(s,args).rows[0];}
const actual=s=>s.workouts.at(-1).exercises.at(-1);
assert.equal(changed(s=>actual(s).sets.forEach(x=>x.reps=12)).status,'top');assert.equal(changed(s=>actual(s).sets[0].rpe=8).status,'above');assert.equal(changed(s=>actual(s).sets[0].reps=7).status,'below');assert.equal(changed(s=>actual(s).sets[0].reps=13).status,'outside');
for(const edit of [s=>actual(s).sets[0].rpe=null,s=>actual(s).sets[0]=null,s=>s.workouts.at(-1).createdAt='2026-10-11T20:00:00.000Z',s=>actual(s).sets[0].rpe='7',s=>actual(s).sets[0].weight=30,s=>actual(s).sets.pop(),s=>actual(s).name='Changed name',s=>actual(s).loadConvention='total',s=>s.workouts.at(-1).sessionIntent.schedule.revisionAt='2026-09-24T12:00:00.000Z',s=>s.workouts.at(-1).sessionIntent.deviationReason='time',s=>s.workouts.at(-1).date='2026-10-11',s=>s.workouts.at(-1).sessionIntent.prescription.plannedExercises.at(-1).sets[0].weight=32,s=>s.workouts.at(-1).createdAt=null,s=>s.workouts.push(structuredClone(s.workouts.at(-1))),s=>s.phasePrograms=[]])assert.equal(changed(edit).status,'unknown');
assert.equal(F.inspect(fixture({logged:false}),args).rows[0].status,'missing');assert.equal(F.inspect(fixture({logged:false}),reviewArgs).rows[0].status,'waiting');
for(const status of ['skipped','cancelled'])assert.equal(changed(s=>s.scheduledSessions=S.change(s.scheduledSessions,reviewArgs.sessionId,{status,reason:'Explicit '+status},'2026-10-11T12:00:00.000Z'),{logged:false}).status,status);
const moved=s=>s.scheduledSessions=S.change(s.scheduledSessions,reviewArgs.sessionId,{date:'2026-10-13',reason:'Moved'},'2026-10-11T12:00:00.000Z');assert.equal(changed(moved,{logged:false}).status,'superseded');assert.equal(changed(moved).status,'within');assert.equal(changed(moved).laterRevision,true); // A later revision does not erase a log's exact captured target.
let s=fixture();s.workouts.at(-1).exercises.at(-1).sets[0].rpe=null;assert.equal(F.inspect(s,args).rows[0].status,'unknown');s.workouts.at(-1).exercises.at(-1).sets[0].rpe=7;assert.equal(F.inspect(s,args).rows[0].status,'within'); // Corrections refresh, never freeze or infer missing effort.
assert.equal(F.inspect(state,{...args,now:'2026-10-12T18:00:00.000Z'}).rows[0].status,'missing');
let future=fixture({logged:false});future.scheduledSessions.find(s=>s.id===reviewArgs.sessionId).revisions.at(-1).recordedAt='2026-10-13T12:00:00.000Z';assert.equal(F.inspect(future,args).rows.length,0);
let malformed=fixture();malformed.scheduledSessions.find(s=>s.id===reviewArgs.sessionId).revisions.at(-1).context.prescription.plannedExercises[0].sets[0].weight+=1;assert.equal(F.inspect(malformed,args).rows[0].status,'unknown');
const reply=C.answer(state,'How did my accessory change work?',{...args,unit:'lb'});assert.equal(reply.source,'Shared coaching · accessory follow-up');assert.match(reply.text,/68.34 lb/);assert.match(reply.text,/not what caused/);assert.equal(reply.actions[0].kind,'accessory-follow-up');assert.equal(JSON.stringify(state),original);
assert.equal(F.answer(state,'Should I increase my bench?',args),null);assert.equal(F.answer(state,'My accessory hurts; did the change work?',args),null);assert.match(F.answer({},'Show accessory follow-ups',args).text,/No approved/);
console.log('Read-only accessory follow-ups: exact revisions, reps/effort, corrections, timing, changed plans, missing/duplicate logs, source and Companion boundaries passed');
