const assert=require('node:assert/strict'),A=require('../src/product/adaptive-session'),I=require('../src/product/session-intent');
const source={exerciseId:'row',name:'Cable row',purpose:'hypertrophy',group:'upper-back',equipment:['cable'],loadConvention:'stack',confirmed:true};
const target={...source,exerciseId:'db-row',name:'Dumbbell row',equipment:['dumbbells'],loadConvention:'per-hand'};
const profile={equipment:['dumbbells'],equipmentConfirmed:true};
const dose={restSeconds:120,sets:[{weight:15,reps:10,targetRpe:7},{weight:15,reps:10,targetRpe:7}]};
const plan=I.createPrescription([{name:'Squat',exerciseId:'squat',restSeconds:180,sets:[{reps:5,weight:100,targetRpe:7},{reps:5,weight:100,targetRpe:7}]},{name:source.name,exerciseId:'row',restSeconds:120,sets:[{reps:10,weight:40,targetRpe:7},{reps:10,weight:40,targetRpe:7}]}],{type:'program'},'2026-10-05T10:00:00.000Z');
const original=JSON.stringify(plan);
assert.equal(A.alternatives(source,[target]).choices.length,0);
assert.equal(A.alternatives(source,[target],profile).choices.length,1);
assert.equal(A.alternatives(source,[target],{...profile,excludedExerciseIds:['db-row']}).choices.length,0);
assert.equal(A.alternatives(source,[{...target,purpose:'strength'}],profile).choices.length,0);
assert.throws(()=>A.preferences({minutes:9}));
assert.throws(()=>A.preferences({equipment:['unknown']}));
const trim=A.timePreview(plan,{minutes:10,optionalExerciseIds:['row']});
assert.deepEqual(trim.omittedExerciseIds,['row']);assert.deepEqual(trim.after.plannedExercises,[plan.plannedExercises[0]]);assert.equal(trim.fitsEstimate,true);
assert.equal(A.timePreview(plan,{minutes:10}).fitsEstimate,false);
assert.equal(A.timePreview({...plan,plannedExercises:plan.plannedExercises.map(e=>{const x={...e};delete x.restSeconds;return x;})},{minutes:10}).supported,false);
const replacement=A.replacementPreview(plan,{source,target,startingDose:dose,profile});
assert.equal(replacement.after.plannedExercises[1].sets[0].weight,15);assert.equal(replacement.after.plannedExercises[1].loadConvention,'per-hand');
assert.deepEqual(replacement.after.plannedExercises[0],plan.plannedExercises[0]);
assert.throws(()=>A.replacementPreview(plan,{source,target,startingDose:{...dose,restSeconds:null},profile}));
assert.throws(()=>A.replacementPreview(plan,{source,target,startingDose:{...dose,sets:[{weight:-1,reps:10,targetRpe:7}]},profile}));
assert.throws(()=>A.replacementPreview(plan,{source,target,startingDose:{...dose,sets:[{weight:15,reps:10,targetRpe:7},{weight:15,reps:1.5,targetRpe:7}]},profile}));
assert.throws(()=>A.approve(plan,trim,{confirmed:false}));
const now='2026-10-05T11:00:00.000Z';assert.equal(A.approve(plan,trim,{confirmed:true,now}).capturedAt,now);
assert.equal(A.approve(plan,replacement,{confirmed:true,now}).plannedExercises[1].exerciseId,'db-row');
assert.throws(()=>A.approve(plan,{...trim,after:plan},{confirmed:true,now}));
assert.throws(()=>A.approve({...plan,capturedAt:now},trim,{confirmed:true,now}));
assert.throws(()=>A.approve(plan,replacement,{confirmed:true,now:plan.capturedAt}));
assert.equal(JSON.stringify(plan),original);
const technical=I.createPrescription([{name:'Snatch',exerciseId:'snatch',type:'practice',kind:'weightlifting',rounds:3,reps:1,restSeconds:180,protocol:'Reviewed singles',weight:40,family:'snatch',variation:'Full'}],{type:'program'},plan.capturedAt);
assert.equal(A.timePreview(technical,{minutes:10}).supported,false);
assert.throws(()=>A.replacementPreview(technical,{source,target,startingDose:dose,profile}));
console.log('Adaptive session previews, explicit preferences, fresh starting doses and approval guards passed');

const S=require('../src/product/schedule'),Sync=require('../src/product/sync-model'),G=require('../src/product/movement-guidance');
assert.deepEqual(A.deviceProfile(null).movements,[]);assert.throws(()=>A.deviceProfile({version:2,movements:[]}));assert.throws(()=>A.deviceProfile({version:1,movements:[source,source]}));
assert.equal(A.estimate(plan.plannedExercises,{defaultRestSeconds:180}).known,true);
const missingRest={...plan,plannedExercises:plan.plannedExercises.map(e=>{const x={...e};delete x.restSeconds;return x;})};
const assumed=A.timePreview(missingRest,{minutes:10,optionalExerciseIds:['row'],assumptions:{defaultRestSeconds:180}});assert.equal(assumed.supported,true);assert.equal(assumed.after.plannedExercises[0].restSeconds,undefined);
const id='phase:p:w1:d0',scheduled=S.create([],{date:'2026-10-06',name:'Reviewed session',prescription:plan},{id,now:plan.capturedAt});
const state={workouts:[],exerciseCatalog:[{id:source.exerciseId,name:source.name},{id:target.exerciseId,name:target.name}],scheduledSessions:scheduled,phasePrograms:[{id:'p',config:{accessories:[{exerciseId:'row'}]}}]};
const before=JSON.stringify(state),args={confirmed:true,asOf:'2026-10-05',expectedRevisionAt:plan.capturedAt,now};
const updated=A.applySchedule(state,id,trim,args);assert.equal(updated.scheduledSessions[0].revisions.length,2);assert.equal(JSON.stringify(state),before);
assert.deepEqual(updated.phasePrograms,state.phasePrograms);assert.equal(S.list(updated.scheduledSessions)[0].prescription.plannedExercises.length,1);
assert.throws(()=>A.applySchedule(state,id,trim,{...args,draftOpen:true}));assert.throws(()=>A.applySchedule(state,id,trim,{...args,asOf:'2026-10-07'}));assert.throws(()=>A.applySchedule(updated,id,trim,args));
assert.throws(()=>A.applySchedule(state,id,A.timePreview(plan,{minutes:60}),args));
assert.throws(()=>A.applySchedule({...state,workouts:[{sessionIntent:{schedule:{id}}}]},id,trim,args));
const primaryTrim=A.timePreview(plan,{minutes:10,optionalExerciseIds:['squat']});assert.throws(()=>A.applySchedule(state,id,primaryTrim,args));
const replaced=A.applySchedule(state,id,replacement,args);assert.equal(S.list(replaced.scheduledSessions)[0].prescription.plannedExercises[1].exerciseId,'db-row');
assert.throws(()=>A.applySchedule({...state,exerciseCatalog:[{id:source.exerciseId,name:source.name}]},id,replacement,args));
const SyncState={...updated,phasePrograms:[],exerciseCatalog:[]};const bundle=Sync.createPackage(SyncState,{clientId:'device-test',createdAt:now});assert.equal(bundle.data.collections.scheduledSessions[0].revisions.length,2);
assert.equal(G.find('Hammer Curl').cues.length,2);assert.equal(G.find('Hammer Curl variation'),null);assert(G.find('Goblet Squat').source.startsWith('https://www.acefitness.org/'));
console.log('Calendar adaptation protects primary work, history, drafts and sync; guidance uses exact identities');
