const assert=require('node:assert/strict');
const Core=require('../src/core/loadnote-core'),Blocks=require('../src/product/training-blocks'),Review=require('../src/product/training-review'),Ready=require('../src/product/decision-readiness');
assert.equal(Core.estimated1RM(200,1,7),200,'legacy estimator and PR contract unchanged');
assert.equal(Core.capacityEvidence(200,1,7).reason,'submax-single');
assert.equal(Core.capacityEvidence(200,1,9.5).estimate,null);
assert.equal(Core.capacityEvidence(200,1,10).estimate,200);
assert.equal(Core.capacityEvidence(100,5,5).reason,'low-rpe');
assert.equal(Core.capacityEvidence(100,5,null).reason,'missing-rpe');
assert.equal(Core.capacityEvidence(100,5,11).reason,'invalid-rpe');
assert.equal(Core.capacityEvidence(100,13,8).reason,'high-reps');
assert.equal(Core.capacityEvidence(Infinity,5,8).reason,'invalid-set');
assert.equal(Core.capacityEvidence(100,5,8).estimate,Core.estimated1RM(100,5,8));
const stamp='2026-01-01T00:00:00.000Z';
let blocks=Blocks.upsert([],{name:'Base',startDate:'2026-01-01',endDate:'2026-01-31',loadStrategy:'conservative'},{now:stamp});
blocks=Blocks.upsert(blocks,{name:'Strength',startDate:'2026-02-01',endDate:'2026-02-28'},{now:stamp});
const first=Blocks.list(blocks)[0],second=Blocks.list(blocks)[1];
const workouts=['2026-01-05','2026-01-12','2026-01-19','2026-02-05'].map((date,i)=>({id:'w'+i,date,createdAt:date+'T10:00:00.000Z',exercises:[{exerciseId:'s',name:'Squat',sets:[{weight:200+i,reps:1,rpe:7},{weight:100+i,reps:5,rpe:5},{weight:110+i,reps:5,rpe:8}]}]}));
const state={workouts,trainingBlocks:blocks};const before=JSON.stringify(state);
const mixed=Review.review(state,{asOf:'2026-02-10'});assert.equal(mixed.exercises[0].estimatedCapacityTrend,null);
const r=Review.review(state,{asOf:'2026-02-10',blockId:first.id});
assert.equal(r.from,'2026-01-01');assert.equal(r.through,'2026-01-31');assert.equal(r.workoutCount,3);
assert.equal(r.exercises[0].capacityDays,3);assert.equal(r.exercises[0].exclusions['submax-single'],3);assert.equal(r.exercises[0].exclusions['low-rpe'],3);
assert.equal(r.exercises[0].estimatedCapacityTrend.start,Core.estimated1RM(110,5,8));
assert.equal(r.exercises[0].loggedLoadTrend.start,200);
assert.match(r.exercises[0].reasons.join(' '),/Low-effort/);
assert.equal(Review.review(state,{asOf:'2026-01-13',blockId:first.id}).workoutCount,2);
assert.throws(()=>Review.review(state,{asOf:'2026-01-13',blockId:second.id}));
assert.throws(()=>Review.review(state,{asOf:'2026-02-10',blockId:'deleted'}));
const late=Blocks.upsert([],{name:'Late',startDate:'2026-01-01',endDate:'2026-01-31'},{now:'2026-03-01T00:00:00.000Z'});
assert.throws(()=>Review.review({...state,trainingBlocks:late},{asOf:'2026-02-10',blockId:late[0].id,retrospective:false}));
assert.equal(Review.review({...state,unit:'lb'},{asOf:'2026-02-10',blockId:first.id}).exercises[0].estimatedCapacityTrend.start,r.exercises[0].estimatedCapacityTrend.start);
assert.equal(JSON.stringify(state),before);
const singles=workouts.map(w=>({...w,exercises:[{...w.exercises[0],sets:[w.exercises[0].sets[0]]}]}));
const roles=Ready.upsert([],{exerciseId:'s',role:'competition',competitionLift:'squat'},{now:stamp});
const ready=Ready.snapshot({workouts:singles,exerciseRoles:roles,trainingBlocks:blocks},{asOf:'2026-01-31',retrospective:true}).lifts.squat;
assert.equal(ready.evidence.estimatedCapacity,null);assert.equal(ready.metrics.capacityDays,0);assert.equal(ready.metrics.hardSets,3,'hard singles remain counted as logged hard work');
assert.equal(ready.metrics.rpeCoverage,1,'present RPE is not missing');assert.match(ready.reasons.join(' '),/capacity-evidence days/);
assert.equal(Blocks.analyze(blocks,singles,first.id,{asOf:'2026-01-31',retrospective:true}).exercises[0].estimatedCapacityTrend,null);
console.log('Capacity evidence exclusions, single handling and block-specific review passed');
