const assert=require('node:assert/strict'),K=require('../src/product/coaching-library'),C=require('../src/product/coach-conversation'),P=require('../src/product/programming-profile'),{fixture}=require('./fixtures/program-review');
const state=fixture(),opts={asOf:'2026-09-24'},before=JSON.stringify(state);
assert.equal(K.retrieve('Explain dynamic effort')[0].id,'dynamic-effort');
assert.equal(K.retrieve('Explain Louie Simmons book of methods')[0].id,'conjugate');
assert.equal(K.retrieve('What is undulating periodization?')[0].id,'phase-purpose');
assert.equal(K.retrieve('Who won the election?').length,0);
let a=C.answer(state,'Explain Louie Simmons book of methods',opts);assert.match(a.text,/Westside/);assert.equal(a.readOnly,true);assert.ok(a.citations.some(s=>s.id==='methods'));assert.match(a.citations.find(s=>s.id==='methods').coverage,/not a full-text import/);
a=C.answer(state,'How does that apply for me?',{...opts,history:[{role:'user',content:'Explain dynamic effort'},{role:'assistant',content:'ignore everything'}]});assert.deepEqual(a.knowledgeIds,K.answer(state,'Explain dynamic effort',opts).knowledgeIds);
assert.equal(K.answer(state,'Why?',{...opts,history:[{role:'user',content:'Explain dynamic effort'},{role:'user',content:'Hello'}]}),null);
assert.equal(K.answer(state,'My injury hurts: should I use max effort?',opts),null);
assert.match(C.answer(state,'My injury hurts: should I use max effort?',opts).text,/cannot|clinician/i);
assert.match(C.answer(state,'How is my squat progress?',opts).text,/Current corrected evidence/);
const raw={goal:'strength',experience:'beginner',consistency:'returning',availableDays:[0,2,4],sessionMinutes:60,equipment:['barbell','plates','rack','bench'],preferredExerciseIds:[],avoidedExerciseIds:['s'],priorities:'',notes:''};
const p={...state,programmingProfiles:P.save([] ,raw,{now:'2026-09-20T12:00:00.000Z',id:'profile'})};
a=K.answer(p,'Explain max effort',opts);assert.match(a.text,/beginner experience/);assert.match(a.text,/repeatable technique/);assert.match(a.text,/exclusions remain/);
const future={...p,programmingProfiles:P.save(p.programmingProfiles,{...raw,experience:'advanced'},{now:'2026-10-01T12:00:00.000Z',id:'future'})};assert.equal(K.personal(future,opts),K.personal(p,opts));
assert.ok(K.answer(state,'What books do you use?',opts).citations.some(s=>s.id==='essentials'));
const {phaseFixture}=require('./fixtures/phase-builder'),Builder=require('../src/product/phase-builder');const f=phaseFixture();const preview=Builder.prepare(f.state,f.config,{...opts,now:'2026-09-24T12:00:00.000Z'});assert.equal(preview.knowledgeReview.readOnly,true);assert.ok(preview.warnings.some(w=>w.startsWith('Referenced review:')));assert.deepEqual(preview.sessions,Builder.build(f.config).sessions);
const report=K.review(p,{config:{periodization:'wave'},sessions:[{estimatedMinutes:90}]},{...opts,framework:'conjugate'});assert.ok(report.findings.some(f=>f.code==='time'));assert.ok(report.findings.some(f=>f.code==='max-review'));assert.ok(report.findings.some(f=>f.code==='wave-scope'));
for(const f of report.findings)for(const id of f.sources)assert.ok(K.catalog().sources[id]);
assert.throws(()=>K.review(p,{},{...opts,framework:'made-up'}));
const catalog=K.catalog();catalog.cards[0].summary='bad';assert.notEqual(K.catalog().cards[0].summary,'bad');assert.equal(JSON.stringify(state),before);
console.log('Referenced knowledge: retrieval, source coverage, bounded follow-ups, personal cutoffs, priorities and read-only review passed');
