const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
let current={surface:'home',liveWorkout:null,restTimer:{active:false}};
let replacementCount=0;
const host={innerHTML:''},status={},launcher={dataset:{}},quick={dataset:{},buttons:[]};
Object.defineProperty(quick,'innerHTML',{set(html){
 replacementCount++;
 this.buttons=[...html.matchAll(/data-cc-q="([^"]+)"/g)].map(match=>({dataset:{ccQ:match[1]},listeners:[],addEventListener(type,fn){this.listeners.push({type,fn});}}));
}});
quick.querySelectorAll=()=>quick.buttons;
const elements={'coach-companion-launcher':launcher,'cc-context':host,'cc-status':status,'cc-quick':quick};
const document={readyState:'loading',addEventListener(){},getElementById:id=>elements[id]||null,querySelectorAll:()=>[]};
const window={LoadnoteCoachCompanion:{buildContext:()=>current,currentSetSummary:()=>null}};
vm.runInNewContext(fs.readFileSync(require.resolve('../src/product/coach-companion-ui'),'utf8'),{window,document});
const refresh=window.LoadnoteCoachCompanionUI.refresh;
refresh();
const first=quick.buttons[0];
for(let i=0;i<5;i++)refresh();
assert.equal(replacementCount,1,'Unchanged polling must not replace controls');
assert.equal(quick.buttons[0],first);
assert.equal(first.listeners.length,1,'Polling must not duplicate question handlers');
current={...current,restTimer:{active:true,remainingSeconds:90}};
refresh();
assert.equal(replacementCount,2);
assert.equal(quick.buttons[0].dataset.ccQ,'How much rest is left?');
const restButton=quick.buttons[0];
current.restTimer.remainingSeconds=89;refresh();
assert.equal(quick.buttons[0],restButton,'Countdown updates must preserve question controls');
assert(host.innerHTML.includes('89s'));
current={surface:'train',liveWorkout:{active:true},restTimer:{active:false}};
refresh();
assert.equal(replacementCount,3);
assert(quick.buttons.some(b=>b.dataset.ccQ==='Why this set?'));
current={surface:'progress',liveWorkout:null,restTimer:{active:false}};
refresh();
assert.equal(quick.buttons[0].dataset.ccQ,'How is my training going?');
console.log('Companion UI polling preserves controls/handlers while questions and rest context update');
