const assert=require('node:assert/strict'),C=require('../src/product/coach-conversation'),{fixture}=require('./fixtures/program-review');
const state=fixture(),original=JSON.stringify(state),options={asOf:'2026-09-24',unit:'lb'};
let a=C.answer(state,'How is my squat progress?',options);
assert.match(a.text,/Competition Squat/);assert.match(a.text,/Current corrected evidence as of 2026-09-24/);assert.match(a.text,/lb/);assert.match(a.text,/not a tested max/);assert.equal(a.readOnly,true);
const h=[{role:'user',content:'How is my squat progress?'},{role:'assistant',content:a.text}];
a=C.answer(state,'What about bench?',{...options,history:h});assert.equal(a.intent.lift,'bench');assert.match(a.text,/Competition Bench/);
h.push({role:'user',content:'What about bench?'},{role:'assistant',content:a.text});assert.equal(C.resolve('Why?',h).lift,'bench');assert.equal(C.resolve('Why?',h).topic,'evidence');
h.push({role:'user',content:'Hello'});assert.equal(C.resolve('Why?',h).topic,null);
assert.equal(C.resolve('How should accessories progress?',h).lift,null);
assert.match(C.answer(state,'What is my deadlift training max?',options).text,/Training max: not recorded/);
assert.match(C.answer({...state,exerciseRoles:[]},'Is my squat ready?',options).text,/not mapped/);
const future=JSON.parse(JSON.stringify(state));future.workouts.push({id:'future',date:'2026-10-01',createdAt:'2026-10-01T20:00:00.000Z',exercises:[{name:'Competition Squat',exerciseId:'s',sets:[{weight:999,reps:3,rpe:9}]}]});
assert.equal(C.answer(future,'How is my squat progress?',options).text,C.answer(state,'How is my squat progress?',options).text);
assert.match(C.answer(state,'Should I add weight?',options).text,/Which lift/);
assert.match(C.answer(state,'What accessories should I use?',options).text,/not diagnosed weaknesses/);
assert.match(C.answer(state,'What does RPE mean?',options).text,/Missing RPE is unknown/);
assert.match(C.answer(state,'My Achilles hurts with pain',options).text,/cannot diagnose/);
assert.equal(C.answer(state,'Who won the election?',options),null);
assert.equal(JSON.stringify(state),original);
const historyReply=C.answer(state,'How did my bench training change across my last three workouts?',options);
assert.equal(historyReply.source,'Recorded workout history');assert.match(historyReply.text,/Last 3 recorded workouts/);assert.match(historyReply.text,/2026-09-07/);assert.match(historyReply.text,/lb/);assert.match(historyReply.text,/no next-session load change/);assert.equal(historyReply.readOnly,true);
assert.equal(C.answer(future,'How did my bench training change across my last three workouts?',options).text,historyReply.text);
assert.match(C.answer({...state,exerciseRoles:[]},'How did my bench training change across my last three workouts?',options).text,/Confirm one competition/);
const effortHistory=[{role:'user',content:'I got fewer bench reps at the same weight today and RPE was higher. What should I consider?'}];
for(const q of ['My recent bench lift evidence','My recent lift evidence']){const reply=C.answer(state,q,{...options,history:effortHistory});assert.equal(reply.intent.lift,'bench');assert.equal(reply.source,'Current corrected lift evidence');assert.match(reply.text,/Competition Bench/);}
assert.match(C.answer(state,'My recent lift evidence',{...options,history:[...effortHistory,{role:'user',content:'Hello'}]}).text,/Which lift/);
assert.equal(C.answer(state,'My arm feels numb after bench. Should I add weight next time?',options).intent.topic,'health');
assert.equal(JSON.stringify(state),original);
console.log('Local Coach conversation: mapping, bounded follow-ups, limits, units, future exclusion and immutability passed');
