const assert=require('node:assert/strict'),F=require('./fixtures/coaching'),H=require('../src/product/hypertrophy-builder'),R=require('../src/product/coaching-review'),S=require('../src/product/schedule'),W=require('../src/product/muscle-workload-review'),C=require('../src/product/coaching-context'),Core=require('../src/core/loadnote-core'),Sync=require('../src/product/sync-model');
const copy=x=>structuredClone(x),initial=F.hypertrophy(),config={...initial.hypertrophyPrograms[0].config,weeks:8,deloadWeeks:[8]};
let state={...initial,hypertrophyPrograms:[],scheduledSessions:[],workouts:[],workloadProfiles:[],coachingReviews:[]};
state=H.save(state,H.prepare(state,config,{asOf:'2026-10-04',goalId:state.athleteGoals[0].id}),{confirmed:true,workloadConfirmed:true},{asOf:'2026-10-04',now:'2026-10-04T12:00:00.000Z',id:'repeat'});
state=H.schedule(state,'repeat',{asOf:'2026-10-04',now:'2026-10-04T13:00:00.000Z'});
const frozen=copy(state.hypertrophyPrograms);
function log(index,weight){const row=S.list(state.scheduledSessions)[index];state.workouts.push({id:'w'+index,date:row.date,createdAt:row.date+'T18:00:00.000Z',sessionIntent:{schedule:{id:row.id,revisionAt:row.revisionAt},prescription:copy(row.prescription),deviationReason:'none'},exercises:[{exerciseId:'press',name:'Leg press',type:'strength',sets:Array.from({length:3},()=>({weight,reps:12,rpe:8}))}]});}
function coverage(asOf){state=W.save(state,{coverage:'complete',from:'2026-10-01',through:asOf,tolerance:'tolerated',targets:{}},{now:asOf+'T19:00:00.000Z',expected:W.current(state.workloadProfiles)});}
log(0,60);log(1,60);coverage('2026-10-12');
const first=R.proposals(state,{asOf:'2026-10-12'}).proposals[0];assert.equal(first.fromKg,60);assert.equal(first.toKg,65);assert.equal(first.changes.length,5);
state=R.respond(state,first,{asOf:'2026-10-12',now:'2026-10-12T20:00:00.000Z',response:'accepted',confirmed:true});
assert.equal(H.progression(state,'repeat',{asOf:'2026-10-12'}).findings[0].currentKg,65);assert.equal(R.proposals(state,{asOf:'2026-10-12'}).proposals.length,0,'Earlier-dose successes cannot be reused');
log(2,65);coverage('2026-10-19');assert.equal(R.proposals(state,{asOf:'2026-10-19'}).proposals.length,0,'One new session is insufficient');
log(3,65);coverage('2026-10-26');const second=R.proposals(state,{asOf:'2026-10-26'}).proposals[0];assert.equal(second.fromKg,65);assert.equal(second.toKg,70);assert.notEqual(second.key,first.key);assert.equal(second.changes.length,3);
assert.match(C.answer(state,'What is my current approved load?',{asOf:'2026-10-26'}).text,/current approved load 65 kg/);
const beforeSecond=copy(state),past=copy(state.workouts);
for(const mutate of [s=>s.workouts[3].exercises[0].sets[0].rpe=null,s=>s.workouts[3].exercises[0].sets[0].rpe=9,s=>s.workouts[3].exercises[0].sets[0].weight=60,s=>s.workouts[3].sessionIntent.schedule.revisionAt='2026-10-04T13:00:00.000Z',s=>s.workouts[3].sessionIntent.prescription.capturedAt='2026-10-26T17:00:00.000Z',s=>s.workouts[3].sessionIntent.prescription.plannedExercises[0].sets[0].weight=60,s=>s.workouts[3].sessionIntent.deviationReason='fatigue',s=>s.workouts.push(copy(s.workouts[3])),s=>s.scheduledSessions[4].revisions.at(-1).context.prescription.plannedExercises[0].sets[0].weight=80,s=>s.workloadProfiles.at(-1).context.coverage='unknown',s=>s.workloadProfiles.at(-1).context.targets.quadriceps={min:0,max:10,restricted:true}]){const bad=copy(state);mutate(bad);assert.equal(R.proposals(bad,{asOf:'2026-10-26'}).proposals.length,0);assert.throws(()=>R.respond(bad,second,{asOf:'2026-10-26',now:'2026-10-26T20:00:00.000Z',response:'accepted',confirmed:true}));}
const hold=copy(state);hold.workouts[3].exercises[0].sets[0].reps=10;assert.equal(H.progression(hold,'repeat',{asOf:'2026-10-26'}).findings[0].status,'hold');
const declined=R.respond(state,second,{asOf:'2026-10-26',now:'2026-10-26T20:00:00.000Z',response:'declined',confirmed:true});assert.deepEqual(declined.scheduledSessions,state.scheduledSessions);
state=R.respond(state,second,{asOf:'2026-10-26',now:'2026-10-26T20:00:00.000Z',response:'accepted',confirmed:true});assert.deepEqual(state.workouts,past);assert.deepEqual(state.hypertrophyPrograms,frozen);assert.deepEqual(state.scheduledSessions[7],beforeSecond.scheduledSessions[7],'Protected lower-volume week remains unchanged');
assert.equal(R.proposals(state,{asOf:'2026-10-26'}).proposals.length,0);log(4,70);log(5,70);coverage('2026-11-09');assert.equal(H.progression(state,'repeat',{asOf:'2026-11-09'}).findings[0].currentKg,70);assert.equal(H.progression(state,'repeat',{asOf:'2026-11-09'}).findings[0].approvedIncreases,2);assert.equal(R.outcomes(state,{asOf:'2026-11-09'})[1].workoutIds.length,2);assert.equal(R.outcomes(state,{asOf:'2026-11-09'})[0].workoutIds.length,2,'Later-dose follow-ups belong only to their exact approval');
const normalized=Core.normalizeState(state),pkg=Sync.createPackage(normalized,{clientId:'repeat'});assert.equal(Sync.verifyPackage(pkg).verified,true);assert.deepEqual(Sync.projectState(pkg.data).coachingReviews,state.coachingReviews);
// A shared session revision for one exercise must not strand the other slots.
const core={...config.slots[0],exerciseId:'core',name:'Core support',muscles:{confirmed:true,mode:'resistance',primary:['trunk'],secondary:[]},weightKg:20,incrementKg:2};
let multi={...initial,exerciseCatalog:[...initial.exerciseCatalog,{id:'core',name:core.name,muscles:core.muscles}],hypertrophyPrograms:[],scheduledSessions:[],workouts:[],workloadProfiles:[],coachingReviews:[]};
multi=H.save(multi,H.prepare(multi,{...config,slots:[config.slots[0],core]},{asOf:'2026-10-04',goalId:multi.athleteGoals[0].id}),{confirmed:true,workloadConfirmed:true},{asOf:'2026-10-04',now:'2026-10-04T12:00:00.000Z',id:'multi'});multi=H.schedule(multi,'multi',{asOf:'2026-10-04',now:'2026-10-04T13:00:00.000Z'});
for(const row of S.list(multi.scheduledSessions).slice(0,2))multi.workouts.push({id:row.id,date:row.date,createdAt:row.date+'T18:00:00.000Z',sessionIntent:{schedule:{id:row.id,revisionAt:row.revisionAt},prescription:copy(row.prescription),deviationReason:'none'},exercises:row.prescription.plannedExercises.map(e=>({exerciseId:e.exerciseId,type:'strength',sets:e.sets.map(s=>({weight:s.weight,reps:s.maxReps,rpe:8}))}))});
multi=W.save(multi,{coverage:'complete',from:'2026-10-01',through:'2026-10-12',tolerance:'tolerated',targets:{}},{now:'2026-10-12T19:00:00.000Z'});
assert.equal(R.proposals(multi,{asOf:'2026-10-12'}).proposals.length,2);multi=R.respond(multi,R.proposals(multi,{asOf:'2026-10-12'}).proposals.find(p=>p.exerciseId==='press'),{asOf:'2026-10-12',now:'2026-10-12T20:00:00.000Z',response:'accepted',confirmed:true});
const coreProposal=R.proposals(multi,{asOf:'2026-10-12'}).proposals.find(p=>p.exerciseId==='core');assert(coreProposal);assert.equal(coreProposal.fromKg,20);assert.equal(coreProposal.toKg,22);multi=R.respond(multi,coreProposal,{asOf:'2026-10-12',now:'2026-10-12T20:01:00.000Z',response:'accepted',confirmed:true});assert.deepEqual(H.progression(multi,'multi',{asOf:'2026-10-12'}).findings.map(f=>f.currentKg),[65,22]);
console.log('Two approved progression cycles, fresh dose/revision evidence, stale/failed gates, protected weeks and sync preservation passed');
