const assert=require('node:assert/strict');
const Review=require('../src/product/cycle-review'),Cycle=require('../src/product/meet-cycle'),Phase=require('../src/product/phase-builder'),Schedule=require('../src/product/schedule');
const {phaseFixture}=require('./fixtures/phase-builder');
const {state,config}=phaseFixture(),args={asOf:'2026-09-24',now:'2026-09-24T12:00:00.000Z'};
const source=Phase.save(state,Phase.prepare(state,config,args),{confirmed:true},{...args,id:'setup'});
const cycle=Cycle.prepare(source,source.phasePrograms[0],{version:1,weeks:12,peakWeeks:2,taperWeeks:1,meetDate:'2026-12-19'},args);
const approved=Cycle.save(source,cycle,{confirmed:true},{...args,id:'c12'});
const scheduled=Cycle.schedule(approved,'c12',{...args,now:'2026-09-24T13:00:00.000Z'}),snapshot=JSON.stringify(scheduled);
const asOf='2026-10-04',now='2026-10-04T19:00:00.000Z';
const incomplete=Review.analyze(scheduled,{cycleId:'c12',week:1,asOf,now});
assert.equal(incomplete.kind,'weekly');assert.equal(incomplete.guidance.summary.unconfirmed,3);
assert.equal(incomplete.findings.squat.canReduceOne,false);
assert.throws(()=>Review.preview(incomplete,{squat:'reduce-one',bench:'keep',deadlift:'keep'}),/not supported/);
const keep={squat:'keep',bench:'keep',deadlift:'keep'};
assert.throws(()=>Review.apply(scheduled,incomplete,keep,{confirmed:false,asOf,now}),/Approve/);
const kept=Review.apply(scheduled,incomplete,keep,{confirmed:true,asOf,now,id:'week-one'});
assert.equal(kept.meetCycles[0].weeklyReviews.length,1);assert.equal(kept.meetCycles[0].weeklyReviews[0].changes.length,0);
assert.equal(JSON.stringify(kept.scheduledSessions),JSON.stringify(scheduled.scheduledSessions));
assert.throws(()=>Review.analyze(kept,{cycleId:'c12',week:1,asOf,now}),/already has/);
assert.deepEqual(Review.validate(kept),kept.meetCycles);
const active={...scheduled,workouts:[...scheduled.workouts]};
for(const row of cycle.sessions.filter(s=>s.week===1)){
 const record=scheduled.scheduledSessions.find(x=>x.id==='meet:c12:'+row.key),plan=record.revisions[0].context.prescription;
 active.workouts.push({id:'completed-'+row.key,date:row.date,createdAt:row.date+'T17:00:00.000Z',exercises:plan.plannedExercises.map(e=>({...e,sets:e.sets.map((s,i)=>({weight:s.weight,reps:s.reps,rpe:e.exerciseId===config.lifts.squat.exerciseId&&i<2?Math.min(10,s.targetRpe+1):s.targetRpe}))})),sessionIntent:{prescription:plan,schedule:{id:record.id,revisionAt:record.revisions[0].recordedAt}}});
}
const report=Review.analyze(active,{cycleId:'c12',week:1,asOf,now});
assert.equal(report.guidance.summary.completed,3);assert.equal(report.findings.squat.canReduceOne,true);
assert.equal(report.findings.bench.canReduceOne,false);assert.equal(report.findings.deadlift.canReduceOne,false);
const choices={...keep,squat:'reduce-one'},baseline=JSON.stringify(active),changes=Review.apply(active,report,choices,{confirmed:true,asOf,now:'2026-10-04T19:01:00.000Z',id:'approved-squat'});
const review=changes.meetCycles[0].weeklyReviews[0];
assert.equal(review.changes.length,2,'Each squat exposure receives one set reduction');
assert.equal(review.kind,'weekly');assert.equal(review.report.findings.squat.aboveCap,2);
assert.deepEqual(changes.meetCycles[0].sessions,active.meetCycles[0].sessions,'Original cycle is immutable');
assert.deepEqual(changes.workouts,active.workouts,'Workout history not rewritten');
assert.deepEqual(changes.scheduledSessions.slice(0,3),active.scheduledSessions.slice(0,3),'Completed week not rewritten');
assert(review.changes.every(c=>c.after.context.date>asOf&&c.after.context.prescription.capturedAt==='2026-10-04T19:01:00.000Z'));
for(const edit of review.changes){const original=edit.before.context.prescription,updated=edit.after.context.prescription;for(const e of original.plannedExercises){const after=updated.plannedExercises.find(x=>x.exerciseId===e.exerciseId);if(e.exerciseId===config.lifts.squat.exerciseId||e.exerciseId==='ss')assert.equal(after.sets.length,e.sets.length-1);else assert.deepEqual(after.sets,e.sets);}}
assert.throws(()=>Review.analyze(changes,{cycleId:'c12',week:1,asOf,now:'2026-10-04T19:02:00.000Z'}),/already has/);
const stale=structuredClone(active);stale.scheduledSessions=Schedule.change(stale.scheduledSessions,'meet:c12:'+cycle.sessions.find(s=>s.week===2&&s.exercises.some(e=>e.lift==='squat')).key,{status:'skipped',reason:'Unavailable'},'2026-10-04T18:00:00.000Z');
assert.throws(()=>Review.apply(stale,report,choices,{confirmed:true,asOf,now:'2026-10-04T19:01:00.000Z'}),/changed|regenerate/);
const lockedId='meet:c12:'+cycle.sessions.find(s=>s.week===2&&s.exercises.some(e=>e.lift==='squat')).key;
assert.throws(()=>Review.apply(active,report,choices,{confirmed:true,asOf,now:'2026-10-04T19:01:00.000Z',lockedSessionIds:[lockedId]}),/open in a workout draft/);
const unknown=structuredClone(active);unknown.workouts[unknown.workouts.length-1].sessionIntent.schedule.revisionAt='2026-10-01T00:00:00.000Z';
assert.equal(Review.analyze(unknown,{cycleId:'c12',week:1,asOf,now}).findings.squat.canReduceOne,false);
const transitionWeek=cycle.weekly.find(w=>w.phase==='accumulation'&&cycle.weekly[w.week]?.phase==='strength');
assert(transitionWeek);const transition=Review.analyze(scheduled,{cycleId:'c12',week:transitionWeek.week,asOf:transitionWeek.endDate,now:transitionWeek.endDate+'T23:00:00.000Z'});
assert.equal(transition.kind,'phase-transition');assert.equal(transition.nextPhase,'strength');
const peak=cycle.weekly.find(w=>w.phase==='strength'&&cycle.weekly[w.week]?.phase==='peaking');
const peakReport=Review.analyze(scheduled,{cycleId:'c12',week:peak.week,asOf:peak.endDate,now:peak.endDate+'T23:00:00.000Z'});
assert.equal(peakReport.nextPhase,'peaking');assert(Object.values(peakReport.findings).every(f=>!f.canReduceOne));
const after=JSON.stringify(active);assert.equal(after,baseline);assert.equal(JSON.stringify(scheduled),snapshot);
console.log('v2.32 weekly and transition review, independent lifts, missing evidence, immutable plans, approved revision audit, stale state, drafts and no peak rewrite passed');
