const assert=require('node:assert/strict');
const Core=require('../src/core/loadnote-core'),Blocks=require('../src/product/training-blocks'),Readiness=require('../src/product/decision-readiness'),Integrity=require('../src/product/data-integrity');
const catalog=[{id:'squat-id',name:'Back Squat',aliases:['Squat']},{id:'ssb-id',name:'Safety Bar Squat',aliases:[]},{id:'bench-id',name:'Bench Press',aliases:[]},{id:'deadlift-id',name:'Deadlift',aliases:[]}];
let roleId=0,roles=Readiness.replace([],[
 {exerciseId:'squat-id',role:'competition',competitionLift:'squat'},
 {exerciseId:'ssb-id',role:'close-variation',competitionLift:'squat'},
 {exerciseId:'bench-id',role:'competition',competitionLift:'bench'},
 {exerciseId:'deadlift-id',role:'competition',competitionLift:'deadlift'}
],{now:'2026-09-02T00:00:00.000Z',createId:()=>`role-${++roleId}`});
assert.equal(Readiness.validate(roles).length,4);assert.equal(Readiness.list(roles,'2026-09-01T23:59:59.999Z').length,0,'future role knowledge must not leak');
assert.deepEqual(Readiness.suggestion('Safety Bar Squat'),{role:'close-variation',competitionLift:'squat'});assert.deepEqual(Readiness.suggestion('Barbell Bench Press'),{role:'competition',competitionLift:'bench'});
const blockContext={name:'Return to Powerlifting',startDate:'2026-06-10',endDate:'2026-09-08',blockType:'return-reentry',primaryGoal:'Rebuild strength and work capacity',loadStrategy:'conservative',progressionIntent:'return-ramp',dataCompleteness:'complete',trainingMaxes:[{exercise:'Back Squat',exerciseId:'squat-id',kg:165.56,observedOn:'2026-06-10'}],known1RMs:[{exercise:'Back Squat',exerciseId:'squat-id',kg:202.30,observedOn:'2026-06-01'}]};
const trainingBlocks=Blocks.upsert([],blockContext,{now:'2026-09-01T00:00:00.000Z'});
const workout=(id,date,exerciseId,name,weight,rpe=7)=>({id,date,createdAt:`${date}T20:00:00.000Z`,updatedAt:`${date}T20:00:00.000Z`,exercises:[{exerciseId,name,sets:[{weight,reps:5,rpe}]}]});
const workouts=[workout('s1','2026-06-10','squat-id','Back Squat',120,6),workout('s2','2026-06-17','squat-id','Back Squat',130,7),workout('s3','2026-06-24','squat-id','Back Squat',140,8),workout('v1','2026-06-25','ssb-id','Safety Bar Squat',200,6),workout('b1','2026-06-11','bench-id','Bench Press',90,7),workout('d1','2026-06-12','deadlift-id','Deadlift',160,null)];
const state={schemaVersion:13,exerciseCatalog:catalog,exerciseRoles:roles,trainingBlocks,workouts,workoutRevisions:[],athleteProfile:{squat:200,bench:145,deadlift:260}};
const corrected=Readiness.snapshot(state,{asOf:'2026-06-30',retrospective:true});
assert.equal(corrected.decisionAllowed,false);assert.equal(corrected.mode,'current-corrected');assert.equal(corrected.lifts.squat.status,'ready');assert.equal(corrected.lifts.bench.status,'limited');assert.equal(corrected.lifts.deadlift.status,'limited');
assert.equal(corrected.lifts.squat.metrics.bestLoggedLoad,140,'close variations must not become competition-lift performance');assert.equal(corrected.lifts.squat.metrics.variationSessions,1);
assert.ok(corrected.lifts.squat.metrics.observedHardSetsPerWeek>0);assert.equal(corrected.lifts.squat.evidence.baselineEstimatedCapacity.date,'2026-06-10');assert.equal(corrected.lifts.squat.evidence.estimatedCapacity.date,'2026-06-24');
assert.equal(corrected.lifts.squat.evidence.trainingMax.kg,165.56);assert.equal(corrected.lifts.squat.evidence.known1RM.kg,202.30);assert.equal(corrected.lifts.squat.evidence.profileBenchmark.kg,200);assert.notEqual(corrected.lifts.squat.evidence.estimatedCapacity.kg,corrected.lifts.squat.evidence.trainingMax.kg);assert.match(corrected.lifts.squat.interpretation,/not equivalent/);
const historical=Readiness.snapshot(state,{asOf:'2026-06-30'});assert.equal(historical.mode,'as-recorded');assert.equal(historical.block,null);assert.equal(historical.lifts.squat.status,'not-ready');assert.match(historical.lifts.squat.reasons.join(' '),/Confirm/);
const mergedIdentity=Integrity.mergeExercises({exerciseCatalog:[{id:'source',name:'Barbell Squat',aliases:[]},{id:'target',name:'Back Squat',aliases:[]}],exerciseRoles:Readiness.replace([],[{exerciseId:'source',role:'close-variation',competitionLift:'squat'},{exerciseId:'target',role:'competition',competitionLift:'squat'}],{now:'2026-09-03T00:00:00.000Z',createId:(()=>{let n=0;return()=>`merge-role-${++n}`;})()}),workouts:[],templates:[],prs:[],trainingBlocks:[],workoutRevisions:[]},'source','target');assert.equal(Readiness.list(Readiness.validate(mergedIdentity.exerciseRoles)).length,1);assert.equal(Readiness.list(mergedIdentity.exerciseRoles)[0].exerciseId,'target');
const before=workout('edited','2026-06-20','bench-id','Bench Press',100,8),after={...before,updatedAt:'2026-07-02T00:00:00.000Z',exercises:[{exerciseId:'bench-id',name:'Bench Press',sets:[{weight:110,reps:5,rpe:8}]}]},replay=Readiness.workoutsAt({workouts:[after],workoutRevisions:[{id:'revision',workoutId:'edited',recordedAt:'2026-07-02T00:00:00.000Z',action:'edit',before,after}]},'2026-06-30','2026-06-30T23:59:59.999Z',false);assert.equal(replay.workouts[0].exercises[0].sets[0].weight,100);
const migrated=Core.normalizeState({schemaVersion:12,workouts:[{id:'legacy',date:'2026-01-01',exercises:[]}]},{});assert.equal(migrated.schemaVersion,13);assert.equal(migrated.releaseVersion,'1.12.0');assert.deepEqual(migrated.exerciseRoles,[]);assert.equal(migrated.workouts[0].date,'2026-01-01');
console.log('Decision readiness roles, evidence separation, replay and migration passed');
