const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const P=require('../src/product/phase-builder'),W=require('../src/product/programming-workspace'),H=require('../src/product/training-hub'),A=require('../src/product/accessory-programming');
const {state,config}=require('./fixtures/phase-builder').phaseFixture(),args={asOf:'2026-09-24',now:'2026-09-24T12:00:00.000Z'};
const saved=P.save(state,P.prepare(state,config,args),{confirmed:true},{...args,id:'demo-phase'}),before=JSON.stringify(saved);
assert.equal(W.route(saved,{asOf:args.asOf}).primaryAction,'review-phase');assert.equal(W.route(saved,{asOf:args.asOf}).sourceId,'demo-phase');
assert.equal(saved.scheduledSessions.length,0,'Saving alone never schedules');
const scheduled=P.schedule(saved,'demo-phase',{...args,now:'2026-09-24T13:00:00.000Z'});
assert.equal(W.route(scheduled,{asOf:args.asOf}).primaryAction,'view-current');
assert.doesNotMatch(H.inspect(scheduled,args).review.detail,/Schedule a supported program/);assert.equal(JSON.stringify(saved),before);
const accessory={policy:A.POLICY,exerciseId:'row',name:'Dumbbell Row',day:0,group:'upper-back',purpose:'hypertrophy',equipment:'dumbbells',equipmentConfirmed:true,mode:'reps',sets:2,weightKg:15,targetRpe:7,minReps:8,maxReps:12};
const deload=A.exercises([accessory],0,'deload')[0],frozen=JSON.stringify(deload);
assert.equal(deload.sets[0].targetRpe,6);assert.match(A.explanation(deload),/at or below RPE 6\./);assert.doesNotMatch(A.explanation(deload),/RPE 7/);assert.equal(JSON.stringify(deload),frozen);
assert.match(A.explanation(A.exercises([accessory],0,'strength')[0]),/RPE 7/);
const recap={hidden:false,children:['old saved workout'],replaceChildren(){this.children=[];}};
const ctx={document:{getElementById:id=>id==='workout-recap'?recap:null}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../src/product/training-flow'),'utf8'),ctx);ctx.clearWorkoutRecap();assert.equal(recap.hidden,true);assert.equal(recap.children.length,0);
console.log('Demo cleanup: reviewed scheduling route, immutable deload wording, weekly review labels and recap clearing passed');
