const assert=require('node:assert/strict');
const R=require('../src/product/exercise-reference'),E=require('../src/product/exercise-explanation'),A=require('../src/product/accessory-programming'),I=require('../src/product/data-integrity'),P=require('../src/product/programming-profile'),C=require('../src/product/coach-conversation');
const {phaseFixture}=require('./fixtures/phase-builder');
const {state}=phaseFixture(),before=JSON.stringify(state);
assert.equal(R.resolve('DB bench press').name,'Dumbbell Bench Press');
assert.equal(R.resolve('row'),null);assert.equal(E.named('What is a row?'),null);
assert.equal(E.named('What is Side Plank?').name,'Side Plank');
assert.equal(E.named('Compare Plank and Leg Curl'),null);
const suggestions=R.suggestions({priorities:'Upper back, quads and biceps',equipment:['bodyweight','dumbbells'],identify:I.stableExerciseId});
assert(suggestions.some(t=>t.name==='Chest-supported Row'));
assert(suggestions.every(t=>['bodyweight','dumbbells'].includes(t.equipment)));
const renamed=[{id:'saved-row',name:'My supported row',aliases:['Chest-supported Row']}];
const preferred=R.suggestions({preferredExerciseIds:['saved-row'],equipment:['dumbbells'],catalog:renamed,identify:I.stableExerciseId});
assert.equal(preferred[0].id,'saved-row');assert.equal(preferred[0].name,'My supported row');assert.match(preferred[0].reason,/preferred/);
assert.equal(R.suggestions({preferredExerciseIds:['saved-row'],excludedExerciseIds:['saved-row'],equipment:['dumbbells'],catalog:renamed,identify:I.stableExerciseId}).length,0);
const p=P.current(state.programmingProfiles).context;
assert(!Object.hasOwn(P.context(p),'accessoryEquipment'));assert.throws(()=>P.context({...p,accessoryEquipment:['unknown']}));
const updated={...state,programmingProfiles:P.save(state.programmingProfiles,{...p,accessoryEquipment:['bodyweight','dumbbells'],avoidedExerciseIds:['blocked']},{id:'tools',now:'2026-09-24T12:00:00.000Z'}),exerciseCatalog:[...state.exerciseCatalog,{id:'blocked',name:'Dumbbell Row'}]};
const alt=E.answer(updated,'What alternatives to Lat Pulldown can I use?');
assert.match(alt.text,/Chest-supported Row/);assert(!alt.text.includes('Dumbbell Row ('));assert(!alt.text.includes('Pull-Up ('));assert.match(alt.text,/separate starting load/);
const follow=E.answer(updated,'Only dumbbells instead?',{history:[{role:'user',content:'What is Lat Pulldown?'},{role:'assistant',content:'Use a machine'}]});assert.match(follow.text,/Chest-supported Row/);
const live={liveWorkout:{currentExercise:{name:'Plank',index:0},exercises:[{name:'Plank',completedSets:1,totalSets:2}]}},intelligence={session:{plannedExercise:{name:'Plank',purpose:'Reviewed trunk hold'}}};
const current=E.answer(updated,'Why this exercise?',{live,intelligence});assert.match(current.text,/Reviewed trunk hold/);assert.match(current.text,/1 of 2 sets marked complete/);
const swapped=E.answer(updated,'Why this exercise?',{live,intelligence:{session:{plannedExercise:{name:'Side Plank',purpose:'Old target'}}}});assert(!swapped.text.includes('Old target'));
assert.match(C.answer(updated,'Can I swap this exercise because my knee hurts?',{asOf:'2026-09-24',live,intelligence}).text,/cannot diagnose/);
const row={policy:A.POLICY,name:'Lat Pulldown',exerciseId:I.stableExerciseId('Lat Pulldown'),equipment:'cable',equipmentConfirmed:true,group:'upper-back',purpose:'hypertrophy',day:0,mode:'reps',sets:2,weightKg:20,targetRpe:7,minReps:8,maxReps:12};
assert.throws(()=>A.context(updated,[row],P.current(updated.programmingProfiles)),/absent/);
A.context(state,[row],P.current(state.programmingProfiles)); // Legacy unknown access still needs per-movement confirmation.
assert.equal(JSON.stringify(state),before);
const Intelligence=require('../src/product/companion-intelligence');
const linked={...state,phasePrograms:[{id:'reviewed',config:{accessories:[row]}}]};
const draft={sessionIntent:{prescription:{source:{referenceId:'reviewed'},plannedExercises:[{name:row.name,exerciseId:row.exerciseId,sets:[{reps:8,weight:20,targetRpe:7}]}]}}};
assert.match(Intelligence.sessionSummary(linked,draft,{currentExercise:{name:row.name}}).plannedExercise.purpose,/Athlete-selected hypertrophy work for upper back/);
const mismatch=structuredClone(draft);mismatch.sessionIntent.prescription.plannedExercises[0].exerciseId='another-row';assert.equal(Intelligence.sessionSummary(linked,mismatch,{currentExercise:{name:row.name}}).plannedExercise.purpose,null);
console.log('Shared exercise reference preserves saved identities, equipment exclusions, contextual explanations and read-only follow-ups');
