const assert=require('node:assert/strict'),A=require('../src/product/guided-plan'),F=require('./fixtures/coaching'),G=require('../src/product/athlete-goals'),P=require('../src/product/programming-profile'),C=require('../src/product/coaching-context');
const state=F.hypertrophy();state.exerciseCatalog.push({id:'push',name:'Chest press',muscles:{confirmed:true,mode:'resistance',primary:['chest'],secondary:['triceps']}},{id:'pull',name:'Upper back row',muscles:{confirmed:true,mode:'resistance',primary:['upper-back'],secondary:['biceps']}});
const before=JSON.stringify(state),view=A.inspect(state,'hypertrophy');assert.equal(view.roles[2].choices[0].id,'pull');const seed=A.draft(state,{mode:'hypertrophy',goalId:state.athleteGoals[0].id,days:[0],selections:{lower:'press',push:'push',pull:'pull'}});assert.equal(seed.slots.length,3);assert.equal(seed.minutes,60);assert(seed.slots.every(s=>s.weightKg===undefined));assert.equal(JSON.stringify(state),before);
assert.throws(()=>A.draft(state,{mode:'hypertrophy',goalId:seed.goalId,days:[1],selections:{lower:'press',push:'push',pull:'pull'}}));assert.throws(()=>A.draft(state,{mode:'hypertrophy',goalId:seed.goalId,days:[0],selections:{lower:'push',push:'push',pull:'pull'}}));assert.throws(()=>A.inspect(state,'guessed'));
const restricted=structuredClone(state);restricted.workloadProfiles.at(-1).context.targets.chest={min:0,max:10,restricted:true};assert.equal(A.inspect(restricted,'hypertrophy').roles[1].choices.length,0);
state.programmingProfiles=P.save([],{goal:'hypertrophy',experience:'intermediate',consistency:'consistent',availableDays:[0],sessionMinutes:45,equipment:[],avoidedExerciseIds:['pull'],preferredExerciseIds:[]},{now:'2026-10-04T14:00:00.000Z'});assert.equal(A.inspect(state,'hypertrophy').goals[0].minutes,45);assert.equal(A.inspect(state,'hypertrophy').roles[2].choices.length,0);
for(const mode of ['weightlifting','athlete']){const s=F.sport(mode);s.exerciseCatalog.push({id:'support',name:'Squat',muscles:{confirmed:true,mode:'resistance',primary:['quadriceps'],secondary:['glutes']}});const role=mode==='weightlifting'?'technical':'quality',id=mode==='weightlifting'?'snatch':'sprint',g=G.list(s.athleteGoals)[0];const d=A.draft(s,{mode,goalId:g.id,days:[0],selections:{[role]:id,support:'support'},drillKind:'jump'});assert.equal(d.slots[0].kind,mode==='weightlifting'?'weightlifting':'jump');assert.equal(d.slots[0].protocol,undefined);s.athleteGoals=G.upsert(s.athleteGoals,{...g,trainingContext:{...g.trainingContext,competitionDays:[1]}},{id:g.id,now:'2026-10-04T14:00:00.000Z'});assert.equal(A.inspect(s,mode).goals[0].days.length,0);assert.throws(()=>A.draft(s,{mode,goalId:g.id,days:[0],selections:{[role]:id,support:'support'}}));}
assert.match(C.answer(state,'Help me create a muscle growth plan',{asOf:'2026-10-12'}).text,/Starter plans/);
console.log('Guided identities, availability, sport-day protection, explicit dose gaps, preferences and read-only Coach passed');
