const assert=require('node:assert/strict'),H=require('../src/product/hypertrophy-builder'),G=require('../src/product/athlete-goals'),W=require('../src/product/muscle-workload-review'),S=require('../src/product/schedule'),I=require('../src/product/session-intent'),L=require('../src/product/program-lifecycle'),V=require('../src/product/program-workout-viewer'),C=require('../src/product/coach-conversation'),Core=require('../src/core/loadnote-core'),Sync=require('../src/product/sync-model'),D=require('../src/product/data-integrity'),Guidance=require('../src/product/set-guidance');
const copy=x=>JSON.parse(JSON.stringify(x)),asOf='2026-10-04',now='2026-10-04T10:00:00.000Z',muscles={confirmed:true,mode:'resistance',primary:['quadriceps'],secondary:['glutes']};
let goals=G.upsert([],{name:'Muscle growth',sport:'Resistance training',equipment:'Leg press and plates',availableDays:[0,3],sessionMinutes:60,trainingContext:{primary:'hypertrophy',secondary:[],season:'off-season',scheduleKnown:true,practiceDays:[],competitionDays:[]}},{now:'2026-10-01T10:00:00.000Z'});
const goalId=goals[0].id,slot={day:0,exerciseId:'press',name:'Leg press',muscles,equipment:'machine',equipmentConfirmed:true,loadConvention:'stack',sets:3,minReps:8,maxReps:12,weightKg:60,incrementKg:5,targetRpe:8,restSeconds:120,purpose:'Athlete-selected quad training'},config={version:1,name:'Reviewed growth',startDate:'2026-10-05',weeks:4,days:[0],sessionMinutes:60,deloadWeeks:[4],sportCoordinationConfirmed:false,slots:[slot]},state={athleteGoals:goals,exerciseCatalog:[{id:'press',name:'Leg press',muscles}],workouts:[],scheduledSessions:[],hypertrophyPrograms:[],programmingProfiles:[],workloadProfiles:[],phasePrograms:[],meetCycles:[],activeProgramId:'keep',programs:[{id:'keep'}]};
const before=JSON.stringify(state),p=H.prepare(state,config,{asOf,goalId});assert.equal(p.sessions.length,4);assert.equal(p.weekly[0].groups.quadriceps.direct,3);assert.equal(p.weekly[0].groups.glutes.indirect,3);assert.equal(p.weekly[0].groups.quadriceps.effortUnknown,3);assert.equal(p.sessions[3].exercises[0].sets.length,2);assert.equal(p.sessions[3].exercises[0].sets[0].targetRpe,6);assert(p.sessions.every(s=>s.exercises[0].sets[0].weight===60));assert.equal(p.currentWorkload.length,4);assert.equal(JSON.stringify(state),before);
for(const changes of [{days:[0,0]},{startDate:'2026-10-06'},{weeks:0},{deloadWeeks:[1,2,3,4]},{sessionMinutes:30,slots:[{...slot,sets:6,restSeconds:600}]},{slots:[{...slot,equipmentConfirmed:false}]},{slots:[{...slot,loadConvention:'per-hand'}]},{slots:[{...slot,muscles:{...muscles,mode:'weightlifting'}}]},{slots:[{...slot,weightKg:.001}]},{slots:[{...slot,minReps:5}]},{slots:[{...slot,targetRpe:10}]},{slots:[slot,slot]},{days:[0,3],slots:[slot,{...slot,day:3,muscles:{...muscles,primary:['glutes'],secondary:[]}}]}])assert.throws(()=>H.build({...config,...changes}));
assert.throws(()=>H.prepare({...state,athleteGoals:[]},config,{asOf,goalId}));assert.throws(()=>H.prepare(state,{...config,days:[2],slots:[{...slot,day:2}]},{asOf,goalId}));assert.throws(()=>H.prepare({...state,exerciseCatalog:[{...state.exerciseCatalog[0],name:'Renamed'}]},config,{asOf,goalId}));
const changedGoal=(changes)=>G.upsert(goals,{...G.list(goals)[0],...changes},{id:goalId,now:'2026-10-04T09:00:00.000Z'});
assert.throws(()=>H.prepare({...state,athleteGoals:changedGoal({eventDate:'2026-10-18'})},config,{asOf,goalId}));assert.throws(()=>H.prepare({...state,athleteGoals:changedGoal({trainingContext:{...G.list(goals)[0].trainingContext,scheduleKnown:true,practiceDays:[0]}})},config,{asOf,goalId}));
const overlap={...state,athleteGoals:changedGoal({trainingContext:{...G.list(goals)[0].trainingContext,practiceDays:[0]}})};assert(H.prepare(overlap,{...config,sportCoordinationConfirmed:true},{asOf,goalId}));
const restricted=W.save(state,{coverage:'unknown',tolerance:'unknown',targets:{quadriceps:{min:3,max:9,restricted:true}}},{now});assert.throws(()=>H.prepare(restricted,config,{asOf,goalId}));for(const tolerance of ['discomfort','needs-review'])assert.throws(()=>H.prepare(W.save(state,{coverage:'unknown',tolerance,targets:{}},{now}),config,{asOf,goalId}));
assert.throws(()=>H.save(state,p,{confirmed:true},{asOf,now}));const saved=H.save(state,p,{confirmed:true,workloadConfirmed:true},{asOf,now,id:'hyp'});assert.equal(saved.scheduledSessions.length,0);assert.equal(saved.activeProgramId,'keep');assert.deepEqual(H.validate(copy(saved.hypertrophyPrograms)),saved.hypertrophyPrograms);assert.throws(()=>H.save({...state,athleteGoals:changedGoal({name:'Changed'})},p,{confirmed:true,workloadConfirmed:true},{asOf,now}));assert.throws(()=>H.save(state,p,{confirmed:true,workloadConfirmed:true,by:'coach-reported'},{asOf,now}));
for(const mutate of [r=>r.sessions.pop(),r=>r.weekly[0].groups.quadriceps.direct++,r=>r.review.workloadConfirmed=false,r=>r.scheduledAt='2026-10-01T00:00:00.000Z',r=>r.goalSnapshot.context.trainingContext=null]){const bad=copy(saved.hypertrophyPrograms);mutate(bad[0]);assert.throws(()=>H.validate(bad));}assert.throws(()=>H.validate(null));
const scheduled=H.schedule(saved,'hyp',{asOf,now:'2026-10-04T11:00:00.000Z'});assert.equal(scheduled.scheduledSessions.length,4);assert.equal(G.list(scheduled.athleteGoals)[0].sessionIds.length,4);assert.equal(S.list(scheduled.scheduledSessions)[0].prescription.plannedExercises[0].restSeconds,120);assert.equal(S.list(scheduled.scheduledSessions)[0].prescription.plannedExercises[0].loadConvention,'stack');assert.equal(saved.hypertrophyPrograms[0].scheduledAt,null);assert.throws(()=>H.schedule(scheduled,'hyp',{asOf,now}));assert.throws(()=>H.schedule(saved,'hyp',{asOf,now,draftOpen:true}));assert.throws(()=>H.schedule({...saved,workouts:[{date:'2026-10-05'}]},'hyp',{asOf,now}));assert.throws(()=>H.schedule({...saved,scheduledSessions:scheduled.scheduledSessions},'hyp',{asOf,now}));assert.throws(()=>H.schedule({...saved,athleteGoals:changedGoal({name:'Edited'})},'hyp',{asOf,now}));
assert.equal(L.inspect(scheduled,{asOf:'2026-10-05'}).nextAction.kind,'start-workout');assert.equal(L.inspect(scheduled,{asOf:'2026-10-12'}).nextAction.kind,'resolve-overdue');const skipped={...scheduled,scheduledSessions:scheduled.scheduledSessions.map(r=>({...r,revisions:r.revisions.map(v=>({...v,context:{...v.context,status:'skipped'}}))}))};assert.equal(L.inspect(skipped,{asOf:'2026-11-03'}).nextAction.kind,'review-hypertrophy');
let logged=copy(scheduled);for(const row of S.list(logged.scheduledSessions).slice(0,2)){const prescription=copy(row.prescription);logged.workouts.push({id:row.id,date:row.date,createdAt:row.date+'T18:00:00.000Z',sessionIntent:{schedule:{id:row.id,revisionAt:row.revisionAt},prescription,deviationReason:'none'},exercises:[{exerciseId:'press',name:'Leg press',type:'strength',sets:Array.from({length:3},()=>({weight:60,reps:12,rpe:8,done:true}))}]});}
logged=W.save(logged,{coverage:'complete',from:'2026-10-01',through:'2026-10-12',tolerance:'tolerated',targets:{quadriceps:{min:3,max:6,restricted:false}}},{now:'2026-10-12T19:00:00.000Z'});
const initial=JSON.stringify(logged),report=H.progression(logged,'hyp',{asOf:'2026-10-12'});assert.equal(report.findings[0].status,'review-load');assert.equal(report.findings[0].candidateKg,65);assert.equal(JSON.stringify(logged),initial);assert.deepEqual(C.answer(logged,'How do I progress my hypertrophy program?',{asOf:'2026-10-12'}).evidence[0],report);assert.deepEqual(C.answer(logged,'Should I add weight?',{asOf:'2026-10-12',history:[{role:'user',content:'How do I progress my hypertrophy program?'}]}).evidence[0],report);
for(const mutate of [s=>s.workouts[1].exercises[0].sets[0].rpe=null,s=>s.workouts[1].exercises[0].sets[0].rpe=9,s=>s.workouts[1].exercises[0].sets[0].weight=65,s=>s.workouts[1].exercises[0].sets[0].warmup=true,s=>s.workouts[1].sessionIntent.deviationReason='fatigue',s=>s.workouts[1].sessionIntent.prescription.plannedExercises[0].loadConvention='total',s=>s.workouts[1].sessionIntent.prescription.capturedAt='2026-10-12T20:00:00.000Z',s=>s.workloadProfiles[0].context.coverage='unknown',s=>s.workloadProfiles[0].context.tolerance='discomfort',s=>s.workloadProfiles[0].context.targets.quadriceps.restricted=true,s=>s.workouts.push(copy(s.workouts[1])),s=>s.exerciseCatalog[0].muscles.primary=['glutes']]){const changed=copy(logged);mutate(changed);assert.equal(H.progression(changed,'hyp',{asOf:'2026-10-12'}).findings[0].status,'gather');}
const hold=copy(logged);hold.workouts[1].exercises[0].sets[0].reps=10;assert.equal(H.progression(hold,'hyp',{asOf:'2026-10-12'}).findings[0].status,'hold');assert.equal(H.progression(logged,'hyp',{asOf:'2026-10-19'}).findings[0].status,'gather');
assert.equal(Guidance.evaluate([{weight:60,reps:8,minReps:8,maxReps:12,targetRpe:8}],[{weightKg:60,reps:12,rpe:8,done:true}]).status,'within-cap');assert.throws(()=>I.createPrescription([{name:'Press',sets:[{weight:60,reps:8}],restSeconds:1}]));
const migrated=Core.normalizeState({schemaVersion:27,workouts:[]});assert.equal(migrated.schemaVersion,30);assert.deepEqual(migrated.hypertrophyPrograms,[]);const pkg=Sync.createPackage(Core.normalizeState(logged),{clientId:'hypertrophy-test'});assert.equal(Sync.verifyPackage(pkg).verified,true);assert.deepEqual(Sync.projectState(pkg.data).hypertrophyPrograms,logged.hypertrophyPrograms);assert.equal(D.previewImport({hypertrophyPrograms:[]},logged).hypertrophyPrograms.added,1);
const targetState=W.save(state,{coverage:'unknown',tolerance:'unknown',targets:{quadriceps:{min:6,max:12,restricted:false},chest:{min:3,max:6,restricted:false}}},{now});const targetProposal=H.prepare(targetState,config,{asOf,goalId});assert.equal(targetProposal.workloadComparison[0].muscles.find(m=>m.muscle==='chest').direct,0);assert.equal(targetProposal.workloadComparison[0].muscles.find(m=>m.muscle==='chest').outside,true);assert(targetProposal.warnings.some(w=>w.includes('differ from a reviewed target')));
const backup=D.addBackupManifest(logged,{exportedAt:'2026-10-12T20:00:00.000Z'});assert.equal(backup._loadnoteBackup.counts.hypertrophyPrograms,1);assert.equal(D.verifyBackupManifest(backup).verified,true);const damaged=copy(backup);damaged.hypertrophyPrograms=[];assert.equal(D.verifyBackupManifest(damaged).verified,false);
const legacy=Sync.createPackage({...Core.normalizeState(logged),schemaVersion:27},{clientId:'old',createdAt:now});delete legacy.data.collections.hypertrophyPrograms;legacy.manifest=Sync.manifestFromProject(legacy.data);legacy.manifestFingerprint=legacy.manifest.fingerprint;legacy.packageFingerprint=Sync.fingerprint({protocol:legacy.protocol,createdAt:legacy.createdAt,clientId:legacy.clientId,schemaVersion:27,releaseVersion:legacy.releaseVersion,manifestFingerprint:legacy.manifest.fingerprint});assert.equal(Sync.verifyPackage(legacy).verified,true);assert.deepEqual(Sync.projectState(legacy.data).hypertrophyPrograms,[]);legacy.schemaVersion=28;assert.equal(Sync.verifyPackage(legacy).verified,false);
console.log('Hypertrophy build/review/schedule, safety, immutable snapshots, progression, shared Coach, lifecycle and schema-28 tests passed');
