const assert=require('node:assert/strict');
const Workload=require('../src/product/lift-workload');
const {phaseFixture}=require('./fixtures/phase-builder');
const {state,config}=phaseFixture();
const before=JSON.stringify(state),configBefore=JSON.stringify(config);
const empty=Workload.compare({...state,workouts:[],workoutRevisions:[]},config,{asOf:'2026-09-24',now:'2026-09-24T12:00:00.000Z'});
assert.equal(empty.lifts.squat.firstWeekPlan.competitionSets,3);
assert.equal(empty.lifts.squat.firstWeekPlan.variationSets,3);
assert.equal(empty.lifts.bench.firstWeekPlan.competitionSets,9);
assert.equal(empty.lifts.deadlift.firstWeekPlan.competitionSets,2);
assert(empty.lifts.squat.warnings.some(w=>w.includes('Sparse')));
const workouts=['2026-09-02','2026-09-09','2026-09-16','2026-09-23'].map((date,i)=>({id:'evidence-'+i,date,createdAt:date+'T12:00:00.000Z',exercises:[{exerciseId:config.lifts.squat.exerciseId,type:'strength',trackBy:'reps',sets:[{weight:150,reps:3,rpe:8},{weight:140,reps:3,rpe:7}]},{exerciseId:'ss',type:'strength',trackBy:'reps',sets:[{weight:100,reps:5,rpe:7}]},{exerciseId:config.lifts.bench.exerciseId,type:'strength',trackBy:'reps',sets:[{weight:100,reps:3}]},{exerciseId:'other',type:'strength',sets:[{weight:999,reps:5}]}]}));
const future={id:'later',date:'2026-09-23',createdAt:'2026-09-25T00:00:00.000Z',exercises:[{exerciseId:config.lifts.squat.exerciseId,sets:[{weight:999,reps:1,rpe:10}]}]};
const evidence=Workload.compare({...state,workouts:[...workouts,future],workoutRevisions:[]},config,{asOf:'2026-09-24',now:'2026-09-24T12:00:00.000Z'});
assert.equal(evidence.lifts.squat.observedTotals.validSets,12);
assert.equal(evidence.lifts.squat.observedTotals.competitionSets,8);
assert.equal(evidence.lifts.squat.observedTotals.variationSets,4);
assert.equal(evidence.lifts.squat.observedTotals.tonnageKg,5480);
assert.equal(evidence.lifts.squat.rpeCoverage,1);
assert.equal(evidence.lifts.bench.rpeCoverage,0);
assert(evidence.lifts.bench.warnings.some(w=>w.includes('RPE')));
assert.equal(evidence.lifts.deadlift.observedTotals.validSets,0);
assert.equal(evidence.lifts.squat.firstWeekPlan.exposures,2);
assert.equal(JSON.stringify(state),before);
assert.equal(JSON.stringify(config),configBefore);
assert.throws(()=>Workload.compare(state,config,{asOf:'nonsense'}));
assert.throws(()=>Workload.compare(state,config,{asOf:'2026-09-24',now:'broken'}));
console.log('Lift-specific workload comparison tests passed');
