const assert=require('node:assert/strict');
const Meet=require('../src/product/meet-preparation');
const {phaseFixture}=require('./fixtures/phase-builder');
const {state,config}=phaseFixture(),before=JSON.stringify(state),original=JSON.stringify(config);
const result=Meet.plan(config,{meetDate:'2026-12-19',peakWeeks:3});
assert.equal(result.version,1);
assert.equal(result.baseEnd,'2026-11-15');
assert.equal(result.peakStart,'2026-11-23');
assert.equal(result.gapDays,7);
assert.deepEqual(result.weeks.map(w=>w.emphasis),['competition-specific strength','competition-specific strength','taper']);
assert.equal(result.weeks[2].endDate,'2026-12-13');
assert.equal(result.meetWeek.startDate,'2026-12-14');
assert.equal(result.competitionLifts.squat.exerciseId,config.lifts.squat.exerciseId);
assert.equal(result.competitionLifts.deadlift.exerciseId,config.lifts.deadlift.exerciseId);
assert(!('sessions' in result));
assert.equal(JSON.stringify(config),original);
assert.equal(JSON.stringify(state),before);
assert.throws(()=>Meet.plan(config,{meetDate:'2026-12-16'}),/Saturday or Sunday/);
assert.throws(()=>Meet.plan(config,{meetDate:'2026-11-28'}),/overlaps/);
assert.throws(()=>Meet.plan(config,{meetDate:'2026-12-19',peakWeeks:1}),/2–4/);
assert.throws(()=>Meet.plan(config,{meetDate:'2026-12-19',peakWeeks:5}),/2–4/);
assert.throws(()=>Meet.plan(config,{meetDate:'2026-02-30'}));
const sunday=Meet.plan(config,{meetDate:'2026-12-20',peakWeeks:3});
assert.equal(sunday.peakStart,'2026-11-23');
assert.equal(sunday.meetWeek.startDate,'2026-12-14');
const variation=structuredClone(config);variation.lifts.deadlift.exposures.push({day:2,role:'light',format:'straight'});
assert(Meet.plan(variation,{meetDate:'2026-12-19'}).warnings.some(w=>w.includes('deadlift exposure')));
console.log('Meet preparation foundation tests passed');
