const assert=require('node:assert/strict'),Meet=require('../src/product/meet-cycle'),Phase=require('../src/product/phase-builder'),Core=require('../src/core/loadnote-core'),Schedule=require('../src/product/schedule');
const {phaseFixture}=require('./fixtures/phase-builder');
const {state,config}=phaseFixture(),args={asOf:'2026-09-24',now:'2026-09-24T12:00:00.000Z'};
const base=Phase.prepare(state,config,args),reviewed=Phase.save(state,base,{confirmed:true,notes:'Reviewed lift setup'},{...args,id:'base'}),source=reviewed.phasePrograms[0];
const before=JSON.stringify(reviewed);
const date=(weeks)=>{const d=new Date(config.startDate+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+(weeks-1)*7+5);return d.toISOString().slice(0,10)};
for(const weeks of [8,12,16,20,26,52]){
 const p=Meet.prepare(reviewed,source,{version:1,weeks,peakWeeks:2,taperWeeks:1,meetDate:date(weeks)},args);
 assert.equal(p.weekly.length,weeks);assert.equal(p.weekly.at(-1).phase,'mock-meet');assert.equal(p.weekly.at(-1).meetDate,date(weeks));
 assert.equal(p.sessions.length,p.weekly.slice(0,-1).reduce((n,w)=>n+w.sessionCount,0));
 assert.equal(new Set(p.sessions.map(s=>s.key)).size,p.sessions.length);
 assert(p.sessions.every(s=>s.date<date(weeks)&&s.week<weeks));
 assert.deepEqual(p.sessions.filter(s=>s.phase==='taper').flatMap(s=>s.exercises).flatMap(e=>e.sets).map(s=>s.targetRpe),[6,6,6]);
 assert.equal(p.config.accumulationWeeks+p.config.strengthWeeks+p.config.peakWeeks+p.config.taperWeeks+1,weeks);
 assert(p.sessions.every(s=>s.exercises.every(e=>e.sets.every(set=>set.weight>0&&set.weight<=e.trainingMaxKg*.85+.001))));
 if(weeks>16)assert(p.warnings.some(w=>w.includes('six progressive weeks')));
}
const p=Meet.prepare(reviewed,source,{version:1,weeks:12,peakWeeks:2,taperWeeks:1,meetDate:date(12)},args);
assert.equal(p.weekly.filter(w=>w.phase==='peaking').length,2);assert.equal(p.weekly.filter(w=>w.phase==='taper').length,1);
assert.equal(JSON.stringify(reviewed),before);
assert.throws(()=>Meet.save(reviewed,p,{},args),/Review and approve/);
const saved=Meet.save(reviewed,p,{confirmed:true,notes:'Mock meet test'},{...args,id:'meet12'});
assert.equal(saved.meetCycles.length,1);assert.equal(saved.meetCycles[0].scheduledAt,null);
assert.equal(JSON.stringify(saved.workouts),JSON.stringify(reviewed.workouts));
assert.deepEqual(Meet.validate(structuredClone(saved.meetCycles)),saved.meetCycles);
const scheduled=Meet.schedule(saved,'meet12',{...args,now:'2026-09-24T13:00:00.000Z'});
assert.equal(scheduled.scheduledSessions.length,p.sessions.length);
assert.equal(scheduled.meetCycles[0].scheduledAt,'2026-09-24T13:00:00.000Z');
assert(scheduled.scheduledSessions.every(s=>s.revisions[0].context.prescription.source.referenceId==='meet12'));
assert(scheduled.scheduledSessions.every(s=>s.revisions[0].context.date!==date(12)),'No inferred competition attempts');
assert.deepEqual(scheduled.meetCycles[0].sessions,p.sessions,'Immutable original');
assert.throws(()=>Meet.schedule(scheduled,'meet12',{...args,now:'2026-09-24T14:00:00.000Z'}));
const conflict={...saved,scheduledSessions:Schedule.create([],{date:p.sessions[0].date,name:'Existing',role:'mixed',goal:'Other',prescription:scheduled.scheduledSessions[0].revisions[0].context.prescription},{id:'occupied',now:args.now})};
assert.throws(()=>Meet.schedule(conflict,'meet12',{...args,now:'2026-09-24T14:00:00.000Z'}),/Calendar conflict/);
const altered=structuredClone(saved.meetCycles);altered[0].sessions[0].exercises[0].sets[0].weight=999;
assert.throws(()=>Meet.validate(altered),/differs/);
const invalid=overrides=>({...p.config,...overrides});
for(const bad of [invalid({weeks:6}),invalid({weeks:53}),invalid({peakWeeks:5}),invalid({taperWeeks:3}),invalid({weeks:7,peakWeeks:4}),invalid({meetDate:'2026-12-26'}),invalid({meetDate:'2026-12-15'})])assert.throws(()=>Meet.config(bad,source));
const tomorrow={...reviewed,programmingProfiles:[...reviewed.programmingProfiles,{...reviewed.programmingProfiles[0],id:'later',recordedAt:'2026-09-25T12:00:00.000Z',context:{...reviewed.programmingProfiles[0].context,notes:'Later'}}]};
assert.deepEqual(Meet.prepare(tomorrow,source,p.config,args),p,'As-known profile cutoff');
const old=Core.normalizeState({schemaVersion:22,workouts:reviewed.workouts,phasePrograms:reviewed.phasePrograms});
assert.equal(old.schemaVersion,23);assert.deepEqual(old.meetCycles,[]);assert.deepEqual(old.workouts,reviewed.workouts);
assert.deepEqual(Core.normalizeState({...scheduled}).meetCycles,scheduled.meetCycles);
console.log('Flexible 8/12/16/20/26/52 week meet cycles, time and load caps, saved original, conflicts, kg and migration passed');
