const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const config=JSON.parse(read('capacitor.config.json'));
assert.equal(config.appName,'Loadnote');
assert.equal(config.webDir,'www');
assert.match(config.appId,/^[A-Za-z][A-Za-z0-9_]*(\.[A-Za-z][A-Za-z0-9_]*){2,}$/);
const manifest=JSON.parse(read('manifest.webmanifest'));
assert.equal(manifest.name,'Loadnote');
assert.equal(manifest.id,'./');
assert.equal(manifest.scope,'./');
assert.equal(manifest.start_url,'./index.html');
assert.equal(manifest.display,'standalone');
assert.match(manifest.description,/adaptive training log/i);
assert(manifest.icons.some(icon=>icon.sizes==='512x512'&&String(icon.purpose||'').includes('maskable')));
const html=read('index.html');
assert.match(html,/viewport-fit=cover/);
assert(html.includes('src/product/platform-runtime.js'));
assert(html.indexOf('src/product/platform-runtime.js')<html.indexOf('src/product/app-lifecycle.js'));
const styles=read('styles.css');
assert.match(styles,/safe-area-inset-top/);
assert.match(styles,/safe-area-inset-bottom/);
const sync=read('scripts/sync-www.js');
for(const forbidden of ['backend','tests','.github'])assert(!sync.includes("'"+forbidden+"'"),'Mobile sync must not package '+forbidden);
const workflow=read('.github/workflows/test.yml');
assert.match(workflow,/npm run check:mobile/);
console.log('v2.54 mobile manifest, Capacitor shell, safe-area and CI release-gate checks passed');
