const assert=require('node:assert/strict'),P=require('../src/product/phase-builder'),Profile=require('../src/product/programming-profile'),Core=require('../src/core/loadnote-core'),Schedule=require('../src/product/schedule'),Review=require('../src/product/program-review'),{phaseFixture}=require('./fixtures/phase-builder');
const {state,config}=phaseFixture(),args={asOf:'2026-09-24',now:'2026-09-24T12:00:00.000Z'},before=JSON.stringify(state),proposal=P.prepare(state,config,args);
assert.equal(proposal.sessions.length,21);assert.equal(proposal.weekly.length,7);assert.equal(proposal.weekly[0].lifts.squat.sets,6);assert.equal(proposal.weekly[0].lifts.bench.sets,9);assert.equal(proposal.weekly[0].lifts.deadlift.sets,2);assert.equal(proposal.weekly.at(-1).lifts.squat.sets,4);
assert.equal(proposal.sessions[0].exercises[0].sets[0].weight,102.5);assert.equal(proposal.sessions[0].exercises[0].sets[1].weight,90);assert.equal(proposal.sessions[1].exercises[0].sets[0].weight,77.5);assert.equal(proposal.sessions[1].exercises[0].trainingMaxKg,120);
assert.equal(proposal.sessions.at(-1).phase,'deload');assert(proposal.sessions.filter(s=>s.phase==='deload').every(s=>s.exercises.every(e=>e.format==='straight')));assert.equal(JSON.stringify(state),before);
assert.throws(()=>P.save(state,proposal,{},args));const saved=P.save(state,proposal,{confirmed:true,notes:'Reviewed'}, {...args,id:'phase'});assert.equal(saved.phasePrograms.length,1);assert.deepEqual(saved.reviewedPrograms,state.reviewedPrograms);assert.deepEqual(saved.workouts,state.workouts);assert.deepEqual(P.validate(JSON.parse(JSON.stringify(saved.phasePrograms))),saved.phasePrograms);
const scheduled=P.schedule(saved,'phase',{...args,now:'2026-09-24T13:00:00.000Z'});assert.equal(scheduled.scheduledSessions.length,21);assert.equal(scheduled.scheduledSessions[0].revisions[0].context.prescription.source.referenceId,'phase');assert.equal(scheduled.scheduledSessions.at(-1).revisions[0].context.role,'deload');assert.throws(()=>P.schedule(scheduled,'phase',args));assert.throws(()=>Review.analyze(scheduled,{...args,programId:'phase',week:1}));
const conflict={...saved,scheduledSessions:scheduled.scheduledSessions.slice(0,1)};assert.throws(()=>P.schedule(conflict,'phase',args));
const edit=fn=>{const c=structuredClone(config);fn(c);return c;};
for(const bad of [edit(c=>c.startDate='2026-09-29'),edit(c=>c.days=[0,0]),edit(c=>c.phases.reverse()),edit(c=>c.phases[0].weeks=0),edit(c=>c.sessionMinutes=30),edit(c=>c.lifts.squat.variation.trainingMaxKg=0),edit(c=>c.lifts.squat.variationEquipmentConfirmed=false),edit(c=>c.lifts.bench.exposures[1].role='primary'),edit(c=>c.lifts.deadlift.exposures[0].day=1),edit(c=>{c.phases[1].weeks=6;c.lifts.squat.stepPct=2.5;})])assert.throws(()=>P.prepare(state,bad,args));
const profile=Profile.current(state.programmingProfiles).context;for(const bad of [{goal:'return'},{goal:'meet'},{goal:'hypertrophy'},{equipment:[]},{avoidedExerciseIds:['ss'],preferredExerciseIds:[]},{availableDays:[0,1,2]},{eventDate:'2026-11-10'}]){
 const modified={...state,programmingProfiles:Profile.save([],{...profile,...bad},{id:'bad',now:'2026-09-23T11:00:00.000Z'})};assert.throws(()=>P.prepare(modified,config,args));}
const changed={...saved,programmingProfiles:Profile.save(saved.programmingProfiles,{...profile,notes:'Changed context'},{id:'changed',now:'2026-09-24T12:30:00.000Z'})};assert.throws(()=>P.save(changed,proposal,{confirmed:true},{...args,now:'2026-09-24T13:00:00.000Z'}));assert.throws(()=>P.schedule(changed,'phase',{...args,now:'2026-09-24T13:00:00.000Z'}));
const broken=structuredClone(saved.phasePrograms);broken[0].sessions[0].exercises[0].sets[0].weight=999;assert.throws(()=>P.validate(broken));const badRoles=structuredClone(saved.phasePrograms);badRoles[0].roleSnapshot=[];assert.throws(()=>P.validate(badRoles));assert.throws(()=>P.validate(null));
const lbs=edit(c=>{c.incrementKg=5*.45359237;c.lifts.squat.trainingMaxKg=365*.45359237;});assert(Math.abs(P.build(lbs).sessions[0].exercises[0].sets[0].weight/.45359237-235)<.02);
const future={...state,workouts:[...state.workouts,{id:'future',date:'2026-09-25',createdAt:'2026-09-25T20:00:00.000Z',exercises:[{exerciseId:'s',sets:[{weight:999,reps:5}]}]}]};assert.deepEqual(P.prepare(future,config,args),proposal);
const coarse=edit(c=>{c.incrementKg=10;c.lifts.squat.trainingMaxKg=30;c.lifts.squat.variation.trainingMaxKg=30;});assert(P.build(coarse).warnings.some(w=>w.includes('tonnage rises more than 20%')));
const sparse={...state,workouts:['2026-09-02','2026-09-09','2026-09-23'].map((date,i)=>({id:'recent-'+i,date,createdAt:date+'T12:00:00.000Z',exercises:[{exerciseId:'s',sets:[{weight:100,reps:5}]}]}))};assert(P.prepare(sparse,config,args).warnings.some(w=>w.includes('first-week sets exceed')));
const replay=structuredClone(sparse),original=structuredClone(replay.workouts[0]);replay.workouts[0].exercises[0].sets=Array.from({length:100},()=>({weight:100,reps:5}));replay.workoutRevisions=[{workoutId:original.id,recordedAt:'2026-09-25T00:00:00.000Z',before:original,after:replay.workouts[0]}];assert.deepEqual(P.prepare(replay,config,args),P.prepare(sparse,config,args));
const migrated=Core.normalizeState({schemaVersion:20,workouts:state.workouts,reviewedPrograms:state.reviewedPrograms});assert.equal(migrated.schemaVersion,21);assert.deepEqual(migrated.phasePrograms,[]);assert.deepEqual(migrated.reviewedPrograms,state.reviewedPrograms);assert.deepEqual(migrated.workouts,state.workouts);
console.log('Phase sequences, independent lifts, formats, variation maxes, constraints, reviews, chronology, kg/lb, backups and migration passed');
