const assert=require('node:assert/strict');
const Outcomes=require('../src/product/phase-outcomes'),Review=require('../src/product/phase-review'),Schedule=require('../src/product/schedule');
const {fixture,args}=require('./fixtures/phase-review');
const base=fixture(),report=Review.analyze(base,args),chosen={squat:'reduce-load',bench:'keep',deadlift:'keep'},approved=Review.apply(base,report,chosen,{confirmed:true,asOf:args.asOf,now:args.now});
const prior=JSON.stringify(approved),asOf='2026-11-08',now='2026-11-08T23:00:00.000Z';
const empty=Outcomes.analyze(approved,{asOf,now});
assert.equal(empty.reviews.length,1);
assert.equal(empty.reviews[0].findings.squat.choice,'reduce-load');
assert.equal(empty.reviews[0].findings.squat.status,'gather-follow-up');
assert.equal(empty.reviews[0].findings.squat.completed,0);
const filled=structuredClone(approved);
const next=filled.phasePrograms[0].sessions.filter(s=>s.phase==='strength');
for(const s of next){
 const record=filled.scheduledSessions.find(r=>r.id==='phase:ph:'+s.key),revision=record.revisions.at(-1),plan=revision.context.prescription;
 filled.workouts.push({id:'follow-'+s.key,date:s.date,createdAt:s.date+'T20:00:00.000Z',sessionIntent:{schedule:{id:record.id,revisionAt:revision.recordedAt},prescription:structuredClone(plan),deviationReason:'none'},exercises:plan.plannedExercises.map(e=>({...e,sets:e.sets.map(set=>({...set,rpe:set.targetRpe}))}))});
}
const done=Outcomes.analyze(filled,{asOf,now});
assert.equal(done.reviews[0].findings.squat.status,'observed-follow-up');
assert.equal(done.reviews[0].findings.squat.matched,6);
assert.equal(done.reviews[0].findings.squat.withinCap,6);
assert.equal(done.reviews[0].findings.bench.matched,9);
assert.equal(done.reviews[0].findings.deadlift.matched,3);
assert(Number.isFinite(done.reviews[0].findings.squat.observedChangePct));
assert.equal(JSON.stringify(approved),prior);
const partial=structuredClone(filled);partial.workouts.pop();
assert.equal(Outcomes.analyze(partial,{asOf,now}).reviews[0].findings.deadlift.status,'gather-follow-up');
const bad=structuredClone(filled),w=bad.workouts.find(w=>w.id==='follow-w4d0');w.exercises[0].sets[0].weight+=10;
const outcome=Outcomes.analyze(bad,{asOf,now});
assert.equal(outcome.reviews[0].findings.squat.status,'gather-follow-up');
assert(outcome.reviews[0].findings.squat.rows.some(r=>r.status==='work-deviated'));
const after=structuredClone(filled),target=after.workouts.find(w=>w.id==='follow-w4d0'),before=structuredClone(target);
target.exercises[0].sets[0].weight+=100;
after.workoutRevisions=[{workoutId:before.id,recordedAt:'2026-11-09T00:00:00.000Z',before,after:target}];
assert.deepEqual(Outcomes.analyze(after,{asOf,now}),done);
const future=structuredClone(filled);future.workouts.push({id:'late',date:'2026-11-09',createdAt:'2026-11-09T20:00:00.000Z',exercises:[]});
assert.deepEqual(Outcomes.analyze(future,{asOf,now}),done);
const changed=structuredClone(filled),record=changed.scheduledSessions.find(r=>r.id==='phase:ph:w4d0');
changed.scheduledSessions=Schedule.change(changed.scheduledSessions,record.id,{date:'2026-10-20',reason:'Moved'},'2026-10-19T08:00:00.000Z');
assert.equal(Outcomes.analyze(changed,{asOf,now}).reviews[0].findings.squat.status,'gather-follow-up');
const gap=Outcomes.analyze(approved,{asOf:'2026-10-18',now:args.now});
assert.equal(gap.reviews[0].findings.squat.completed,0);
assert.throws(()=>Outcomes.analyze(approved,{asOf:'bad',now}));
console.log('Accepted phase decision outcomes tests passed');
