const assert=require('node:assert/strict'),R=require('../src/product/phase-review'),Core=require('../src/core/loadnote-core'),Schedule=require('../src/product/schedule'),{fixture,args}=require('./fixtures/phase-review');
const state=fixture(),snapshot=JSON.stringify(state),report=R.analyze(state,args),choices={squat:'reduce-load',bench:'keep',deadlift:'keep'},options={confirmed:true,asOf:args.asOf,now:args.now};
assert.equal(report.findings.squat.decision,'reduce-load');assert.equal(report.findings.bench.decision,'keep');assert.equal(report.findings.deadlift.decision,'keep');
assert.equal(report.findings.squat.expectedSessions,6);assert.equal(report.findings.bench.completedSessions,9);assert(report.findings.squat.capacity);assert.equal(report.findings.squat.performance.length,9);
assert.equal(report.findings.squat.performance[0].estimatedCapacity,Core.capacityEvidence(report.findings.squat.performance[0].weight,5,8).estimate);
const edits=R.preview(report,choices);assert.equal(edits.length,6);assert(edits.every(e=>e.after.plannedExercises[0].sets[0].weight<e.before.prescription.plannedExercises[0].sets[0].weight));
assert.throws(()=>R.apply(state,report,choices,{...options,confirmed:false}));assert.throws(()=>R.apply(state,report,choices,{...options,lockedSessionIds:[edits[0].id]}));
const next=R.apply(state,report,choices,options);assert.equal(next.phaseReviews.length,1);assert.deepEqual(next.workouts,state.workouts);assert.deepEqual(next.phasePrograms,state.phasePrograms);assert.equal(JSON.stringify(state),snapshot);
assert(next.scheduledSessions.filter(s=>s.revisions.length===2).length===6);next.scheduledSessions.forEach((s,i)=>assert.deepEqual(s.revisions[0],state.scheduledSessions[i].revisions[0]));
assert.deepEqual(R.validate(JSON.parse(JSON.stringify(next.phaseReviews))),next.phaseReviews);assert.throws(()=>R.apply(next,report,choices,options));
const keep={squat:'keep',bench:'keep',deadlift:'keep'};assert.deepEqual(R.apply(state,report,keep,options).scheduledSessions,state.scheduledSessions);
const edit=fn=>{const s=structuredClone(state);fn(s);return s;};
assert.equal(R.analyze(edit(s=>s.workouts.pop()),args).findings.bench.decision,'gather');
assert.equal(R.analyze(edit(s=>s.workouts[0].exercises[0].sets[0].rpe=null),args).findings.squat.decision,'gather');
assert.equal(R.analyze(edit(s=>s.workouts[0].exercises[0].sets[0].rpe=5),args).findings.squat.decision,'gather');
assert.equal(R.analyze(state,{...args,recovery:{}}).findings.squat.decision,'gather');
assert.equal(R.analyze(state,{...args,recovery:{...args.recovery,discomfort:'present'}}).findings.squat.decision,'gather');
assert.throws(()=>R.apply(edit(s=>s.workouts[0].exercises[0].sets[0].rpe=10),report,choices,options),/fresh/);
const fatigue=R.analyze(state,{...args,recovery:{...args.recovery,fatigue:'worse'}});assert.equal(fatigue.findings.bench.decision,'reduce-sets');assert.equal(fatigue.findings.deadlift.decision,'gather');
const fewer=R.apply(state,fatigue,{...keep,bench:'reduce-sets'},options);assert.equal(fewer.scheduledSessions[9].revisions.at(-1).context.prescription.plannedExercises.find(e=>e.exerciseId==='b').sets.length,2);
const missingTarget=edit(s=>s.scheduledSessions.splice(9,1)),missingReport=R.analyze(missingTarget,args);assert.throws(()=>R.apply(missingTarget,missingReport,choices,options),/eligible/);
const manual=edit(s=>{s.scheduledSessions=Schedule.change(s.scheduledSessions,edits[0].id,{date:'2026-10-20',reason:'Manual move'},'2026-10-18T10:00:00.000Z');});assert.throws(()=>R.apply(manual,R.analyze(manual,args),choices,options),/eligible/);
const done=edit(s=>s.workouts.push({id:'future-done',date:'2026-10-19',createdAt:'2026-10-19T20:00:00.000Z',sessionIntent:{schedule:{id:edits[0].id}},exercises:[]}));
assert.deepEqual(R.analyze(done,args),report,'Future workouts cannot leak into historical analysis');assert.throws(()=>R.apply(done,report,choices,options),/completed/);
const replay=edit(s=>{const before=structuredClone(s.workouts[0]);s.workouts[0].exercises[0].sets[0].rpe=10;s.workoutRevisions=[{workoutId:before.id,recordedAt:'2026-10-19T20:00:00.000Z',before,after:s.workouts[0]}];});assert.deepEqual(R.analyze(replay,args),report);
assert.throws(()=>R.analyze(state,{...args,asOf:'2026-10-17'}),/final/);assert.throws(()=>R.analyze(state,{...args,asOf:'2026-09-23',now:'2026-09-23T12:00:00.000Z'}),/known/);
assert.equal(R.analyze(state,{...args,phase:'strength',asOf:'2026-11-08',now:'2026-11-08T22:00:00.000Z'}).findings.squat.decision,'gather');
const bad=structuredClone(next.phaseReviews);bad[0].changes[0].after.context.date='2026-10-01';assert.throws(()=>R.validate(bad));assert.throws(()=>R.validate([...next.phaseReviews,...next.phaseReviews]));assert.throws(()=>R.validate(null));
const old={schemaVersion:21,workouts:state.workouts};assert.deepEqual(Core.normalizeState(old).phaseReviews,[]);assert.equal(Core.normalizeState(old).schemaVersion,22);assert.deepEqual(Core.normalizeState(old).workouts,state.workouts);
assert.deepEqual(R.analyze({...state,unit:'lb'},args),report,'Display unit cannot change kg-based decisions');
assert.equal(R.analyze(edit(s=>delete s.workouts[0].createdAt),args).findings.squat.decision,'gather');
assert.equal(R.analyze(edit(s=>s.workouts.push({...structuredClone(s.workouts[0]),id:'duplicate'})),args).findings.squat.decision,'gather');
assert.equal(R.analyze(edit(s=>s.workouts[0].sessionIntent.deviationReason='fatigue'),args).findings.squat.decision,'gather');
const unknown=edit(s=>s.workouts=[]);assert.equal(R.analyze(unknown,args).findings.squat.capacity,null);assert.equal(R.analyze(unknown,args).findings.squat.averageRpe,null);
const changedProfile=edit(s=>s.programmingProfiles[0].context.notes='Changed context');assert.equal(R.analyze(changedProfile,args).findings.bench.decision,'gather');
const changedRole=edit(s=>s.exerciseRoles.find(r=>r.id==='squat').revisions.at(-1).context.role='close-variation');assert.equal(R.analyze(changedRole,args).findings.squat.decision,'gather');
const corrupt=structuredClone(next.phaseReviews);corrupt[0].changes[0].after.context.prescription.plannedExercises[0].sets[0].weight=999;assert.throws(()=>R.validate(corrupt),/policy/);
const invalidChoice={...keep,bench:'reduce-load'};assert.throws(()=>R.preview(report,invalidChoice),/supported/);
const afterCutoff=edit(s=>{s.scheduledSessions=Schedule.change(s.scheduledSessions,edits[0].id,{date:'2026-10-20',reason:'Later edit'},'2026-10-19T10:00:00.000Z');});assert.deepEqual(R.analyze(afterCutoff,args),report);assert.throws(()=>R.apply(afterCutoff,report,choices,options),/cutoff/);
const easy=fixture({incrementKg:.5});for(const w of easy.workouts)for(const e of w.exercises)if(e.exerciseId==='b')for(const set of e.sets)set.rpe=Math.max(6,set.targetRpe-1);
const progress=R.analyze(easy,args);assert.equal(progress.findings.bench.decision,'progress',progress.findings.bench.reason);assert.equal(progress.findings.squat.decision,'reduce-load');
assert.equal(progress.findings.bench.underCapSessions,progress.findings.bench.expectedSessions);
const upChoices={squat:'keep',bench:'progress',deadlift:'keep'},upEdits=R.preview(progress,upChoices);
assert.equal(upEdits.length,9);assert(upEdits.every(e=>e.after.plannedExercises.find(x=>x.exerciseId==='b').sets.every((set,i)=>set.weight>e.before.prescription.plannedExercises.find(x=>x.exerciseId==='b').sets[i].weight)));
const advanced=R.apply(easy,progress,upChoices,options);assert.equal(advanced.phaseReviews[0].policy,'phase-effort-v2');
assert.deepEqual(advanced.workouts,easy.workouts);assert.deepEqual(advanced.phasePrograms,easy.phasePrograms);
assert.deepEqual(R.validate(JSON.parse(JSON.stringify(advanced.phaseReviews))),advanced.phaseReviews);
assert.throws(()=>R.preview(progress,{...upChoices,squat:'progress'}),/supported/);
const changedEasy=structuredClone(easy);changedEasy.workouts[0].exercises.find(e=>e.exerciseId==='b').sets[0].rpe=10;
assert.notEqual(R.analyze(changedEasy,args).findings.bench.decision,'progress');
const worseEasy=R.analyze(easy,{...args,recovery:{...args.recovery,sleep:'worse'}});assert.notEqual(worseEasy.findings.bench.decision,'progress');
const highIncrement=structuredClone(progress);
highIncrement.basis.program.config.incrementKg=100;
assert.throws(()=>R.preview(highIncrement,upChoices),/increment|ceiling/);
const legacyReview=structuredClone(next.phaseReviews);legacyReview[0].policy='phase-effort-v1';delete legacyReview[0].trainingMaxKg;for(const change of legacyReview[0].changes)change.after.context.reason='Approved accumulation phase review (phase-effort-v1)';
assert.deepEqual(R.validate(legacyReview),legacyReview,'Old accepted reductions remain valid and importable');
const tamperedIncrease=structuredClone(advanced.phaseReviews);tamperedIncrease[0].changes[0].after.context.prescription.plannedExercises[0].sets[0].weight=1000;
assert.throws(()=>R.validate(tamperedIncrease),/policy|ceiling|progression/);
console.log('Phase review evidence, independent choices, future-only revisions, replay, sparse guards and backups passed');
