const assert=require('node:assert/strict');
const T=require('../src/product/phase-transition'),R=require('../src/product/phase-review');
const {fixture,args}=require('./fixtures/phase-review');
const state=fixture(),before=JSON.stringify(state);
const report=R.analyze(state,args),raw=JSON.stringify(report);
const choices={squat:'reduce-load',bench:'keep',deadlift:'keep'};
const outcome=T.assess(report,choices);
assert.equal(outcome.phase,'accumulation');
assert.equal(outcome.nextPhase,'strength');
assert.equal(outcome.firstNextWeek,4);
assert.equal(outcome.sessionRevisions,6);
assert.equal(outcome.findings.squat.choice,'reduce-load');
assert.equal(outcome.findings.squat.nextPhaseWeekAfter.sets,outcome.findings.squat.nextPhaseWeekBefore.sets);
assert(outcome.findings.squat.nextPhaseWeekAfter.tonnageKg<outcome.findings.squat.nextPhaseWeekBefore.tonnageKg);
assert.deepEqual(outcome.findings.bench.nextPhaseWeekAfter,outcome.findings.bench.nextPhaseWeekBefore);
assert.equal(outcome.findings.bench.lastPhaseWeek.exposures,3);
assert.equal(outcome.findings.bench.lastPhaseWeek.sets,9);
assert.equal(outcome.findings.bench.completedSessions,9);
assert.equal(JSON.stringify(state),before);
assert.equal(JSON.stringify(report),raw);
assert.deepEqual(T.assess(R.analyze({...state,unit:'lb'},args),choices),outcome,'internal kg metrics are invariant to display unit');
assert.throws(()=>T.assess(report,{...choices,bench:'add-set'}),/supported/);
const changed=structuredClone(report);
changed.targets.find(t=>t.session?.status==='scheduled').session.status='skipped';
const caution=T.assess(changed,{squat:'keep',bench:'keep',deadlift:'keep'});
assert(Object.values(caution.findings).some(f=>f.warnings.some(w=>/no longer scheduled/.test(w))));
const strength=R.analyze(state,{...args,phase:'strength',asOf:'2026-11-08',now:'2026-11-08T22:00:00.000Z'});
const deload=T.assess(strength,{squat:'keep',bench:'keep',deadlift:'keep'});
assert.equal(deload.nextPhase,'deload');
assert(Object.values(deload.findings).every(f=>f.status==='planned-deload'));
assert.equal(deload.sessionRevisions,0);
const done=R.analyze(state,{...args,phase:'deload',asOf:'2026-11-15',now:'2026-11-15T22:00:00.000Z'});
const ended=T.assess(done,{squat:'keep',bench:'keep',deadlift:'keep'});
assert.equal(ended.nextPhase,null);
assert(Object.values(ended.findings).every(f=>f.status==='sequence-complete'&&f.nextPhaseWeekAfter.sets===0));
const easy=fixture();
for(const w of easy.workouts)for(const e of w.exercises)if(e.exerciseId==='b')for(const set of e.sets)set.rpe=Math.max(6,set.targetRpe-1);
const proposal=R.analyze(easy,args);assert.equal(proposal.findings.bench.decision,'add-set');
const more=T.assess(proposal,{squat:'keep',bench:'add-set',deadlift:'keep'});
assert.equal(more.findings.bench.nextPhaseWeekAfter.sets,more.findings.bench.nextPhaseWeekBefore.sets+3);
assert.equal(more.findings.bench.nextPhaseWeekAfter.exposures,more.findings.bench.nextPhaseWeekBefore.exposures);
console.log('Phase transition projected workload, choices, protected deload, gaps, kg invariance and immutability passed');
