const assert=require('node:assert/strict');
const Workspace=require('../src/product/programming-workspace');
const Profile=require('../src/product/programming-profile');
const {phaseFixture}=require('./fixtures/phase-builder');
const {state}=phaseFixture();
assert.equal(Workspace.weekStartOnOrAfter('2026-10-11'),'2026-10-12');
assert.equal(Workspace.weekStartOnOrAfter('2026-10-12'),'2026-10-12');
assert.equal(Workspace.weeksToEvent('2026-10-12','2026-12-26'),11);
let r=Workspace.route({...state,programmingProfiles:[]},{asOf:'2026-09-29'});assert.equal(r.primaryAction,'profile');
const p=Profile.current(state.programmingProfiles).context;
const returning={...state,programmingProfiles:Profile.save([],{...p,goal:'return',consistency:'returning'},{id:'return',now:'2026-09-28T12:00:00.000Z'})};
r=Workspace.route(returning,{asOf:'2026-09-29'});assert.equal(r.primaryAction,'quick');
const meet={...state,programmingProfiles:Profile.save([],{...p,goal:'meet',eventDate:'2026-12-26'},{id:'meet',now:'2026-09-28T12:00:00.000Z'})};
r=Workspace.route(meet,{asOf:'2026-09-29'});assert.equal(r.primaryAction,'phase-meet');assert.match(r.reason,/not an exact-match requirement/i);
const general={...state,programmingProfiles:Profile.save([],{...p,goal:'general',eventDate:null,consistency:'consistent'},{id:'general',now:'2026-09-28T12:00:00.000Z'})};
r=Workspace.route(general,{asOf:'2026-09-29'});assert.equal(r.primaryAction,'phase');
const hyp={...state,programmingProfiles:Profile.save([],{...p,goal:'hypertrophy'},{id:'hyp',now:'2026-09-28T12:00:00.000Z'})};
r=Workspace.route(hyp,{asOf:'2026-09-29'});assert.equal(r.primaryAction,'adopt');
console.log('v2.68 programming workspace routing and date helper tests passed');