const assert=require('node:assert/strict');
const Planning=require('../src/product/program-planning-decision');
const Phase=require('../src/product/phase-builder');
const {phaseFixture}=require('./fixtures/phase-builder');
const {state,config}=phaseFixture(),args={asOf:'2026-09-24',now:'2026-09-24T12:00:00.000Z'};
const sourceState=Phase.save(state,Phase.prepare(state,config,args),{confirmed:true,notes:'planning source'},{...args,id:'planning-source'}),source=sourceState.phasePrograms[0];
assert.equal(Planning.totalWeeks('2026-10-12','2026-12-26'),11);
let p=Planning.plan(sourceState,source,{meetDate:'2026-12-26',eventType:'mock'},args);
assert.equal(p.status,'ready');assert.equal(p.totalWeeks,14,'fixture starts before October; total weeks must derive from actual source start, not a hard-coded user date');
assert.equal(p.phases.accumulationWeeks+p.phases.strengthWeeks+p.phases.peakWeeks+p.phases.taperWeeks+1,p.totalWeeks);
assert.equal(p.mode,'decisions');assert.match(p.summary,/accumulation/);assert.equal(Planning.validate(structuredClone(p),source,p.config).decisionFingerprint,p.decisionFingerprint);
const shortDate=(()=>{const d=new Date(source.config.startDate+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+5*7+5);return d.toISOString().slice(0,10);})();
const short=Planning.plan(sourceState,source,{meetDate:shortDate,eventType:'mock'},args);assert.equal(short.status,'unsupported-short');assert.match(short.summary,/requires at least 7 weeks/i);
const event11=(()=>{const d=new Date(source.config.startDate+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+10*7+5);return d.toISOString().slice(0,10);})();
p=Planning.plan(sourceState,source,{meetDate:event11,eventType:'mock'},args);assert.equal(p.totalWeeks,11);assert.equal(p.phases.peakWeeks,2);assert.equal(p.phases.taperWeeks,1);assert.equal(p.phases.accumulationWeeks+p.phases.strengthWeeks,7);
const custom=Planning.plan(sourceState,source,{meetDate:event11,eventType:'mock',phaseOverride:{accumulationWeeks:3,strengthWeeks:4,peakWeeks:2,taperWeeks:1}},args);assert.equal(custom.mode,'athlete-customized');assert.deepEqual(custom.phases,{accumulationWeeks:3,strengthWeeks:4,peakWeeks:2,taperWeeks:1,eventWeeks:1});
assert.throws(()=>Planning.plan(sourceState,source,{meetDate:event11,eventType:'mock',phaseOverride:{accumulationWeeks:4,strengthWeeks:4,peakWeeks:2,taperWeeks:1}},args),/add up/);
const evidenceSource=structuredClone(source);evidenceSource.objectiveSnapshot={recommendation:{label:'Rebuild-development block',accumulationWeeks:4,strengthWeeks:2,driver:'rebuild-tolerance',reason:'Frozen transition evidence favors development.'}};
const evidence=Planning.plan(sourceState,evidenceSource,{meetDate:event11,eventType:'mock'},args);assert(evidence.phases.accumulationWeeks>evidence.phases.strengthWeeks);assert.equal(evidence.phaseEvidence.source,'transition-objective');
const before=JSON.stringify(sourceState);Planning.plan(sourceState,source,{meetDate:event11,eventType:'mock'},args);assert.equal(JSON.stringify(sourceState),before,'planning decisions are read-only');
console.log('v2.68 meet-date anchored deterministic program-planning decision tests passed');