const assert = require('assert');
const Release = require('../src/release');
const a = Release.assess({schemaVersion:11, workouts:[], programs:[]});
assert.strictEqual(a.version, require('../package.json').version);
assert.strictEqual(a.ready, true);
assert.strictEqual(a.completed, a.total);
const b = Release.assess({schemaVersion:8, workouts:[]});
assert.strictEqual(b.ready, false);
assert.ok(b.checks.some(c=>c.id==='migration' && !c.ok));
console.log('release tests passed');
