const assert = require('assert');
const Release = require('../src/release');
const a = Release.assess({schemaVersion:25, workouts:[], programs:[],transitionSnapshots:[],adoptedPrograms:[],exerciseCatalog:[],workoutRevisions:[],exerciseRoles:[],prescriptionVersion:1,decisionEvents:[]});
assert.strictEqual(a.version, require('../package.json').version);
assert.strictEqual(a.ready, true);
assert.strictEqual(a.completed, a.total);
const b = Release.assess({schemaVersion:8, workouts:[]});
assert.strictEqual(b.ready, false);
assert.ok(b.checks.some(c=>c.id==='migration' && !c.ok));
console.log('release tests passed');

const fs=require('node:fs'),path=require('node:path');
const read=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8');
const pkg=require('../package.json'),lock=require('../package-lock.json');
assert.equal(lock.version,pkg.version);
assert.equal(lock.packages[''].version,pkg.version);
assert(read('README.md').includes('**v'+pkg.version+' · Development build.**'));
assert(read('README.md').includes('Current schema: **'+require('../src/core/loadnote-core').SCHEMA_VERSION+'**'));
assert(read('README.md').includes('node scripts/serve.js'));
assert(!read('README.md').includes('npm run serve'));
assert(!read('docs/architecture.md').includes('The v2 decision engine remains disabled'));
assert(read('CHANGELOG.md').startsWith('# v'+pkg.version+' —'));
assert(read('sw.js').includes("const CACHE = 'loadnote-v"+pkg.version+"';"));
assert(read('src/product/navigation.js').includes('Loadnote web v'+pkg.version+' ·'));
assert.equal(require('../src/core/loadnote-core').RELEASE_VERSION,pkg.version);
assert.equal(pkg.scripts['build:assets'],'node scripts/build-assets.js');
assert(read('docs/mobile-release.md').includes('npm run sync:www'));
for(const stale of ['npm run sync:web','npm run add:ios','npm run add:android'])assert(!read('docs/mobile-release.md').includes(stale));
console.log('release documentation, lockfile, footer and packaging-command consistency passed');
