const assert=require('node:assert/strict'),Guidance=require('../src/product/set-guidance');
const plan=[{weight:100,reps:5,targetRpe:8},{weight:100,reps:5,targetRpe:8},{weight:100,reps:5,targetRpe:8}];
const empty=()=>Array.from({length:3},()=>({done:false,reps:5,weightKg:100,rpe:''}));
assert.deepEqual(Guidance.evaluate(plan,empty()).status,'awaiting-set');
const within=empty();within[0]={done:true,reps:5,weightKg:100,rpe:'7.5'};
assert.equal(Guidance.evaluate(plan,within).status,'within-cap');assert.equal(Guidance.evaluate(plan,within).nextIndex,1);
assert.equal(Guidance.evaluate(plan,within).nextTarget.weight,100);
const above=structuredClone(within);above[0].rpe='9';
assert.equal(Guidance.evaluate(plan,above).status,'above-cap');assert.equal(Guidance.evaluate(plan,above).rpeDifference,1);
const missing=structuredClone(within);missing[0].rpe='';
assert.equal(Guidance.evaluate(plan,missing).status,'rpe-missing');
const changed=structuredClone(within);changed[0].weightKg=102.5;
assert.equal(Guidance.evaluate(plan,changed).status,'work-different');
const reps=structuredClone(within);reps[0].reps=4;
assert.equal(Guidance.evaluate(plan,reps).status,'work-different');
const later=structuredClone(above);later[1]={done:true,reps:5,weightKg:100,rpe:'7'};
assert.equal(Guidance.evaluate(plan,later).status,'within-cap','Most recently checked set controls in-session guidance');
const none=Guidance.evaluate([], [{done:true,reps:5,weightKg:100,rpe:'8'}]);
assert.equal(none.status,'no-comparable-target');
assert.deepEqual(Guidance.evaluate(plan,empty()),Guidance.evaluate(plan,empty()),'Deterministic output');
assert.throws(()=>Guidance.evaluate(null,[]),/planned/);
console.log('Set-by-set read-only effort guidance tests passed');
