const assert=require('node:assert/strict'),B=require('../src/product/training-blocks'),Core=require('../src/core/loadnote-core');
const config={name:'Return to Powerlifting',startDate:'2026-06-10',endDate:'2026-07-21',blockType:'return-reentry',primaryGoal:'Rebuild strength and work capacity',loadStrategy:'conservative',progressionIntent:'return-ramp',trainingMaxes:[{exercise:'Squat',kg:365/2.2046226218,observedOn:'2026-06-10'}],known1RMs:[{exercise:'Squat',kg:446/2.2046226218,observedOn:'2026-06-01'}]};
let records=B.upsert([],config,{now:'2026-09-10T00:00:00.000Z'});const id=records[0].id;
assert.equal(B.list(records)[0].name,config.name);assert.equal(B.at(records,'2026-07-01'),null);
assert.equal(B.at(records,'2026-07-01',{retrospective:true}).id,id);
assert.equal(B.at(records,'2026-07-01',{knownAt:'2026-12-01T00:00:00.000Z'}),null);
assert.notEqual(B.list(records)[0].trainingMaxes[0].kg,B.list(records)[0].known1RMs[0].kg);
const updated=B.upsert(records,{...config,name:'Corrected'},{id,now:'2026-09-11T00:00:00.000Z'});
assert.equal(B.list(updated,'2026-09-10T12:00:00.000Z')[0].name,config.name);
assert.equal(B.list(updated)[0].name,'Corrected');assert.equal(B.list(records)[0].name,config.name);
const deleted=B.remove(updated,id,'2026-09-12T00:00:00.000Z');assert.equal(B.list(deleted).length,0);assert.equal(B.list(deleted,'2026-09-11T12:00:00.000Z').length,1);
assert.deepEqual(B.validate(JSON.parse(JSON.stringify(deleted))),deleted);
assert.throws(()=>B.upsert(records,{...config,name:'Overlap'},{now:'2026-09-11T00:00:00.000Z'}),/overlap/);
records=B.upsert(records,{...config,name:'Strength',startDate:'2026-07-22',endDate:null,blockType:'strength'},{now:'2026-09-11T00:00:00.000Z'});
assert.equal(B.at(records,'2026-07-22',{retrospective:true}).name,'Strength');
assert.throws(()=>B.upsert(records,{...config,startDate:'2026-07-21'},{now:'2026-09-12T00:00:00.000Z'}));
assert.throws(()=>B.context({...config,startDate:'2026-02-30'}));assert.throws(()=>B.validate({}));
assert.throws(()=>B.context({...config,known1RMs:[{exercise:'Squat',kg:-1,observedOn:'2026-06-01'}]}));
assert.throws(()=>B.validate([...records,records[0]]));
assert.equal(B.context({name:'Minimal',startDate:'2026-01-01'}).loadStrategy,'unknown');
assert.equal(B.context({...config,blockType:'future-type'}).blockType,'future-type');
const workouts=[0,7,14].map((d,i)=>({id:String(i),date:`2026-06-${String(10+d).padStart(2,'0')}`,exercises:[{name:'Squat',sets:[{weight:140+i*10,reps:5,rpe:6}]}]}));
const snapshot=JSON.stringify(workouts);const a=B.analyze(records,workouts,id,{asOf:'2026-07-21',retrospective:true});
assert.equal(JSON.stringify(workouts),snapshot);assert.equal(a.workoutCount,3);assert.equal(a.adherence,null);assert.equal(a.exercises[0].prescriptionTrend,null);assert.match(a.interpretation,/not equivalent/);
assert.equal(a.exercises[0].estimatedCapacityTrend.end,Core.estimated1RM(160,5,6));
const harder=structuredClone(workouts);harder[2].exercises[0].sets[0].rpe=9.5;
assert(B.analyze(records,harder,id,{asOf:'2026-07-21',retrospective:true}).exercises[0].estimatedCapacityTrend.percent<a.exercises[0].estimatedCapacityTrend.percent);
assert.equal(B.analyze(records,workouts,id,{asOf:'2026-06-17',retrospective:true}).exercises[0].estimatedCapacityTrend,null);
const future={date:'2026-12-01',exercises:[{name:'Squat',sets:[{weight:999,reps:5,rpe:6}]}]};
assert.deepEqual(B.analyze(records,[...workouts,future],id,{asOf:'2026-07-21',retrospective:true}),a);
const noRPE=structuredClone(workouts);noRPE.forEach(w=>delete w.exercises[0].sets[0].rpe);assert.equal(B.analyze(records,noRPE,id,{asOf:'2026-07-21',retrospective:true}).exercises[0].estimatedCapacityTrend,null);
const old={schemaVersion:10,workouts,prs:[{id:'pr',weight:150}]};const migrated=Core.normalizeState(old,{});assert.equal(migrated.schemaVersion,11);assert.deepEqual(migrated.trainingBlocks,[]);assert.deepEqual(migrated.workouts,workouts);assert.deepEqual(migrated.prs,old.prs);
assert.deepEqual(Core.normalizeState({...old,trainingBlocks:records},{}).trainingBlocks,records);
console.log('Training block CRUD, timelines, sparse estimates, import and migration passed');
