const assert=require('node:assert/strict');
const Review=require('../src/product/training-review'),Core=require('../src/core/loadnote-core'),Blocks=require('../src/product/training-blocks'),Intent=require('../src/product/session-intent'),Schedule=require('../src/product/schedule');
const at=d=>d+'T18:00:00.000Z';
const workout=(id,date,weight,rpe=6)=>{
 const exercises=[{name:'Squat',exerciseId:'sq',type:'strength',sets:[{weight,reps:5,rpe}]}];
 return {id,date,createdAt:at(date),exercises,sessionIntent:Intent.context({prescription:Intent.createPrescription(exercises,{type:'manual'},date+'T10:00:00.000Z')})};
};
const context={name:'Return to Powerlifting',startDate:'2026-06-10',endDate:'2026-09-08',blockType:'return-reentry',loadStrategy:'conservative',progressionIntent:'return-ramp',trainingMaxes:[{exercise:'Squat',kg:165.56,observedOn:'2026-06-10'}],known1RMs:[{exercise:'Squat',kg:202.3,observedOn:'2026-06-10'}]};
const state={workouts:[workout('a','2026-06-10',142.88),workout('b','2026-07-10',154.22),workout('c','2026-08-10',165.56,9.5)],trainingBlocks:Blocks.upsert([],context,{now:at('2026-09-01')})};
const before=JSON.stringify(state),options={asOf:'2026-08-20',weeks:12};
const r=Review.review(state,options),e=r.exercises[0];
assert.equal(JSON.stringify(state),before,'review is nonmutating');
assert.equal(r.decisionAllowed,false);assert.match(r.interpretation,/not equivalent/);
assert.equal(e.prescriptionTrend.days,3);assert.equal(e.estimatedCapacityTrend.days,3);
assert.notEqual(e.prescriptionTrend.percent,e.estimatedCapacityTrend.percent);
assert.equal(e.estimatedCapacityTrend.end,Core.estimated1RM(165.56,5,9.5));
assert.notEqual(e.estimatedCapacityTrend.end,165.56);assert.notEqual(e.estimatedCapacityTrend.end,202.3);
assert.equal(e.evidence[0].workoutId,'a');assert.equal(e.evidence[2].actualSets[0].rpe,9.5);
assert.equal(Review.review({...state,unit:'lb'},options).exercises[0].estimatedCapacityTrend.end,e.estimatedCapacityTrend.end);
const equalEffort=JSON.parse(JSON.stringify(state));equalEffort.workouts[2].exercises[0].sets[0].rpe=6;
assert.ok(Review.review(equalEffort,options).exercises[0].estimatedCapacityTrend.end>e.estimatedCapacityTrend.end);
const sparse={...state,workouts:state.workouts.slice(0,2)};
assert.equal(Review.review(sparse,options).exercises[0].estimatedCapacityTrend,null);
const missing=JSON.parse(JSON.stringify(state));
for(const w of missing.workouts){delete w.sessionIntent;delete w.exercises[0].sets[0].rpe;}
const m=Review.review(missing,options).exercises[0];
assert.equal(m.prescriptionTrend,null);assert.equal(m.estimatedCapacityTrend,null);assert.equal(m.usableSets,0);assert.ok(m.loggedLoadTrend);
const future={...state,workouts:[...state.workouts,workout('future','2026-08-21',500)]};
assert.deepEqual(Review.review(future,options).exercises,r.exercises);
const old=workout('a','2026-06-10',100),edited=workout('a','2026-06-10',200);
const replay={workouts:[edited],workoutRevisions:[{workoutId:'a',recordedAt:at('2026-09-01'),before:old,after:edited}]};
assert.equal(Review.review(replay,{...options,retrospective:false}).exercises[0].evidence[0].actualSets[0].weight,100);
assert.equal(Review.review(replay,options).exercises[0].evidence[0].actualSets[0].weight,200);
const deleted={workouts:[],workoutRevisions:[{workoutId:'a',recordedAt:at('2026-09-01'),before:old,after:null}]};
assert.equal(Review.review(deleted,{...options,retrospective:false}).workoutCount,1);
assert.equal(Review.review(state,{...options,retrospective:false}).blocks.length,0,'future block context is withheld');
const late={...state,workouts:[workout('late','2026-06-10',100)]};
late.workouts[0].createdAt=at('2026-09-01');
assert.equal(Review.review(late,{...options,retrospective:false}).workoutCount,0);
const latePlan={workouts:[workout('p','2026-06-10',100)]};
latePlan.workouts[0].sessionIntent.prescription.capturedAt=at('2026-09-01');
assert.equal(Review.review(latePlan,{...options,retrospective:false}).exercises[0].evidence[0].plannedSets.length,0);
assert.equal(Review.review(latePlan,options).exercises[0].evidence[0].retrospectivePlan,true);
const legacy={workouts:[{...old,createdAt:undefined}]};
assert.match(Review.review(legacy,{...options,retrospective:false}).warnings.join(' '),/Legacy/);
let blocks=Blocks.upsert([],{...context,endDate:'2026-06-30'},{now:at('2026-06-01')});
blocks=Blocks.upsert(blocks,{...context,name:'Strength',startDate:'2026-07-01',blockType:'strength',loadStrategy:'performance-based',progressionIntent:'performance'},{now:at('2026-06-02')});
const mixed=Review.review({...state,trainingBlocks:blocks},options);
assert.equal(mixed.exercises[0].estimatedCapacityTrend,null);assert.match(mixed.exercises[0].reasons.join(' '),/context changes/);
const variation=workout('v','2026-07-20',300);variation.exercises[0].exerciseId='ssb';variation.exercises[0].name='SSB';delete variation.sessionIntent;
assert.equal(Review.review({...state,workouts:[...state.workouts,variation]},options).exercises.length,2);
const plan=Intent.createPrescription(old.exercises,{type:'manual'},at('2026-08-01'));
let scheduledSessions=[];
for(const [i,d] of ['2026-08-17','2026-08-18','2026-08-19'].entries())scheduledSessions=Schedule.create(scheduledSessions,{date:d,name:'Session '+i,prescription:plan},{id:'s'+i,now:at('2026-08-16')});
scheduledSessions=Schedule.change(scheduledSessions,'s2',{date:'2026-08-25',reason:'Travel'},at('2026-08-19'));
const done=[0,1].map(i=>{const w=workout('done'+i,'2026-08-'+(17+i),100);w.sessionIntent.schedule={id:'s'+i,revisionAt:at('2026-08-16')};return w;});
const week=Review.review({workouts:done,scheduledSessions},options).week;
assert.equal(week.counts.completed,2);assert.equal(week.counts.skipped,0);assert.equal(week.adherence,100);assert.equal(week.resolved,2);
assert.equal(Review.review({workouts:[],scheduledSessions},options).week.counts.unconfirmed,2);
assert.equal(Review.review({workouts:[]},options).week.adherence,null);
assert.deepEqual(Review.review(JSON.parse(JSON.stringify(state)),options),r,'backup roundtrip preserves review');
assert.equal(Review.review(Core.normalizeState({schemaVersion:14,workouts:[]},{}),options).workoutCount,0);
assert.throws(()=>Review.review(state,{asOf:'bad'}));assert.throws(()=>Review.review(state,{...options,weeks:2}));
console.log('Training Review separation, evidence, sparse guards, revisions, scheduling and units passed');
