const assert=require('node:assert/strict');
const Targets=require('../src/product/training-targets'),Review=require('../src/product/phase-review'),Schedule=require('../src/product/schedule');
const {fixture,args}=require('./fixtures/phase-review');
const base=fixture(),before=JSON.stringify(base);
const id='phase:ph:w4d0';
const first=Targets.inspect(base,id,{asOf:'2026-10-18',now:'2026-10-18T22:00:00.000Z'});
assert.equal(first.id,id);
assert.equal(first.exercises.find(e=>e.exerciseId==='s').previous.date,'2026-10-16');
assert.equal(first.phaseReview,null);
const review=Review.analyze(base,args),next=Review.apply(base,review,{squat:'reduce-load',bench:'keep',deadlift:'keep'},{confirmed:true,asOf:args.asOf,now:args.now});
const revised=Targets.inspect(next,id,{asOf:'2026-10-18',now:args.now});
assert.equal(revised.phaseReview.choices[0].lift,'squat');
assert.equal(revised.phaseReview.choices[0].choice,'reduce-load');
assert.equal(revised.exercises.find(e=>e.exerciseId==='s').approvedChange.beforeSets,3);
assert(revised.exercises.find(e=>e.exerciseId==='s').approvedChange.beforeFirstWeightKg>revised.exercises.find(e=>e.exerciseId==='s').approvedChange.afterFirstWeightKg);
assert.equal(revised.exercises.find(e=>e.exerciseId==='b').approvedChange,null);
assert.equal(revised.exercises.find(e=>e.exerciseId==='s').previous.workoutId,'workout-phase:ph:w3d2');
const old=Targets.inspect(next,id,{asOf:'2026-10-18',now:'2026-10-18T21:00:00.000Z'});
assert.equal(old.phaseReview,null,'Later accepted changes must not leak into earlier knowledge cutoffs');
const newer=structuredClone(next);
newer.workouts.push({id:'future',date:'2026-10-17',createdAt:'2026-10-19T00:00:00.000Z',exercises:[{exerciseId:'s',name:'Competition Squat',type:'strength',sets:[{weight:999,reps:5,rpe:10}]}]});
assert.deepEqual(Targets.inspect(newer,id,{asOf:'2026-10-18',now:args.now}),revised);
const change=structuredClone(next),previous=structuredClone(change.workouts.at(-1));
change.workouts.at(-1).exercises[0].sets[0].weight=999;
change.workoutRevisions=[{workoutId:previous.id,recordedAt:'2026-10-19T00:00:00.000Z',before:previous,after:change.workouts.at(-1)}];
assert.deepEqual(Targets.inspect(change,id,{asOf:'2026-10-18',now:args.now}),revised);
assert.throws(()=>Targets.inspect(next,'not-scheduled',{asOf:'2026-10-18',now:args.now}),/unavailable/);
assert.throws(()=>Targets.inspect(next,id,{asOf:'bad',now:args.now}),/valid/);
assert.equal(JSON.stringify(base),before);
assert.deepEqual(next.phasePrograms,base.phasePrograms);
console.log('Read-only scheduled training targets, previous work and approved decision provenance tests passed');
