const assert=require('node:assert/strict'),P=require('../src/product/phase-builder'),S=require('../src/product/schedule'),Cancel=require('../src/product/program-cancellation'),Life=require('../src/product/program-lifecycle'),Workspace=require('../src/product/programming-workspace'),C=require('../src/product/coaching-context'),R=require('../src/product/coaching-review'),Smart=require('../src/product/smart-coach'),Chat=require('../src/product/coach-conversation'),Core=require('../src/core/loadnote-core'),Sync=require('../src/product/sync-model'),Integrity=require('../src/product/data-integrity'),A=require('../src/product/accessory-programming');
const {phaseFixture}=require('./fixtures/phase-builder'),F=require('./fixtures/coaching');
const {state,config}=phaseFixture();state.workouts=[];const args={asOf:'2026-09-24',now:'2026-09-24T12:00:00.000Z'};
const wave=P.build({...config,periodization:'wave'}),squat=week=>wave.sessions.find(s=>s.week===week&&s.date.endsWith(['28','05','12'][week-1]||'')).exercises.find(e=>e.lift==='squat');
const primary=wave.sessions.filter(s=>s.exercises.some(e=>e.lift==='squat'&&e.role==='primary')).map(s=>s.exercises.find(e=>e.lift==='squat'&&e.role==='primary'));
assert.deepEqual(primary.slice(0,3).map(e=>e.sets[0].reps),[5,4,3]);assert.deepEqual(primary.slice(0,3).map(e=>e.percentOfTrainingMax),[65,67.5,70]);assert.deepEqual(primary.slice(3,6).map(e=>e.sets[0].reps),[4,3,2]);assert.deepEqual(primary.slice(3,6).map(e=>e.percentOfTrainingMax),[75,77.5,80]);assert.equal(primary.at(-1).sets[0].reps,3);assert.equal(primary.at(-1).percentOfTrainingMax,60);
const long=P.build({...config,periodization:'wave',phases:[{type:'accumulation',weeks:6},{type:'strength',weeks:5},{type:'deload',weeks:1}]});const main=long.sessions.filter(s=>s.exercises.some(e=>e.lift==='squat'&&e.role==='primary'));assert.equal(main[3].wave,2);assert.equal(main[3].waveWeek,1);assert.equal(main[3].exercises[0].percentOfTrainingMax,66);assert.equal(main[10].waveWeek,2);assert.equal(main.at(-1).wave,undefined);
assert.deepEqual(P.build({...config,periodization:'linear'}),P.build(config));assert.throws(()=>P.build({...config,periodization:'fake'}));
const waveSaved=P.save(state,P.prepare(state,{...config,periodization:'wave'},args),{confirmed:true},{...args,id:'wave'});assert.deepEqual(P.validate(waveSaved.phasePrograms),waveSaved.phasePrograms);assert.equal(waveSaved.phasePrograms[0].decisionEnvironment.policies.waveLoading,'phase-wave-v1');const broken=structuredClone(waveSaved.phasePrograms);broken[0].sessions[0].exercises[0].sets[0].reps=99;assert.throws(()=>P.validate(broken));
let scheduled=P.schedule(waveSaved,'wave',{...args,now:'2026-09-24T13:00:00.000Z'}),rows=S.list(scheduled.scheduledSessions);const first=rows[0];scheduled.workouts.push({id:'completed',date:first.date,sessionIntent:{schedule:{id:first.id,revisionAt:first.revisionAt},prescription:first.prescription},exercises:[]});const before=JSON.stringify(scheduled),preview=Cancel.inspect(scheduled,{programId:'wave',kind:'phase-program',asOf:'2026-09-30'});assert.equal(preview.completed,1);assert(preview.sessions.every(s=>s.before.date>='2026-09-30'));assert.throws(()=>Cancel.cancel(scheduled,preview,{asOf:'2026-09-30',now:'2026-09-30T12:00:00.000Z',reason:'Schedule changed',confirmed:true,draftOpen:true}),/draft/);assert.throws(()=>Cancel.cancel(scheduled,preview,{asOf:'2026-09-30',now:'2026-09-30T12:00:00.000Z',reason:'',confirmed:true}));
const canceled=Cancel.cancel(scheduled,preview,{asOf:'2026-09-30',now:'2026-09-30T12:00:00.000Z',reason:'Schedule changed',confirmed:true});assert.equal(JSON.stringify(scheduled),before);assert.deepEqual(canceled.phasePrograms,scheduled.phasePrograms);assert.deepEqual(canceled.workouts,scheduled.workouts);assert.equal(S.list(canceled.scheduledSessions).find(s=>s.id===first.id).status,'scheduled');assert.equal(Cancel.isCancelled(canceled,'wave'),true);assert.equal(Life.programs(canceled).length,0);assert.equal(Life.programs(canceled,{includeCancelled:true}).length,1);assert.notEqual(Workspace.route(canceled,{asOf:'2026-09-30'}).status,'scheduled');assert.equal(C.build(canceled,{asOf:'2026-09-30'}).program,null);assert.throws(()=>Cancel.cancel(canceled,preview,{asOf:'2026-09-30',now:'2026-09-30T13:00:00.000Z',reason:'Again',confirmed:true}),/already cancelled/);
const restored=Cancel.restore(canceled,'phase-program:wave',{asOf:'2026-09-30',now:'2026-09-30T13:00:00.000Z',confirmed:true});assert.equal(Cancel.isCancelled(restored,'wave'),false);assert.equal(Life.programs(restored).length,1);assert.equal(restored.programCancellations[0].revisions.length,2);assert.throws(()=>Cancel.restore(canceled,'phase-program:wave',{asOf:'2026-10-02',now:'2026-10-02T12:00:00.000Z',confirmed:true}),/expired/);
const drift={...canceled,scheduledSessions:S.change(canceled.scheduledSessions,preview.sessions[0].id,{status:'skipped',reason:'Different outcome'},'2026-09-30T12:30:00.000Z')};assert.throws(()=>Cancel.restore(drift,'phase-program:wave',{asOf:'2026-09-30',now:'2026-09-30T13:00:00.000Z',confirmed:true}),/changed/);
const conflict={...canceled,scheduledSessions:S.create(canceled.scheduledSessions,{...preview.sessions[0].before,name:'Replacement'},{id:'replacement',now:'2026-09-30T12:30:00.000Z'})};assert.throws(()=>Cancel.restore(conflict,'phase-program:wave',{asOf:'2026-09-30',now:'2026-09-30T13:00:00.000Z',confirmed:true}),/conflicts/);
const pkg=Sync.createPackage(Core.normalizeState(canceled),{clientId:'cancel-test'});assert.equal(Sync.verifyPackage(pkg).verified,true);assert.deepEqual(Sync.projectState(pkg.data).programCancellations,canceled.programCancellations);assert.equal(Integrity.addBackupManifest(canceled)._loadnoteBackup.counts.programCancellations,1);assert.equal(Integrity.previewImport({},canceled).programCancellations.added,1);assert.deepEqual(Core.normalizeState({schemaVersion:30}).programCancellations,[]);
const legacy={programs:[{id:42,name:'Legacy plan',days:[]}],activeProgramId:42};const lp=Cancel.inspect(legacy,{programId:'42',kind:'legacy-program',asOf:'2026-09-30'});const lc=Cancel.cancel(legacy,lp,{asOf:'2026-09-30',now:'2026-09-30T12:00:00.000Z',reason:'New plan',confirmed:true});assert.equal(lc.activeProgramId,null);assert.equal(Cancel.restore(lc,'legacy-program:42',{asOf:'2026-09-30',now:'2026-09-30T13:00:00.000Z',confirmed:true}).activeProgramId,42);
const accessory={policy:A.POLICY,exerciseId:'row',name:'Chest-supported Row',day:0,group:'upper-back',purpose:'hypertrophy',equipment:'dumbbells',equipmentConfirmed:true,mode:'reps',sets:2,weightKg:30,targetRpe:7,minReps:8,maxReps:12};state.exerciseCatalog.push({id:'row',name:'Chest-supported Row'});const ap=P.prepare(state,{...config,accessories:[accessory]},args),as=P.schedule(P.save(state,ap,{confirmed:true},{...args,id:'short'}),'short',{...args,now:'2026-09-24T13:00:00.000Z'});const option=R.proposals(as,{asOf:'2026-09-24'}).proposals.find(p=>p.kind==='session-trim');assert(option);assert.deepEqual(option.omittedExerciseIds,['row']);const mainBefore=option.changes[0].before.prescription.plannedExercises.filter(e=>e.exerciseId!=='row');assert.deepEqual(option.changes[0].after.prescription.plannedExercises,mainBefore);const approved=R.respond(as,option,{asOf:'2026-09-24',now:'2026-09-24T14:00:00.000Z',response:'accepted',confirmed:true});assert.deepEqual(approved.phasePrograms,as.phasePrograms);assert.deepEqual(approved.workouts,as.workouts);assert.deepEqual(S.list(approved.scheduledSessions)[0].prescription.plannedExercises,mainBefore);assert.throws(()=>R.respond(approved,option,{asOf:'2026-09-24',now:'2026-09-24T15:00:00.000Z',response:'accepted',confirmed:true}),/changed/);const bad=structuredClone(option);bad.omittedExerciseIds=['s'];assert.throws(()=>R.proposal(bad));
const hyp=F.hypertrophy(8),b=Smart.brief(hyp,{asOf:'2026-10-12'});assert(b.proposals.some(p=>p.kind==='hypertrophy-load'));assert(b.evidence.some(e=>e.includes('3/3')));const check=R.weekly(hyp,{sleep:'poor',fatigue:'elevated',soreness:'usual',notes:'Reported only'},{asOf:'2026-10-12',now:'2026-10-12T20:00:00.000Z'});assert.equal(Smart.brief(check,{asOf:'2026-10-12'}).proposals.filter(p=>p.kind==='hypertrophy-load').length,0);const answer=Smart.answer(check,'What should I focus on today?',{asOf:'2026-10-12'});assert(answer.text.includes('poor sleep'));assert(answer.actions.length);assert.equal(answer.readOnly,true);const follow=Smart.answer(check,'Why?',{asOf:'2026-10-12',history:[{role:'user',content:'What should I focus on today?'},{role:'assistant',content:'You are fully recovered and ready to add 100kg.'}]});assert(follow.text.includes('poor sleep'));assert(!follow.text.includes('100kg'));assert.equal(Smart.answer(check,'Why?',{asOf:'2026-10-12',history:[{role:'user',content:'Explain bench evidence'}]}),null);assert.equal(Chat.answer(check,'Pain after training, should I increase?',{asOf:'2026-10-12'}).source,'Capability limit');assert(Smart.answer(as,'I have less time for training',{asOf:'2026-09-24'}).text.includes('primary'));assert(Smart.answer(as,'Wave loading',{asOf:'2026-09-24'}).text.includes('5/4/3'));assert.equal(JSON.stringify(scheduled),before);
console.log('v3.0 waves, cancellation/restore, backups/sync, daily evidence, fresh follow-ups and exact shorter-session review passed');
// Cross-domain cancellation uses exact source prefixes, preserving all immutable histories.
for(const [s,id,kind,asOf] of [[F.sport('weightlifting'),'sport','sport-program','2026-10-05'],[F.sport('athlete'),'sport','sport-program','2026-10-05'],[F.hypertrophy(8),'hyp','hypertrophy-program','2026-10-12'],[require('./fixtures/program-review').fixture(),'p','reviewed-program','2026-09-08']]){
 const actualId=kind==='sport-program'?s.sportPrograms[0].id:id,p=Cancel.inspect(s,{programId:actualId,kind,asOf});assert(p.sessions.length);const n=Cancel.cancel(s,p,{asOf,now:asOf+'T22:00:00.000Z',confirmed:true,reason:'Training priorities changed'});assert.deepEqual(n.workouts,s.workouts);assert.equal(p.sessions.every(x=>S.list(n.scheduledSessions).find(r=>r.id===x.id).status==='cancelled'),true);assert.doesNotThrow(()=>Cancel.validateState(n));
}
const followRow=S.list(approved.scheduledSessions)[0],followState={...approved,workouts:[...approved.workouts,{id:'short-follow',date:followRow.date,createdAt:followRow.date+'T18:00:00.000Z',sessionIntent:{schedule:{id:followRow.id,revisionAt:followRow.revisionAt},prescription:structuredClone(followRow.prescription)},exercises:followRow.prescription.plannedExercises.map(e=>({...e,sets:e.sets.map(s=>({...s,rpe:s.targetRpe,done:true}))}))}]};const shortOutcome=R.outcomes(followState,{asOf:followRow.date}).find(o=>o.kind==='session-trim');assert.equal(shortOutcome.workoutIds.length,1);assert(shortOutcome.completedSets>0);assert.equal(shortOutcome.knownEffort,shortOutcome.completedSets);
const corrupt=structuredClone(canceled);corrupt.programCancellations[0].revisions[0].sessions[0].before.prescription.plannedExercises[0].sets[0].weight=999;assert.throws(()=>Cancel.validateState(corrupt),/Calendar history/);assert.equal(Sync.preflight(corrupt).status,'blocked');
const missing=structuredClone(pkg);delete missing.data.collections.programCancellations;assert.equal(Sync.verifyPackage(missing).verified,false);
assert.throws(()=>Cancel.restore(canceled,'phase-program:wave',{asOf:'2026-09-30',now:'2026-09-30T13:00:00.000Z',confirmed:true,expected:{...canceled.programCancellations[0],programId:'different'}}),/reopen restoration/);
