const assert=require('node:assert/strict'),W=require('../src/product/weekly-coaching'),F=require('../src/product/primary-follow-up'),C=require('../src/product/coach-conversation'),Review=require('../src/product/cycle-review'),S=require('../src/product/schedule'),AI=require('../src/product/local-coach-ai'),{fixture,args,keep,logWeek}=require('./fixtures/weekly-coaching');
const state=fixture(),before=JSON.stringify(state),r=W.inspect(state,args);
assert.equal(r.status,'ready');assert.equal(r.week,1);assert.equal(r.groups.find(g=>g.key==='squat').status,'review');assert.equal(r.groups.find(g=>g.key==='bench').status,'maintain');assert.equal(r.proposal.changes.length,2);assert(r.proposal.changes.every(c=>c.after.context.date>args.asOf));assert.equal(JSON.stringify(state),before);
const report=Review.analyze(state,{...args,cycleId:'weekly',week:1}),changes=Review.previewTargets(state,report,{...keep,squat:'reduce-one'},args);
assert(changes.every(c=>c.after.context.prescription.plannedExercises.find(e=>e.exerciseId==='s'||e.exerciseId==='ss').sets.length===2));assert.deepEqual(Review.previewTargets(state,report,keep,args),[]);
assert.throws(()=>Review.previewTargets(state,report,{...keep,squat:'reduce-one'},{...args,lockedSessionIds:[changes[0].id]}),/draft/);
let changed=structuredClone(state);changed.workouts[0].exercises[0].sets[0].rpe=null;assert.throws(()=>Review.previewTargets(changed,report,{...keep,squat:'reduce-one'},args),/changed/);
const matched=W.inspect(fixture({above:false}),args);assert(matched.groups.every(g=>g.status==='maintain'));assert.equal(matched.proposal.changes.length,0);
const missing=W.inspect(fixture({logged:false}),args);assert(missing.groups.every(g=>g.status==='gather'));assert.equal(missing.proposal.status,'gather');assert.equal(missing.proposal.changes.length,0);
for(const mutate of [s=>s.workouts[0].exercises[0].sets[0].rpe=null,s=>s.workouts[0].exercises[0].sets[0].reps++,s=>s.workouts[0].exercises[0].sets.pop(),s=>s.workouts.push({...structuredClone(s.workouts[0]),id:'duplicate'}),s=>s.workouts[0].sessionIntent.timing={startedAt:'2026-09-23T10:00:00.000Z'},s=>delete s.workouts[0].createdAt,s=>s.workouts[0].sessionIntent.deviationReason='Changed work']){
 const s=fixture({above:false});mutate(s);assert.equal(W.inspect(s,args).groups.find(g=>g.key==='squat').status,'gather');
}
const skipped=fixture({logged:false});skipped.scheduledSessions=S.change(skipped.scheduledSessions,'meet:weekly:w1d0',{status:'skipped',reason:'Explicit skip'},args.now);assert.equal(W.inspect(skipped,args).groups.find(g=>g.key==='squat').rows[0].status,'skipped');
const phase=require('./fixtures/phase-review').fixture();assert.equal(W.inspect(phase,args).proposal.changes.length,0);assert.match(W.inspect(phase,args).proposal.reason,/completed-phase/);const phaseEnd=W.inspect(phase,require('./fixtures/phase-review').args);assert.equal(phaseEnd.proposal.status,'phase-review');assert.equal(phaseEnd.proposal.route.phase,'accumulation');
const accessory=require('./fixtures/accessory-follow-up').fixture({logged:false});assert(W.inspect(accessory,args).groups.some(g=>g.key==='accessories'));
assert.equal(W.inspect(state,{asOf:'2026-10-01',now:'2026-10-01T12:00:00.000Z'}).status,'waiting');assert.throws(()=>W.inspect(state,{...args,week:2}),/completed/);assert.equal(W.review(state,{...args,now:'broken'}).status,'invalid');assert.equal(W.inspect({},args).status,'empty');assert.equal(W.inspect(state,{asOf:'2026-09-23',now:'2026-09-23T12:00:00.000Z'}).status,'empty');
const overlap=structuredClone(state);const other=structuredClone(overlap.meetCycles[0]);other.id='other';overlap.meetCycles.push(other);assert.equal(W.inspect(overlap,args).status,'ambiguous');assert.equal(W.inspect(overlap,{...args,programId:'weekly',programKind:'meet-cycle'}).status,'ready');
const recap=C.answer(state,'How did this week go, and what should I do next week?',args);assert.equal(recap.source,'Shared coaching · weekly review');assert.equal(C.answer(state,'Why?',{...args,history:[{role:'user',content:'How did this week go?'}]}).text,recap.text);assert.deepEqual(recap.evidence[0],r);assert.equal(AI.eligible('How did this week go?',recap),false);assert.equal(W.answer(state,'My knee hurts, what should I do next week?',args),null);
const approved=fixture({approved:true}),next={asOf:'2026-10-11',now:'2026-10-11T20:00:00.000Z'};assert(F.inspect(approved,args).rows.every(row=>row.status==='waiting'));logWeek(approved,2);
let follow=F.inspect(approved,next);assert.equal(follow.rows.length,2);assert(follow.rows.every(row=>row.status==='within'));assert(follow.rows.every(row=>row.before.sets.length===3&&row.approved.sets.length===2&&row.actual.sets.length===2));assert.equal(W.inspect(approved,next).followups.length,2);
const target=follow.rows[0];approved.scheduledSessions=S.change(approved.scheduledSessions,target.sessionId,{reason:'Later note'},'2026-10-10T20:00:00.000Z');assert.equal(F.inspect(approved,next).rows.find(r=>r.sessionId===target.sessionId).status,'within','A later note does not erase the exact matched approval');
const clone=structuredClone(approved),log=clone.workouts.find(w=>w.sessionIntent.schedule.id===target.sessionId);log.exercises.find(e=>e.exerciseId===target.approved.exerciseId).sets[0].rpe=null;assert.equal(F.inspect(clone,next).rows.find(r=>r.sessionId===target.sessionId).status,'unknown');
const correction=structuredClone(clone);correction.workoutRevisions=[{workoutId:log.id,recordedAt:'2026-10-12T12:00:00.000Z',before:approved.workouts.find(w=>w.id===log.id)}];assert.equal(F.inspect(correction,next).rows.find(r=>r.sessionId===target.sessionId).status,'within');assert.equal(F.inspect(correction,{asOf:'2026-10-12',now:'2026-10-12T20:00:00.000Z'}).rows.find(r=>r.sessionId===target.sessionId).status,'unknown');
const pr=require('../src/product/phase-review'),pa=require('./fixtures/phase-review').args,phaseReport=pr.analyze(phase,pa),phaseApproved=pr.apply(phase,phaseReport,{...keep,squat:'reduce-load'},{...pa,confirmed:true});assert(F.inspect(phaseApproved,pa).rows.length>0);
const po={asOf:'2026-11-08',now:'2026-11-08T20:00:00.000Z'};for(const change of phaseApproved.phaseReviews[0].changes){const plan=change.after.context.prescription;phaseApproved.workouts.push({id:change.id,date:change.after.context.date,createdAt:change.after.context.date+'T20:00:00.000Z',sessionIntent:{prescription:plan,schedule:{id:change.id,revisionAt:change.after.recordedAt}},exercises:plan.plannedExercises.map(e=>({...e,sets:e.sets.map(s=>({...s,rpe:s.targetRpe}))}))});}assert(F.inspect(phaseApproved,po).rows.every(row=>row.status==='within'));
const snap=JSON.stringify(approved);const a=C.answer(approved,'How did my primary-lift change work?',next);assert.equal(a.source,'Shared coaching · primary-lift follow-up');assert.equal(AI.eligible('Explain primary-lift changes',a),false);assert.equal(JSON.stringify(approved),snap);
console.log('Weekly coaching: exact comparisons, controller reuse, phase boundaries, ambiguity, read-only previews, corrected follow-ups and canonical local answers passed');
