const assert=require('assert');
const S=require('../src/product/workout-session');
const estimate=(w,r)=>w*(1+r/30),id=()=> 'pr-id';
const original={id:'uuid',date:'2026-09-07',notes:'before',programId:'prog',programDayIndex:0,programWeek:3,exercises:[{name:'Bench',type:'strength',sets:[{weight:100,reps:5,rpe:8}]}]};
const workout={id:'different',date:'2026-09-06',notes:'corrected',exercises:[{name:'Bench',type:'strength',sets:[{weight:80,reps:5,rpe:7}]}]};
const state={workouts:[original],prs:[]};
const updated=S.apply(state,workout,{id:'uuid',original},null,estimate,id);
assert.equal(updated.workouts.length,1);assert.equal(updated.workouts[0].id,'uuid');assert.equal(updated.workouts[0].programWeek,3);assert.equal(updated.workouts[0].programDayIndex,0);assert.equal(original.notes,'before');
assert.equal(updated.prs[0].weight,80);assert.equal(updated.prs[0].sourceWorkoutId,'uuid');
assert.throws(()=>S.apply(updated,workout,{id:'uuid',original},null,estimate,id),/changed/);
assert.throws(()=>S.apply({workouts:[],prs:[]},workout,{id:'uuid',original},null,estimate,id),/deleted/);
const baseline={id:9,exercise:'Bench',weight:70,reps:5,date:'2020-01-01'};
let p=S.reconcilePRs([baseline],[original],estimate,id);assert.equal(p[0].weight,100);assert.equal(p[0].baselinePR.weight,70);
p=S.reconcilePRs(p,[],estimate,id);assert.equal(p[0].weight,70,'Restore independent benchmark');
assert.equal(S.reconcilePRs(updated.prs,[],estimate,id).length,0,'Remove managed PR without supporting workout');
const d=S.fromDraft({date:'2026-09-08',notes:' hi ',unit:'lb',rows:[{name:'Bench',type:'strength',sets:[{reps:'5',weight:'220.46',rpe:'8'}]},{name:'Plank',type:'strength',trackBy:'duration',sets:[{duration:'30',weight:'',rpe:''}]},{name:'Bike',type:'cardio',duration:'20',distance:'5',distanceUnit:'mi'}]},'new');
assert.equal(d.exercises[0].sets[0].weight,100);assert.equal(d.exercises[1].sets[0].weight,0);assert.equal(d.exercises[1].sets[0].duration,30);assert.equal(d.exercises[2].distanceUnit,'mi');
assert.equal(S.previous([original],' bench ','2026-09-08',null).exercise.name,'Bench');
assert.equal(S.previous([original],'Bench','2026-09-06',null),null);
assert.equal(S.previous([original],'Bench','2026-09-08','uuid'),null);
assert.equal(S.previous([original],'Bench','2026-09-08',null,'strength','duration'),null);
console.log('Session edits, provenance, comparisons, and unit tests passed');
