/* Original educational summaries with explicit provenance. No book text or model weights. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./programming-profile'),require('./athlete-intake'),require('./program-edit'));else root.LoadnoteCoachingLibrary=factory(root.LoadnoteProgrammingProfile,root.LoadnoteAthleteIntake,root.LoadnoteProgramEdit);})(typeof globalThis!=='undefined'?globalThis:this,function(Profile,Intake,Edits){
 'use strict';
 const VERSION='coaching-library-v1',REVIEWED='2026-10-06',copy=x=>JSON.parse(JSON.stringify(x));
 const SOURCES={
  essentials:{title:'Essentials of Strength Training and Conditioning · fifth edition',author:'NSCA; editors G. Gregory Haff and N. Travis Triplett',url:'https://www.nsca.com/certification/cscs/essentials-of-strength-training-and-conditioning-5th-edition/',kind:'Book reference',coverage:'Publisher description verified; full textbook not imported.'},
  methods:{title:'Westside Barbell Book of Methods',author:'Louie Simmons',url:'https://www.westside-barbell.com/collections/books/products/westside-barbell-book-of-methods',kind:'Book reference',coverage:'Book reference verified; guidance uses the public Westside articles below, not a full-text import.'},
  preparation:{title:'Preparatory Period',author:'NSCA',url:'https://www.nsca.com/education/articles/kinetic-select/preparatory-period/',kind:'Public textbook excerpt · fourth edition',coverage:'Preparation, strength phases and recovery variation.'},
  conjugate:{title:'The Conjugate Method',author:'Westside Barbell',url:'https://www.westside-barbell.com/pages/conjugate-method',kind:'Coaching methodology',coverage:'Maximal, dynamic and repeated effort; exercise rotation.'},
  dynamic:{title:'Starting Conjugate: Dynamic Effort',author:'Burley Hawk · Westside Barbell',url:'https://www.westside-barbell.com/blogs/the-blog/starting-conjugate-dynamic-effort',kind:'Coaching article citing Book of Methods',coverage:'Speed intent, training waves and controlled execution.'},
  volume:{title:'Starting Conjugate: Managing Training Volume',author:'Burley Hawk · Westside Barbell',url:'https://www.westside-barbell.com/blogs/the-blog/starting-conjugate-managing-training-volume',kind:'Coaching article citing Book of Methods',coverage:'Main movement priorities and balancing intensity, volume and frequency.'},
  growth:{title:'IUSCA hypertrophy position stand · 2021',author:'Schoenfeld and colleagues',url:'https://doi.org/10.47206/ijsc.v1i1.81',kind:'Research position stand',coverage:'Hypertrophy loading, effort, rest and workload.'}
 };
 const CARDS=[
  {id:'conjugate',title:'How conjugate training fits together',tags:['conjugate','westside','louie','simmons','book of methods','max effort','dynamic effort','repeated effort'],sources:['conjugate','methods'],summary:'Westside combines heavy strength work, submaximal work performed with speed intent, and accessory work. These methods have different purposes; rotating a variation does not make its performance interchangeable with a competition lift.',application:'Choose the method deliberately. Loadnote does not turn its linear or wave builder into a complete Westside template just because you select a variation.',question:'What is your training experience, and which lift or sport are you preparing for?'},
  {id:'dynamic-effort',title:'Dynamic effort and speed intent',tags:['dynamic effort','speed bench','speed squat','bar speed','speed work','bands','chains','accommodating resistance','pendulum'],sources:['dynamic','methods'],summary:'Dynamic effort uses submaximal resistance with fast intent and controlled technique. Westside organizes this work into short waves and adjusts the setup when movement speed deteriorates.',application:'Confirm equipment and a movement-specific starting dose. Without velocity measurements, the app cannot claim that bar speed improved. A Westside speed wave and Loadnote’s general wave-loading option are different protocols.',question:'Are you using straight weight, bands or chains, and how are you observing speed?'},
  {id:'max-effort',title:'Maximal effort and variation records',tags:['max effort','maximal effort','true max','weekly max','rotate variations','exercise rotation'],sources:['conjugate','methods'],summary:'Westside uses maximal-effort variations to train heavy strength, with rotation serving a different role from repeatedly testing the competition lifts.',application:'Weekly true-max testing is not a default prescription. Review experience, recent training and symptoms first. Record each variation separately; a safety-bar squat record does not establish a barbell squat max.',question:'Which exact variation are you considering, and do you have a recent record for it?'},
  {id:'accessory-priorities',title:'Accessories and weak-point priorities',tags:['weak point','weakness','accessories','accessory','special exercises','repeated effort','gpp','work capacity','lockout'],sources:['volume','methods'],summary:'Westside prioritizes the main movement, then supporting exercises. Higher main-lift intensity leaves less training energy for additional work; accessory volume is adjusted within the overall workload.',application:'Use stated priorities and observed exercise performance to select accessories. A sticking point or an exercise edit does not diagnose a weak muscle. Confirm movement identity, equipment and fresh targets.',question:'Which movement is limiting you, and what evidence or coach feedback supports that priority?'},
  {id:'phase-purpose',title:'Match training emphasis to the phase',tags:['periodization','phase','accumulation','strength phase','off season','preparatory','nsca','essentials','textbook','linear','undulating','wave loading'],sources:['preparation','essentials'],summary:'NSCA’s public preparatory-period excerpt describes building general capacity before more specific strength work. Strength emphasis uses heavier loading with lower volume than earlier preparation; variation and recovery weeks help organize the process.',application:'Match the phase to your goal, schedule and established training. The linked excerpt is from the fourth edition; the fifth edition is listed as further reading, not claimed as imported chapter content.',question:'What is your goal and timeline, and how consistently have you trained recently?'},
  {id:'workload',title:'Balance intensity, volume and frequency',tags:['volume management','intensity','frequency','fatigue','recovery','too much','workload','deload'],sources:['volume','preparation'],summary:'Training volume, intensity and frequency interact. Heavy work and supporting work compete for the session’s available capacity, while planned variation and recovery periods organize training over time.',application:'Review completed sets, actual effort, tolerance and available time before adding work. Unknown recovery is not clearance. Keep load changes inside the explicit Decisions review.',question:'Is the problem missed sessions, effort above the cap, or an athlete-reported recovery concern?'},
  {id:'hypertrophy',title:'Muscle growth and sustainable effort',tags:['hypertrophy','muscle growth','failure','rep range','rest between','bodybuilding'],sources:['growth'],summary:'Muscle growth is possible across a broad loading range. Every set need not reach failure, and adequate rest helps preserve subsequent performance. Volume needs vary between people.',application:'Use actual effort and tolerance to review the dose. Repeated-effort work is not blanket permission to take all compound sets to failure.',question:'Which muscle group, weekly workload and actual effort are you reviewing?'}
 ];
 function catalog(){return {version:VERSION,reviewedOn:REVIEWED,sources:copy(SOURCES),cards:copy(CARDS),notice:'Original summaries of the linked sources. A book listing is further reading, not evidence that the entire book was imported or a model was trained on it.'};}
 const clean=q=>String(q||'').toLowerCase().replace(/[’]/g,"'").replace(/[-–]/g,' ').replace(/\s+/g,' ').trim().slice(0,500);
 function retrieve(question,{limit=3}={}){
  const q=clean(question);if(!q)return [];
  return CARDS.map((c,index)=>({c,index,score:c.tags.reduce((s,t)=>s+(new RegExp('(?:^|\\W)'+t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?:$|\\W)','i').test(q)?t.split(' ').length+(t===c.tags[0]?2:0):0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.index-b.index).slice(0,Math.max(1,Math.min(3,limit))).map(x=>copy(x.c));
 }
 const follow=q=>/^(why\??|how so\??|tell me more\.?|explain (that|more)\.?|how (would|does) (that|this) (apply|work)( for me)?\??)$/i.test(q);
 function query(question,history=[]){if(!follow(question))return String(question||'');const prior=history.slice(-8).filter(r=>r.role==='user').at(-1);return prior?String(prior.content):'';}
 function profile(state,asOf,knownAt){return Profile.current(state.programmingProfiles||[],knownAt||(asOf?asOf+'T23:59:59.999Z':undefined))?.context||null;}
 function personal(state,{asOf,knownAt}={}){
  const p=profile(state,asOf,knownAt);if(!p)return 'Your programming setup is missing. Review training experience, goal, availability and equipment before choosing a method.';
  const text=['Your saved setup: '+p.experience+' experience, '+p.consistency+' training, '+Profile.GOALS[p.goal]+', '+p.availableDays.length+' available days and '+p.sessionMinutes+' minutes per session.'];
  if(Intake.active(p.intake))text.push('Your intake reports current symptoms; automated increases remain held. These training references do not diagnose or prescribe rehabilitation.');
  if(p.experience==='unknown')text.push('Confirm your experience before deciding how much heavy or technical work to include.');
  if(p.experience==='beginner'||p.consistency==='returning')text.push('Prioritize repeatable technique and an established base; frequent true-max testing needs individual review.');
  if(p.avoidedExerciseIds.length)text.push('Your '+p.avoidedExerciseIds.length+' confirmed exercise exclusions remain in force.');
  if(asOf&&Edits){const e=Edits.learning(state,{asOf});if(e.events.length)text.push(e.events.length+' recorded exercise edit(s) describe your choices; '+e.suggestions.length+' repeated choices still need explicit preference confirmation. Edits do not prove improvement.');}
  return text.join(' ');
 }
 function answer(state,question,{asOf,history=[]}={}){
  if(/\b(what|which|show|list)\b.*\b(books|sources|references|knowledge base)\b/i.test(question))return {text:'The coaching library lists NSCA Essentials (fifth edition) and Louie Simmons’ Book of Methods as further reading. Original summaries use public NSCA material, Westside articles and a hypertrophy position stand. Full book text has not been imported and model weights have not been trained on either book.',source:'Shared coaching · referenced knowledge',readOnly:true,evidence:[],citations:Object.entries(SOURCES).map(([id,s])=>({id,...copy(s)})),actions:[{kind:'library',label:'Explore coaching references'}]};
  const q=query(question,history),cards=retrieve(q);if(!cards.length||!/(?:explain|what (?:is|are|does)|how.*(?:work|differ|apply)|teach|learn|compare|principle|method|nsca|westside|louie|simmons|essentials|textbook)/i.test(q))return null;
  // Existing personal evidence, medical and action handlers retain priority.
  if(/\b(pain|hurt|injur\w*|rehab|tendinitis|tendinopathy|diagnos\w*|intake|edit|remove|swap|cancel|progress|training max|my.*(?:sets|load|workout)|why (?:this|my) (?:set|load))\b/i.test(q))return null;
  const selected=/\b(nsca|essentials|books?|sources?|references?|textbooks?)\b/i.test(q)?cards:cards.slice(0,2),ids=[...new Set(selected.flatMap(c=>c.sources))];
  return {text:selected.map(c=>c.title+': '+c.summary+' '+c.application).join('\n\n')+'\n\n'+personal(state,{asOf}),source:'Shared coaching · referenced knowledge',readOnly:true,citations:ids.map(id=>({id,...copy(SOURCES[id])})),knowledgeIds:selected.map(c=>c.id),evidence:[],followUps:selected.slice(0,2).map(c=>'Explain '+c.tags[0]),clarification:selected[0].question,actions:[{kind:'library',label:'Explore coaching references'}],intent:{topic:'knowledge',referenceQuestion:q}};
 }
 function review(state,proposal,{asOf,knownAt,framework='foundation'}={}){
  if(!['foundation','conjugate'].includes(framework))throw Error('Choose a coaching framework');
  const sessions=proposal?.sessions||[],config=proposal?.config||{},p=profile(state,asOf,knownAt),findings=[];
  const add=(code,message,sources)=>findings.push({code,message,sources});
  if(!p||p.experience==='unknown')add('experience','Confirm training experience before reviewing method suitability.',['preparation']);
  if(p&&Intake.active(p.intake))add('symptoms','Current symptoms hold automated increases. Source material does not provide medical clearance.',['preparation']);
  if(sessions.some(s=>Number(s.estimatedMinutes)>Number(p?.sessionMinutes)))add('time','At least one session exceeds your saved time availability. Reduce or redistribute planned work before scheduling.',['volume']);
  if(framework==='conjugate'){
   add('method-scope','This reviewed plan is not automatically a Westside template. Heavy, speed and supporting work need distinct objectives; the existing builder has no verified dynamic-effort velocity target.',['conjugate','dynamic']);
   if(!p||['unknown','beginner'].includes(p.experience)||p.consistency==='returning')add('max-review','Do not infer weekly true-max testing from this framework; review skill and established training first.',['conjugate']);
   if(!config.accessories?.length)add('accessory-purpose','Supporting accessory slots are not identified in this review. Review your stated priorities and available capacity rather than inventing weak muscles or adding a stock exercise list.',['volume']);
  }
  if(config.periodization==='wave')add('wave-scope','Loadnote’s wave-loading progression is not the same as Westside’s dynamic-effort wave. Do not interchange their percentages or resistance setups.',['dynamic']);
  const late=sessions.filter(s=>/peak|taper/.test(s.phase||''));if(late.some(s=>(s.exercises||[]).some(e=>e.role==='variation')))add('specificity','Variation work remains near the event. Review the competition-lift emphasis in your dedicated meet-cycle review.',['preparation']);
  add('dose-review','Compare the proposed dose with actual matching work, effort and athlete reports. Reference guidance does not approve a load increase.',['volume','preparation']);
  return {version:VERSION,framework,readOnly:true,findings,context:personal(state,{asOf,knownAt}),notice:'Educational review of this proposal. No targets, exercise choices or training history are changed.'};
 }
 return {VERSION,catalog,retrieve,query,answer,personal,review};
});
