/* Shared, read-only coaching context. Measurements, reports and unknowns stay distinct. */
(function(root,factory){
 if(typeof module==='object'&&module.exports)module.exports=factory(require('./athlete-goals'),require('./programming-profile'),require('./muscle-workload-review'),require('./schedule'),require('./program-lifecycle'),require('./sport-planner'),require('./hypertrophy-builder'),require('./sport-context'),require('./data-integrity'),require('./guided-plan'),require('./program-cancellation'));
 else root.LoadnoteCoachingContext=factory(root.LoadnoteGoals,root.LoadnoteProgrammingProfile,root.LoadnoteMuscleReview,root.LoadnoteSchedule,root.LoadnoteProgramLifecycle,root.LoadnoteSportPlanner,root.LoadnoteHypertrophyBuilder,root.LoadnoteSportContext,root.LoadnoteIntegrity,root.LoadnoteGuidedPlan,root.LoadnoteProgramCancellation);
})(typeof globalThis!=='undefined'?globalThis:this,function(G,P,W,S,L,B,H,C,D,A,Cancellation){
 'use strict';
 const Intake=typeof module==='object'&&module.exports?require('./athlete-intake'):globalThis.LoadnoteAthleteIntake;
 const clone=x=>JSON.parse(JSON.stringify(x)),shift=(d,n)=>{const t=new Date(d+'T12:00:00Z');t.setUTCDate(t.getUTCDate()+n);return t.toISOString().slice(0,10);},end=d=>d+'T23:59:59.999Z';
 const KEYS=['activeProgramId','programs','programStates','adoptedPrograms','trainingBlocks','reviewedPrograms','programReviews','workouts','workoutRevisions','scheduledSessions','athleteGoals','exerciseCatalog','exerciseRoles','programmingProfiles','workloadProfiles','sportPrograms','hypertrophyPrograms','phasePrograms','phaseReviews','meetCycles','transitionSnapshots','decisionEvents','olympicPractice','athleticPractice','coachingReviews','programCancellations'];
 function signature(state){const value=JSON.stringify(Object.fromEntries(KEYS.map(k=>[k,state[k]||[]])));let h=2166136261;for(const c of value)h=Math.imul(h^c.charCodeAt(0),16777619);return (h>>>0).toString(36);}
 function currentRows(state,asOf){return S.list(S.validate(state.scheduledSessions||[])).map(s=>({...s,state:(state.workouts||[]).some(w=>w.sessionIntent?.schedule?.id===s.id&&w.date===s.date&&w.date<=asOf)?'completed':s.status==='scheduled'?(s.date<asOf?'unconfirmed':'scheduled'):s.status}));}
 function build(state,{asOf,live=null,sportLive=null,sessionId=null}={}){
  if(!S.date(asOf))throw Error('Choose a valid coaching date');
  const from=shift(asOf,-6),cutoff=end(asOf),goals=G.list(state.athleteGoals||[]).filter(g=>g.status==='active'),profile=P.current(state.programmingProfiles||[]),workload=W.current(state.workloadProfiles||[]),rows=currentRows(state,asOf);
  let lifecycle=null;try{lifecycle=L.inspect(state,{asOf,draftOpen:!!live?.liveWorkout?.active||!!sportLive});}catch(e){lifecycle={status:'error',nextAction:{label:'Resolve program context',detail:e.message}};}
  const requested=sessionId||sportLive?.sessionId,session=requested?rows.find(s=>s.id===requested):rows.find(s=>s.date===asOf&&s.state==='scheduled')||rows.find(s=>s.date>asOf&&s.state==='scheduled')||null;
  const program=lifecycle?.program?{id:lifecycle.program.id,kind:lifecycle.program.kind,name:lifecycle.program.name,phase:lifecycle.progress?.phase||null,week:lifecycle.progress?.week||null}:null;
  let currentTask=null;if(sportLive){const p=B.validate(state.sportPrograms||[]).find(p=>sportLive.sessionId?.startsWith('sport:'+p.id+':')),s=p?.sessions.find(s=>'sport:'+p.id+':'+s.key===sportLive.sessionId);if(s&&session?.revisionAt===sportLive.revisionAt&&Number.isInteger(sportLive.slotIndex)&&s.slots[sportLive.slotIndex]){const slot=s.slots[sportLive.slotIndex];currentTask={sessionId:sportLive.sessionId,date:session.date,slotIndex:sportLive.slotIndex,exerciseId:slot.exerciseId,name:slot.name,kind:slot.kind,purpose:slot.purpose,protocol:slot.protocol,target:clone(slot),observations:clone(sportLive.observations||[]),reported:true};}}
  else if(live?.liveWorkout?.active){const ex=live.liveWorkout.currentExercise,current=ex?.name?catalogMatches(state,ex.name):[];currentTask=ex?{name:ex.name,exerciseId:current.length===1?current[0].id:null,kind:'strength',target:ex.set?.target||null,previous:ex.set?.previous||null,reported:true}:null;}
  const actual=(state.workouts||[]).filter(w=>w.date>=from&&w.date<=asOf),sets=actual.flatMap(w=>(w.exercises||[]).filter(e=>(e.type==='strength'||!e.type)&&e.trackBy!=='duration').flatMap(e=>(e.sets||[]).filter(s=>s.done!==false&&s.completed!==false&&!s.skipped&&!s.warmup&&s.type!=='warmup').map(s=>({workoutId:w.id,date:w.date,exerciseId:e.exerciseId,...s})))),known=sets.filter(s=>Number.isFinite(s.rpe)&&s.rpe>=1&&s.rpe<=10);
  let trends=[];try{trends=W.analyze(state,{asOf}).trends.filter(t=>t.latest.date>=from).map(t=>({...t,notice:'Same recorded loads and similar reported effort; measurement conditions and causal attribution are not verified.'}));}catch{}
  const technical=C.listPractice(state.olympicPractice||[]).filter(p=>p.date>=from&&p.date<=asOf),drills=B.validateAthletic(state.athleticPractice||[]).flatMap(r=>{const v=r.revisions.at(-1);return v?.context&&v.context.date>=from&&v.context.date<=asOf?[{id:r.id,...v.context}]:[];});
  const sports=B.validate(state.sportPrograms||[]).filter(p=>!Cancellation.isCancelled(state,p.id,'sport-program')&&p.scheduledAt&&p.config.startDate<=asOf&&p.weekly.at(-1).through>=from).map(p=>B.review(state,p.id,{asOf})),hypertrophy=H.validate(state.hypertrophyPrograms||[]).filter(p=>!Cancellation.isCancelled(state,p.id,'hypertrophy-program')&&p.scheduledAt&&p.config.startDate<=asOf&&p.weekly.at(-1).through>=from).map(p=>H.progression(state,p.id,{asOf}));
  const weeklyRows=rows.filter(s=>s.date>=from&&s.date<=asOf),checkIn=(state.coachingReviews||[]).filter(r=>r.kind==='weekly'&&r.asOf>=from&&r.asOf<=asOf).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).at(-1)?.checkIn||null;
  const gaps=[];if(!goals.length)gaps.push('No active confirmed goal');if(!profile)gaps.push('Programming profile not recorded');if(workload?.context.coverage!=='complete'||workload.context.from>from||workload.context.through<asOf)gaps.push('Complete history coverage for this review window is not declared');if(workload?.context.tolerance!=='tolerated')gaps.push('Recent tolerated training is not confirmed');if(known.length!==sets.length)gaps.push((sets.length-known.length)+' strength sets have unknown effort');if(weeklyRows.some(s=>s.state==='unconfirmed'))gaps.push('Earlier Calendar sessions remain unconfirmed');if(goals.some(g=>!g.trainingContext.scheduleKnown))gaps.push('Sport schedule is unknown for an active goal');
  const priorities=[];if(Intake.active(profile?.context.intake))priorities.push({kind:'review',text:'Current intake symptoms hold generated programming and increases; review an individual plan.'});if(['discomfort','needs-review'].includes(workload?.context.tolerance))priorities.push({kind:'review',text:'Review reported training limitations before a new prescription.'});if(sports.some(p=>p.status==='review-with-coach'))priorities.push({kind:'sport',text:'Review misses, inconsistent quality, effort caps or changed sport context with the responsible coach.'});if(gaps.length)priorities.push({kind:'evidence',text:gaps[0]});if(!priorities.length)priorities.push({kind:'continue',text:'Keep the reviewed plan; inspect actual effort and outcomes before any future change.'});
  return {version:1,asOf,from,readOnly:true,signature:signature(state),goals:goals.map(g=>({id:g.id,name:g.name,sport:g.sport,context:clone(g.trainingContext),availableDays:g.availableDays,sessionMinutes:g.sessionMinutes,equipment:g.equipment,eventDate:g.eventDate})),profile:profile?.context||null,workload:workload?.context||null,program,lifecycle,session:session?{id:session.id,date:session.date,name:session.name,role:session.role,revisionAt:session.revisionAt,state:session.state,targets:clone(session.prescription.plannedExercises)}:null,currentTask,weekly:{workoutIds:actual.map(w=>w.id),sessions:actual.length,calendar:{completed:weeklyRows.filter(s=>s.state==='completed').length,skipped:weeklyRows.filter(s=>s.state==='skipped').length,unconfirmed:weeklyRows.filter(s=>s.state==='unconfirmed').length},strength:{sets:sets.length,knownEffort:known.length,unknownEffort:sets.length-known.length},technical:{records:technical.length,made:technical.flatMap(p=>p.attempts).filter(a=>a.outcome==='made').length,missed:technical.flatMap(p=>p.attempts).filter(a=>a.outcome==='missed').length,unknown:technical.flatMap(p=>p.attempts).filter(a=>a.outcome==='unknown'||a.quality==='unknown').length},drills,sports,hypertrophy,checkIn,trends},gaps,priorities:priorities.slice(0,3),notice:'Current corrected records and athlete reports. Session logs do not prove all targets were completed. No causal learning, technique diagnosis, recovery score or automatic prescription.'};
 }
 function catalogMatches(state,q){const key=String(q).toLowerCase().trim();return (state.exerciseCatalog||[]).filter(e=>[e.name,...(e.aliases||[])].some(n=>String(n).toLowerCase().trim()===key));}
 function named(state,q){const lower=q.toLowerCase();return (state.exerciseCatalog||[]).filter(e=>[e.name,...(e.aliases||[])].some(n=>{const name=String(n).toLowerCase().trim();return name.length>=3&&new RegExp('(^|[^a-z0-9])'+name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'([^a-z0-9]|$)').test(lower);}));}
 function resolve(state,q,history,snapshot){
  const text=String(q||'').trim().slice(0,500),explicit=named(state,text),follow=/\b(that|this|it|same|tomorrow|yesterday|next session)\b|^(why|how so|tell me more|what should i change)\??$/i.test(text);
  let prior=null;const last=(history||[]).slice(-8).filter(r=>r.role==='user'&&r.content!==text).at(-1);if(follow&&last){const matches=named(state,String(last.content));if(matches.length===1)prior=matches[0];}
  const matches=explicit.length?explicit:prior?[prior]:snapshot.currentTask?.exerciseId?(state.exerciseCatalog||[]).filter(e=>e.id===snapshot.currentTask.exerciseId):[];
  return {question:text,matches,follow,date:/\btomorrow\b/i.test(text)?shift(snapshot.asOf,1):/\byesterday\b/i.test(text)?shift(snapshot.asOf,-1):snapshot.asOf};
 }
 function explain(s){return 'Training review '+s.from+'–'+s.asOf+': '+s.weekly.sessions+' session logs, '+s.weekly.strength.sets+' strength sets ('+s.weekly.strength.unknownEffort+' with unknown effort), '+s.weekly.technical.made+' made / '+s.weekly.technical.missed+' missed technical attempts and '+s.weekly.drills.length+' separate athletic journal records. '+(s.weekly.trends||[]).filter(t=>t.comparable).slice(0,3).map(t=>t.name+': '+(t.repChange>0?'+':'')+t.repChange+' total reps at the same recorded loads, '+t.previous.date+' to '+t.latest.date+' (similar reported effort).').join(' ')+' '+s.priorities.map(p=>p.text).join(' ')+(s.gaps.length?' Missing evidence: '+s.gaps.join('; ')+'. ':' ')+s.notice;}
 function answer(state,q,{asOf,history=[],live=null,sportLive=null,unit='kg'}={}){
  const snapshot=build(state,{asOf,live,sportLive}),r=resolve(state,q,history,snapshot),text=r.question,reply=(text,kind='context')=>({text,source:'Shared coaching '+kind,evidence:[snapshot],intent:{topic:'unified',referenceQuestion:r.question,exerciseId:r.matches.length===1?r.matches[0].id:null},readOnly:true});
  if(/\b(pain|hurt|injur|rehab|diagnos)\w*/i.test(text))return null;
  if(A&&/\b(start|build|create|set up)\b.*\b(plan|program)\b/i.test(text)){
   const mode=/\b(olympic|weightlifting|snatch|clean and jerk)\b/i.test(text)?'weightlifting':/\b(athlete|sport|speed|jump|agility)\b/i.test(text)?'athlete':/\b(hypertrophy|muscle|growth)\b/i.test(text)?'hypertrophy':null;
   if(mode){const v=A.inspect(state,mode),ready=v.goals.filter(g=>!g.gaps.length);return reply('Open Decisions → Programming → Starter plans → '+A.MODES[mode]+'. '+(ready.length?'Reuse your confirmed goal and availability, choose exact movements, then review dose, constraints and every week.':'Complete a matching active goal first: '+(v.goals.map(g=>g.name+' — '+g.gaps.join(', ')).join('; ')||'training priority, equipment, availability and sport context')+'. ')+v.roles.filter(r=>!r.choices.length).map(r=>'Confirm an eligible '+r.label.toLowerCase()+' exercise mapping.').join(' ')+' The starting structure is editable, not an individualized dose. Saving and scheduling require separate explicit review; chat does not create training.','guided plan');}
  }
  if(/\b(current|approved|next)\b.*\b(load|target|increment)\b|\b(after|another|again)\b.*\b(increase|progression)\b/i.test(text)&&snapshot.weekly.hypertrophy.length){const reports=snapshot.weekly.hypertrophy,findings=reports.flatMap(r=>r.findings).filter(f=>!r.matches.length||r.matches.some(e=>e.id===f.exerciseId));if(findings.length)return reply(findings.map(f=>f.name+' · current approved load '+f.currentKg+' kg ('+f.loadConvention+') · '+f.approvedIncreases+' accepted increase(s). '+(f.candidateKg!=null?'Review '+f.currentKg+' → '+f.candidateKg+' kg in Proposed changes. ':f.reasons.join(' '))).join(' ')+' Each next increase needs two new comparable sessions at that approved target. Chat does not apply it.','current progression');}
  if(/\bwhy\b.*\b(change|changed|update|updated)\b/i.test(text)){const event=(state.coachingReviews||[]).filter(r=>r.kind==='proposal'&&r.response==='accepted'&&r.asOf<=asOf&&r.proposal.changes.some(c=>c.sessionId===snapshot.session?.id&&snapshot.session.revisionAt===r.createdAt)).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).at(-1);if(event){const p=event.proposal;return reply('You accepted this exact future-session proposal on '+event.asOf+': '+p.reason+' Evidence: '+p.evidence.join('; ')+'. The approved Calendar revision is '+event.createdAt+'. '+(p.kind==='hypertrophy-load'?'Reviewed load '+p.fromKg+' → '+p.toKg+' kg ('+p.loadConvention+'). ':'The session was explicitly deferred with targets retained. ')+'This is a stored reviewed change, not proof of a training benefit.','accepted change');}}
  if(/\b(weekly review|review my week|this week went|week summary|weekly coaching)\b/i.test(text))return reply(explain(snapshot),'weekly review');
  if(/\b(what about tomorrow|what.*tomorrow|what.*yesterday|next session|next drill|next attempt)\b/i.test(text)){const rows=currentRows(state,asOf),row=/next session/i.test(text)?rows.find(s=>s.date>asOf&&s.state==='scheduled'):rows.find(s=>s.date===r.date&&s.state==='scheduled');return reply(row?row.date+' · '+row.name+'. Reviewed targets: '+row.prescription.plannedExercises.map(e=>e.name+' ('+(e.type==='practice'?e.kind:e.type)+')').join(', ')+'. Review practice/game conflicts and protocols in Calendar; this does not change the plan.':'No scheduled session is recorded for that date. Unrecorded practices or games remain unknown.');}
  if(r.matches.length>1&&/\b(why|change|compare|last|progress|load|reps|exercise)\b/i.test(text))return reply('Which exact movement do you mean: '+r.matches.map(e=>e.name).join(', ')+'?','clarification');
  if(r.matches.length===1&&/\b(compare.*last|last time.*exercise|how did.*last time)\b/i.test(text)){const e=r.matches[0],t=snapshot.weekly.trends.find(t=>t.exerciseId===e.id);return reply(t?.comparable?e.name+': '+t.previous.reps+' total reps on '+t.previous.date+' → '+t.latest.reps+' on '+t.latest.date+' at the same recorded loads and similar reported effort. '+t.notice:e.name+': no recent comparable pair with the same recorded loads and known similar effort is available. Technical attempts and athletic drills require separate protocol review; no strength estimate is inferred.','comparison');}
  const task=snapshot.currentTask,taskQuestion=/\b(why this (exercise|drill|attempt)|stop rule|stop protocol|current drill|current attempt|how.*attempt|how.*drill)\b/i.test(text);
  if(task&&task.kind!=='strength'&&(!r.matches.length||r.matches.length===1&&r.matches[0].id===task.exerciseId)&&(taskQuestion||/^(why\??|how so\??|should i change (this|that)\??)$/i.test(text))){const issues=task.observations.some(a=>a.outcome==='missed'||a.quality==='inconsistent');return reply(task.name+' · '+task.kind+'. Purpose: '+task.purpose+'. Reviewed execution/stop protocol: '+task.protocol+'. '+(issues?'You reported a miss or inconsistent quality. Follow the reviewed stop/defer rule and review with your coach; no extra success-chasing attempts or load increase is proposed. ':'Unknown outcomes and quality stay unknown. ')+'Technical attempts/drills do not become strength PRs.','live sport context');}
  if(/\b(should i change (this|that)|what should i change|preview (a )?change|propose (a )?change)\b/i.test(text))return reply('Open Decisions → Weekly check-in → Proposed changes. Each supported proposal shows its evidence, affected future dates and before/after targets. Missing effort, restrictions or sport-quality concerns request review instead of a guessed increase. Chat does not apply changes.','proposal workflow');
  if(r.matches.length===1&&(/\b(why this exercise|why.*movement)\b/i.test(text)||r.follow&&/^(why|how so)\??$/i.test(text))){const e=r.matches[0],slots=[...(state.sportPrograms||[]),...(state.hypertrophyPrograms||[])].filter(p=>p.scheduledAt).flatMap(p=>p.config.slots).filter(s=>s.exerciseId===e.id),purposes=[...new Set(slots.map(s=>s.purpose))];return reply(e.name+': '+(purposes.length===1?purposes[0]:purposes.length?'Multiple reviewed purposes exist; choose the session in Calendar.':'No reviewed exercise purpose is recorded. Confirm the target session rather than inferring a weakness.')+' This explains your recorded plan, not a diagnosed limitation.');}
  return null;
 }
 return {KEYS,shift,signature,currentRows,build,resolve,catalogMatches,explain,answer};
});
