/* Explicit reviewed proposals and athlete check-ins. No chat-driven writes or causal learning. */
(function(root,factory){
 if(typeof module==='object'&&module.exports)module.exports=factory(require('./coaching-context'),require('./hypertrophy-builder'),require('./sport-planner'),require('./schedule'),require('./session-intent'),require('../core/loadnote-core'),require('./data-integrity'));
 else root.LoadnoteCoachingReview=factory(root.LoadnoteCoachingContext,root.LoadnoteHypertrophyBuilder,root.LoadnoteSportPlanner,root.LoadnoteSchedule,root.LoadnoteIntent,root.LoadnoteCore,root.LoadnoteIntegrity);
})(typeof globalThis!=='undefined'?globalThis:this,function(C,H,B,S,I,Core,D){
 'use strict';
 const clone=x=>JSON.parse(JSON.stringify(x)),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),iso=x=>typeof x==='string'&&Number.isFinite(Date.parse(x))&&new Date(x).toISOString()===x,text=(x,n)=>typeof x==='string'&&x.length<=n;
 function checkIn(raw){if(!raw||!['unknown','adequate','poor'].includes(raw.sleep)||!['unknown','usual','elevated'].includes(raw.soreness)||!['unknown','usual','elevated'].includes(raw.fatigue)||!text(raw.notes,1000))throw Error('Choose explicit check-in values; unknown is allowed');return {sleep:raw.sleep,soreness:raw.soreness,fatigue:raw.fatigue,notes:raw.notes.trim()};}
 function proposal(raw){
  if(!raw||raw.version!==1||!['hypertrophy-load','sport-defer'].includes(raw.kind)||!text(raw.key,300)||!raw.key||!text(raw.programId,160)||!raw.programId||!S.date(raw.asOf)||!text(raw.basis,100)||!text(raw.reason,1500)||!Array.isArray(raw.evidence)||raw.evidence.length>20||raw.evidence.some(x=>!text(x,1000))||!Array.isArray(raw.changes)||!raw.changes.length||raw.changes.length>150)throw Error('Invalid coaching proposal');
  const changes=raw.changes.map(c=>{if(!text(c.sessionId,240)||!c.sessionId||!iso(c.revisionAt))throw Error('Invalid proposal session');const before=S.validate([{id:c.sessionId,revisions:[{recordedAt:c.revisionAt,context:c.before}]}])[0].revisions[0].context,after=S.validate([{id:c.sessionId,revisions:[{recordedAt:c.revisionAt,context:c.after}]}])[0].revisions[0].context;if(before.date<=raw.asOf||after.date!==before.date||before.status!=='scheduled'||!same(before.prescription.source,after.prescription.source))throw Error('Proposal must preserve future session identity');return {sessionId:c.sessionId,revisionAt:c.revisionAt,before,after};});
  if(new Set(changes.map(c=>c.sessionId)).size!==changes.length)throw Error('Duplicate proposed session');
  if(raw.kind==='sport-defer'&&(changes.length!==1||changes[0].after.status!=='skipped'||!same(changes[0].before.prescription,changes[0].after.prescription)))throw Error('Sport deferral must preserve targets');
  if(raw.kind==='hypertrophy-load'){if(!text(raw.exerciseId,160)||!Number.isFinite(raw.fromKg)||!Number.isFinite(raw.toKg)||raw.fromKg<0||raw.toKg<=raw.fromKg||raw.toKg>1000)throw Error('Invalid explicit increment');for(const c of changes){const expected=clone(c.before);for(const e of expected.prescription.plannedExercises)if(e.exerciseId===raw.exerciseId)for(const s of e.sets||[])s.weight=raw.toKg;if(!same(expected,c.after)||!c.before.prescription.plannedExercises.some(e=>e.exerciseId===raw.exerciseId&&e.type==='strength'&&e.sets.length&&e.sets.every(s=>s.weight===raw.fromKg)))throw Error('Proposal changes exceed the eligible explicit load increment');}}
  if(!text(raw.name,240)||!raw.name||raw.kind==='hypertrophy-load'&&!H.CONVENTIONS[raw.loadConvention])throw Error('Invalid proposal name or load convention');
  return {version:1,key:raw.key,kind:raw.kind,programId:raw.programId,name:raw.name,asOf:raw.asOf,basis:raw.basis,reason:raw.reason,evidence:clone(raw.evidence),...(raw.kind==='hypertrophy-load'?{exerciseId:raw.exerciseId,fromKg:raw.fromKg,toKg:raw.toKg,loadConvention:raw.loadConvention}:{}),changes};
 }
 function validate(records){if(!Array.isArray(records)||records.length>5000)throw Error('Invalid coaching review history');const ids=new Set();return records.map(r=>{if(!r||r.version!==1||!text(r.id,160)||!r.id||ids.has(r.id)||!iso(r.createdAt)||!S.date(r.asOf)||r.asOf>r.createdAt.slice(0,10)||!['weekly','proposal'].includes(r.kind))throw Error('Invalid coaching review identity/date');ids.add(r.id);if(r.kind==='weekly'){if(!S.date(r.from)||r.from!==C.shift(r.asOf,-6)||!text(r.evidenceSignature,100))throw Error('Invalid weekly review window');return {version:1,id:r.id,kind:'weekly',createdAt:r.createdAt,asOf:r.asOf,from:r.from,evidenceSignature:r.evidenceSignature,checkIn:checkIn(r.checkIn)};}if(!['accepted','declined'].includes(r.response)||!text(r.reviewer,120)||!text(r.notes,1000))throw Error('Invalid proposal response');const p=proposal(r.proposal);if(p.asOf!==r.asOf||p.changes.some(c=>c.revisionAt>=r.createdAt)||r.response==='accepted'&&p.kind==='sport-defer'&&!r.reviewer.trim())throw Error('Invalid reviewed proposal chronology or reported reviewer');return {version:1,id:r.id,kind:'proposal',createdAt:r.createdAt,asOf:r.asOf,response:r.response,reviewer:r.reviewer.trim(),notes:r.notes.trim(),proposal:p};});}
 function weekly(state,raw,{asOf,now=new Date().toISOString()}={}){if(!iso(now))throw Error('Invalid review time');const snapshot=C.build(state,{asOf}),value={version:1,id:Core.createId(),kind:'weekly',createdAt:now,asOf,from:snapshot.from,evidenceSignature:snapshot.signature,checkIn:checkIn(raw)};return {...state,coachingReviews:validate([...(state.coachingReviews||[]),value])};}
 function proposals(state,{asOf}={}){
  const snapshot=C.build(state,{asOf}),result=[],rows=C.currentRows(state,asOf),records=validate(state.coachingReviews||[]),last=snapshot.weekly.checkIn;
  const caution=last&&(last.sleep==='poor'||last.soreness==='elevated'||last.fatigue==='elevated');
  if(!caution)for(const report of snapshot.weekly.hypertrophy){for(const finding of report.findings.filter(f=>f.status==='review-load')){const future=rows.filter(s=>s.id.startsWith('hypertrophy:'+report.programId+':')&&s.id.endsWith('d'+finding.day)&&s.date>asOf&&s.state==='scheduled'&&s.role!=='deload'&&s.prescription.plannedExercises.some(e=>e.exerciseId===finding.exerciseId)),changes=[];if(!future.length||future.some(s=>s.prescription.plannedExercises.filter(e=>e.exerciseId===finding.exerciseId).some(e=>e.sets.some(t=>t.weight!==finding.currentKg)))||records.some(r=>r.kind==='proposal'&&r.response==='accepted'&&r.proposal.kind==='hypertrophy-load'&&r.proposal.programId===report.programId&&r.proposal.exerciseId===finding.exerciseId))continue;
   for(const s of future){const before=clone((state.scheduledSessions||[]).find(r=>r.id===s.id).revisions.at(-1).context),after=clone(before);after.prescription.plannedExercises.filter(e=>e.exerciseId===finding.exerciseId).forEach(e=>e.sets.forEach(t=>t.weight=finding.candidateKg));changes.push({sessionId:s.id,revisionAt:s.revisionAt,before,after});}
   result.push(proposal({version:1,key:'hypertrophy:'+report.programId+':'+finding.day+':'+finding.exerciseId,kind:'hypertrophy-load',programId:report.programId,exerciseId:finding.exerciseId,name:finding.name,asOf,basis:snapshot.signature,fromKg:finding.currentKg,toKg:finding.candidateKg,loadConvention:finding.loadConvention,reason:'Review the previously selected increment after two complete comparable sessions at the top of the reviewed rep range, with complete effort/coverage and reported tolerance.',evidence:finding.dates.map(d=>'Comparable full session '+d),changes}));
  }}
  for(const report of snapshot.weekly.sports.filter(r=>r.status==='review-with-coach')){const next=rows.find(s=>s.id.startsWith('sport:'+report.programId+':')&&s.date>asOf&&s.state==='scheduled');if(!next)continue;const before=clone((state.scheduledSessions||[]).find(r=>r.id===next.id).revisions.at(-1).context),after={...clone(before),status:'skipped',reason:'Explicitly deferred pending reported coach review; reviewed targets retained.'};result.push(proposal({version:1,key:'sport-defer:'+next.id,kind:'sport-defer',programId:report.programId,name:next.name,asOf,basis:snapshot.signature,reason:'Reported sport evidence requires coach review. Optionally defer the next future session while resolving it; this is not a diagnosis or clearance.',evidence:[B.explain(report)],changes:[{sessionId:next.id,revisionAt:next.revisionAt,before,after}]}));}
  return {version:1,asOf,readOnly:true,proposals:result,note:caution?'A recent athlete-reported sleep/soreness/fatigue concern holds increase proposals for review; this is not a measured recovery score.':'Only supported policy proposals appear. Missing evidence does not generate a guessed adjustment; powerlifting changes use their existing Decisions review.',signature:snapshot.signature};
 }
 function respond(state,raw,{response,confirmed=false,reviewer='',notes='',asOf,now=new Date().toISOString(),draftOpen=false}={}){
  if(!iso(now)||!['accepted','declined'].includes(response)||confirmed!==true||draftOpen)throw Error('Explicitly review the proposal and finish any open workout/sport draft first');const selected=proposal(raw),fresh=proposals(state,{asOf}).proposals.find(p=>p.key===selected.key);if(!fresh||!same(selected,fresh))throw Error('Coaching evidence or schedule changed. Reopen a fresh proposal.');if(response==='accepted'&&selected.kind==='sport-defer'&&!reviewer.trim())throw Error('Name the reported coach/professional review supporting this deferral');
  let scheduledSessions=S.validate(state.scheduledSessions||[]);if(response==='accepted')for(const c of selected.changes){if((state.workouts||[]).some(w=>w.sessionIntent?.schedule?.id===c.sessionId)||c.before.date<=asOf)throw Error('Only unperformed future sessions may change');const row=scheduledSessions.find(r=>r.id===c.sessionId);if(!row||row.revisions.at(-1).recordedAt!==c.revisionAt||!same(row.revisions.at(-1).context,c.before))throw Error('Schedule changed; refresh the proposal');const after=clone(c.after);if(selected.kind==='hypertrophy-load')after.prescription=I.prescription({...after.prescription,capturedAt:now});row.revisions.push({recordedAt:now,context:after});}
  const event={version:1,id:Core.createId(),kind:'proposal',createdAt:now,asOf,response,reviewer,notes,proposal:selected};return {...state,scheduledSessions:S.validate(scheduledSessions),coachingReviews:validate([...(state.coachingReviews||[]),event])};
 }
 function outcomes(state,{asOf}={}){
  if(!S.date(asOf))throw Error('Invalid outcome date');return validate(state.coachingReviews||[]).filter(r=>r.kind==='proposal'&&r.asOf<=asOf).map(r=>{const changes=r.proposal.changes,ids=new Set(changes.map(c=>c.sessionId)),workouts=(state.workouts||[]).filter(w=>ids.has(w.sessionIntent?.schedule?.id)&&w.date<=asOf&&w.createdAt>=r.createdAt),attributed=workouts.filter(w=>{const c=changes.find(c=>c.sessionId===w.sessionIntent.schedule.id),row=(state.scheduledSessions||[]).find(s=>s.id===c.sessionId),v=row?.revisions.find(v=>v.recordedAt===w.sessionIntent.schedule.revisionAt);return r.response==='accepted'&&v?.recordedAt===r.createdAt&&w.sessionIntent?.prescription?.capturedAt===r.createdAt&&same(v.context.prescription,w.sessionIntent.prescription);}),actualSets=attributed.flatMap(w=>(w.exercises||[]).filter(e=>e.exerciseId===r.proposal.exerciseId&&e.type!=='cardio'&&e.trackBy!=='duration').flatMap(e=>(e.sets||[]).filter(s=>s.done!==false&&s.completed!==false&&!s.skipped&&!s.warmup&&s.type!=='warmup')));return {id:r.id,kind:r.proposal.kind,name:r.proposal.name,response:r.response,asOf:r.asOf,status:r.response==='declined'?'declined':r.proposal.kind==='sport-defer'?'deferred-pending-review':attributed.length?'observed':'awaiting-follow-up',workoutIds:attributed.map(w=>w.id),completedSets:actualSets.length,knownEffort:actualSets.filter(s=>Number.isFinite(s.rpe)).length,note:'Descriptive linked follow-up only. Revised/replaced plans are not attributed; direction or completion does not prove that advice caused improvement. No automatic policy learning.'};});
 }
 function correctAthletic(state,id,context,{expected,now=new Date().toISOString(),confirmed=false}={}){const records=B.validateAthletic(state.athleticPractice||[]),r=records.find(r=>r.id===id);if(!r||!iso(now)||confirmed!==true||!same(r.revisions.at(-1),expected))throw Error('Review the current athletic observation before correcting it');const value=B.athleticContext(context),old=r.revisions.at(-1).context;if(!old||value.date!==old.date||value.goalId!==old.goalId||value.sessionId!==old.sessionId||!same(value.drills.map(d=>[d.exerciseId,d.kind,d.protocol]),old.drills.map(d=>[d.exerciseId,d.kind,d.protocol])))throw Error('Correction must preserve recorded session, identity and protocol');r.revisions.push({recordedAt:now,context:value});return {...state,athleticPractice:B.validateAthletic(records)};}
 return {checkIn,proposal,validate,weekly,proposals,respond,outcomes,correctAthletic};
});
