(function(){
 'use strict';
 const A=()=>window.LoadnoteGuidedPlan,esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),labels=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
 function open(mode='hypertrophy'){
  const view=A().inspect(data,mode);let d=document.getElementById('guided-plan-dialog');if(!d){d=document.createElement('dialog');d.id='guided-plan-dialog';d.className='card schedule-dialog';document.body.append(d);}
  d.innerHTML=`<form><h2>Start a ${esc(A().MODES[mode].toLowerCase())} plan</h2><p>1. Confirm your goal · 2. Choose movements · 3. Review doses and every week.</p><p>${esc(view.name)} is an editable Loadnote starting structure. It is not a coach-authored or individualized prescription.</p><label>Confirmed training goal<select class="input" id="guided-goal"><option value="">Choose goal</option>${view.goals.map(g=>`<option value="${esc(g.id)}">${esc(g.name)}</option>`).join('')}</select></label><p id="guided-context"></p><fieldset id="guided-days"><legend>Training days</legend></fieldset>${mode==='athlete'?'<label>Quality drill category<select class="input" id="guided-kind"><option value="speed">Speed</option><option value="jump">Jump / landing</option><option value="agility">Change of direction</option></select></label>':''}${view.roles.map(r=>`<label>${esc(r.label)}<select class="input" data-guided-role="${r.id}"><option value="">Choose exact exercise</option>${r.choices.map(e=>`<option value="${esc(e.id)}">${esc(e.name)}</option>`).join('')}</select></label>${r.choices.length?'':`<p>Confirm an eligible ${esc(r.label.toLowerCase())} identity in Muscle workload first.</p>`}`).join('')}<p>Equipment remains your explicit review. Loads, increments, technical variations and drill protocols need your inputs in the next step. You can remove, add or change slots there.</p><button class="btn-primary" type="submit">Continue to dose and week review</button><button class="btn-secondary" type="button" id="guided-goals">Edit goals</button><button class="btn-secondary" type="button" id="guided-mapping">Confirm exercise mappings</button><button class="btn-secondary" type="button" id="guided-close">Close</button><p role="alert" id="guided-error"></p></form>`;
  const q=id=>d.querySelector('#guided-'+id);
  q('goal').onchange=()=>{const g=view.goals.find(g=>g.id===q('goal').value);q('context').textContent=g?g.equipment+' · '+g.minutes+' min · '+(g.gaps.length?'Complete in Goals: '+g.gaps.join(', '):'Review sport overlap and restrictions in the next step.'):view.goals.length?'Choose a matching confirmed goal.':'Create an active goal with this training priority in Goals.';q('days').innerHTML='<legend>Training days</legend>'+(g?.days||[]).map(day=>`<label><input type="checkbox" value="${day}" checked> ${labels[day]}</label>`).join('');};q('goal').onchange();
  d.querySelector('form').onsubmit=e=>{e.preventDefault();try{const seed=A().draft(data,{mode,goalId:q('goal').value,days:[...q('days').querySelectorAll('input:checked')].map(e=>Number(e.value)),selections:Object.fromEntries([...d.querySelectorAll('[data-guided-role]')].map(e=>[e.dataset.guidedRole,e.value])),drillKind:q('kind')?.value||'speed'});d.close();if(mode==='hypertrophy')window.LoadnoteHypertrophyBuilderUI.open(seed);else window.LoadnoteSportPlannerUI.open(mode,seed);}catch(err){q('error').textContent=err.message;}};
  q('goals').onclick=()=>{d.close();showTab('coach');showSubTab('coach','co-goals');};q('mapping').onclick=()=>{d.close();showTab('coach');showSubTab('coach','co-programs');const panel=document.getElementById('muscle-workload')?.closest('details');if(panel){panel.open=true;panel.scrollIntoView({block:'start'});}};q('close').onclick=()=>d.close();d.showModal();
 }
 window.LoadnoteGuidedPlanUI={open};
})();
