(function(){
 'use strict';const U=()=>window.LoadnoteReviewedPlanningUI,E=()=>window.LoadnoteProgramEdit;
 function open(){const u=U(),sessions=LoadnoteSchedule.rows(data.scheduledSessions||[],data.workouts||[],{asOf:today()}).filter(s=>s.state==='scheduled'&&s.date>=today());
  const d=u.dialog('program-edit-dialog','Edit planned exercises','<p>One current/future session at a time. Frozen source programs and completed history remain intact. New exercises need fresh targets. Close all training drafts before approval.</p>'+(sessions.length?'<label>Session<select class="input" id="edit-session">'+u.options(sessions.map(s=>({id:s.id,name:s.date+' · '+s.name})))+'</select></label><label>Edit<select class="input" id="edit-action"><option value="remove">Remove movement</option><option value="replace">Replace movement</option><option value="add">Add movement</option></select></label><label>Planned movement<select class="input" id="edit-source"></select></label><label><input type="checkbox" id="edit-primary"> I reviewed changing primary work and the loss of comparable evidence for a new movement.</label><details id="edit-target-details"><summary>New movement and fresh targets</summary><label>Catalog movement<select class="input" id="edit-target-id"><option value="">My own exercise</option>'+u.options(data.exerciseCatalog||[])+'</select></label><label>Exact movement name<input class="input" id="edit-target-name" maxlength="160"></label><label>Tracking<select class="input" id="edit-type"><option value="strength">Strength sets</option><option value="cardio">Cardio minutes</option></select></label><label>Load convention<select class="input" id="edit-convention"><option value="total">Total</option><option value="per-hand">Per hand</option><option value="stack">Machine stack</option><option value="added">Added load</option></select></label><label>Starting load ('+unitLabel()+')<input class="input" id="edit-load" type="number" min="0" step="0.1"></label><label>Sets<input class="input" id="edit-sets" type="number" min="1" max="6" value="2"></label><label>Reps<input class="input" id="edit-reps" type="number" min="1" max="30" value="10"></label><label>RPE cap<input class="input" id="edit-rpe" type="number" min="1" max="9" step="0.5" value="7"></label><label>Rest seconds<input class="input" id="edit-rest" type="number" min="60" max="600" value="120"></label><label>Cardio minutes<input class="input" id="edit-minutes" type="number" min="5" max="90" value="15"></label></details><label>Reason<select class="input" id="edit-reason">'+Object.entries(E().REASONS).map(([k,v])=>'<option value="'+k+'">'+u.esc(v)+'</option>').join('')+'</select></label><label>Explanation<textarea class="input" id="edit-notes" maxlength="250"></textarea></label><button type="button" class="btn-secondary" id="edit-preview">Preview exact edit</button><div id="edit-result" aria-live="polite"></div>':'<p>No current/future unperformed sessions. Schedule a reviewed plan first.</p>'));if(!d||!sessions.length)return;let preview=null;const unit=currentUnit();
  const val=id=>d.querySelector('#edit-'+id).value,n=id=>Number(val(id));
  function clear(){preview=null;d.querySelector('#edit-result').replaceChildren();}
  function controls(){clear();const s=sessions.find(s=>s.id===val('session'));d.querySelector('#edit-source').innerHTML=u.options(s.prescription.plannedExercises.filter(e=>e.exerciseId).map(e=>({id:e.exerciseId,name:e.name})));}
  d.querySelector('#edit-session').onchange=controls;controls();d.querySelector('#edit-action').onchange=()=>{d.querySelector('#edit-target-details').open=val('action')!=='remove';d.querySelector('#edit-source').disabled=val('action')==='add';clear();};d.querySelector('#edit-target-id').onchange=()=>{const e=(data.exerciseCatalog||[]).find(e=>e.id===val('target-id'));d.querySelector('#edit-target-name').value=e?.name||'';d.querySelector('#edit-load').value='';clear();};
  const changed=e=>{if(!e.target.closest('#edit-result'))clear();};d.addEventListener('input',changed);d.addEventListener('change',changed);
  d.querySelector('#edit-preview').onclick=()=>{try{if(currentUnit()!==unit)throw Error('Display unit changed; reopen the editor');const count=n('sets');if(val('action')!=='remove'&&val('type')==='strength'&&(val('load')===''||!Number.isInteger(count)||count<1||count>6))throw Error('Enter a fresh starting load and set count');const raw={action:val('action'),sourceId:val('source'),primaryAcknowledged:d.querySelector('#edit-primary').checked,reason:val('reason'),notes:val('notes'),target:{name:val('target-name'),exerciseId:val('target-id')||undefined,type:val('type'),loadConvention:val('convention'),restSeconds:n('rest'),duration:n('minutes'),sets:Array.from({length:count>=1&&count<=6?count:0},()=>({weight:toStorage(n('load')),reps:n('reps'),targetRpe:n('rpe')}))}};preview=E().preview(data,val('session'),raw,{asOf:today()});u.error(d,'');const host=d.querySelector('#edit-result');host.innerHTML='<h3>Review before → after</h3><p>'+u.esc(preview.notice)+'</p><h4>Before</h4>'+preview.before.plannedExercises.map(e=>'<p>'+u.esc(u.describe(e))+'</p>').join('')+'<h4>After</h4>'+preview.after.plannedExercises.map(e=>'<p>'+u.esc(u.describe(e))+'</p>').join('')+'<label><input type="checkbox" id="edit-confirm"> I approve this exact change.</label><button type="button" class="btn-primary" id="edit-approve">Approve session edit</button>';host.querySelector('#edit-approve').onclick=async()=>{const approved=d.querySelector('#edit-confirm').checked;const ok=await u.save(d,()=>{if(currentUnit()!==unit)throw Error('Display unit changed; reopen the editor');return E().approve(data,preview,{asOf:today(),confirmed:approved,draftOpen:u.drafts()});});if(ok){d.close();showToast('Reviewed session edit saved','success');}};}catch(e){u.error(d,e);}};
 }
 function learning(){const u=U(),report=E().learning(data,{asOf:today()}),d=u.dialog('edit-learning-dialog','What your edits show','<p>'+u.esc(report.notice)+'</p><p>'+report.events.length+' reviewed edits · '+report.events.reduce((n,e)=>n+e.observedLogs,0)+' exact-revision linked logs.</p>'+report.events.slice(-10).reverse().map(e=>'<p>'+u.esc(e.reason+' · removed '+(e.removed.join(', ')||'none')+' · added '+(e.added.join(', ')||'none')+' · '+e.observedLogs+' linked logs')+'</p>').join('')+'<div id="edit-preferences"></div>');if(!d)return;const host=d.querySelector('#edit-preferences');if(!report.suggestions.length)host.textContent='No repeated preference/equipment removals from distinct sessions yet. Symptom edits never become inferred preferences.';
  for(const s of report.suggestions){const row=document.createElement('div'),label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';label.append(check,document.createTextNode(' Confirm '+s.name+' as avoided in future generated plans ('+s.count+' sessions).'));const b=document.createElement('button');b.type='button';b.className='btn-secondary';b.textContent='Save confirmed preference';b.onclick=async()=>{if(await u.save(d,()=>E().acceptAvoided(data,s.exerciseId,{asOf:today(),confirmed:check.checked}))){row.remove();showToast('Confirmed preference saved; existing targets unchanged','success');}};row.append(label,b);host.append(row);}
 }
 window.LoadnoteProgramEditUI={open,learning};
})();
