(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('../core/loadnote-core'),require('./program-builder'),require('./decision-readiness'),require('./schedule'),require('./session-intent'));else root.LoadnoteProgramReview=factory(root.LoadnoteCore,root.LoadnoteBuilder,root.LoadnoteReadiness,root.LoadnoteSchedule,root.LoadnoteIntent);})(typeof globalThis!=='undefined'?globalThis:this,function(Core,Builder,Readiness,Schedule,Intent){
 'use strict';const clone=x=>JSON.parse(JSON.stringify(x)),lifts=['squat','bench','deadlift'],stamp=s=>typeof s==='string'&&Number.isFinite(Date.parse(s))&&new Date(s).toISOString()===s;
 const move=(day,n)=>{const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
 function checkin(raw={}){const out={};for(const k of ['sleep','fatigue','soreness']){out[k]=raw[k]||'unknown';if(!['usual','worse','unknown'].includes(out[k]))throw Error('Invalid recovery check-in');}out.discomfort=raw.discomfort||'unknown';if(!['none','present','unknown'].includes(out.discomfort)||typeof(raw.notes??'')!=='string'||(raw.notes||'').length>1000)throw Error('Invalid recovery notes');out.notes=(raw.notes||'').trim();return out;}
 function analyze(state,{programId,week,asOf,recovery,now=new Date().toISOString()}={}){
  if(!Schedule.date(asOf)||!stamp(now)||asOf>move(now.slice(0,10),1)||!Number.isInteger(week)||week<1||week>3)throw Error('Choose a completed program week (1–3) and valid review date');
  const p=Builder.validate(state.reviewedPrograms||[]).find(p=>p.id===programId);if(!p?.scheduledAt)throw Error('Schedule a reviewed program first');const from=move(p.config.startDate,(week-1)*7),through=move(from,6);if(through>asOf)throw Error('Review this week on or after its final calendar day');
  const cutoff=now<asOf+'T23:59:59.999Z'?now:asOf+'T23:59:59.999Z',current=Schedule.list(state.scheduledSessions||[],cutoff),all=Readiness.workoutsAt(state,asOf,cutoff,false).workouts,ci=checkin(recovery),roles=Readiness.list(state.exerciseRoles||[],cutoff);
  const expected=p.sessions.filter(s=>s.week===week),evidence=[],basis=[];
  for(const s of expected){const id=`builder:${p.id}:${s.key}`,record=(state.scheduledSessions||[]).find(r=>r.id===id),latest=current.find(r=>r.id===id),ws=all.filter(w=>w.sessionIntent?.schedule?.id===id&&w.date>=from&&w.date<=through);basis.push({id,latest:latest||null,workouts:ws});
   const w=ws.length===1?ws[0]:null,original=record?.revisions[0]?.context?.prescription,linked=record?.revisions.find(v=>v.recordedAt===w?.sessionIntent?.schedule?.revisionAt)?.context?.prescription;
   let valid=!!(w&&stamp(w.createdAt)&&linked&&w.sessionIntent?.prescription&&JSON.stringify(Intent.prescription(w.sessionIntent.prescription))===JSON.stringify(Intent.prescription(linked))&&Intent.planTiming(linked,w.date,w.sessionIntent?.timing)==='before-training');
   evidence.push({sessionId:id,name:s.name,date:s.date,state:w?'completed':latest?.status==='scheduled'?'unconfirmed':latest?.status||'missing',workoutId:w?.id||null,deviationReason:w?.sessionIntent?.deviationReason||'none',deviationNotes:w?.sessionIntent?.deviationNotes||'',originalPlan:original||null,performedPlan:linked||null,validTiming:valid,loggedExercises:clone(w?.exercises||[]),workout:w});
  }
  const findings={};for(const lift of lifts){const ex=p.config.lifts[lift],rows=evidence.filter(e=>expected.find(s=>`builder:${p.id}:${s.key}`===e.sessionId)?.exercises.some(x=>x.exerciseId===ex.exerciseId)),mapped=roles.filter(r=>r.role==='competition'&&r.competitionLift===lift);let comparedSets=0,overCapSets=0,overCapSessions=0,complete=true;const performance=[];
   for(const row of rows){const actual=(row.workout?.exercises||[]).filter(e=>e.exerciseId===ex.exerciseId&&e.type!=='cardio'&&e.trackBy!=='duration').flatMap(e=>e.sets||[]),plan=(row.performedPlan?.plannedExercises||[]).filter(e=>e.exerciseId===ex.exerciseId).flatMap(e=>e.sets||[]);let over=0;if(!row.validTiming||!plan.length||actual.length!==plan.length)complete=false;
    for(let i=0;i<plan.length;i++){const a=actual[i],t=plan[i],rpe=Number(a?.rpe);if(!row.validTiming||!a||!Number.isFinite(a.weight)||a.weight<=0||a.reps!==t.reps||Math.abs(a.weight-t.weight)>.02||a.rpe==null||a.rpe===''||!Number.isFinite(rpe)||rpe<6||rpe>10||!Number.isFinite(t.targetRpe)){complete=false;continue;}comparedSets++;if(rpe>=t.targetRpe+1){over++;overCapSets++;}const capacity=Core.capacityEvidence(a.weight,a.reps,rpe).estimate;performance.push({workoutId:row.workoutId,date:row.workout.date,weight:a.weight,reps:a.reps,rpe,targetRpe:t.targetRpe,estimatedCapacity:capacity});}
    if(over)overCapSessions++;
   }
   let decision='hold',reason='Matched work stayed within the review rule. Keep next week as scheduled; this is not evidence that a load increase has been earned.';
   if(mapped.length!==1||mapped[0].exerciseId!==ex.exerciseId){decision='gather';reason='Competition lift mapping changed or is ambiguous. Review the mapping before adjusting.';}
   else if(ci.discomfort!=='none'){decision='gather';reason=ci.discomfort==='present'?'Discomfort reported. Review with an appropriate professional; no automatic load adjustment is proposed.':'Discomfort check-in is unknown. Complete the check-in before considering an adjustment.';}
   else if(!complete||!rows.length||!comparedSets){decision='gather';reason='Missing, changed, skipped, late-captured or incomplete work prevents a reliable matched-set comparison.';}
   else if(overCapSessions>=2&&overCapSets>=2){decision='reduce';reason='At least two matched sessions exceeded their RPE cap by at least 1. Consider reducing next-week loads by 5%, rounded down to the configured increment.';}
   else if(overCapSets||['sleep','fatigue','soreness'].some(k=>ci[k]==='worse')){decision='gather';reason='Effort or recovery needs review; evidence does not meet the repeated-session adjustment rule.';}
   if(week===3){decision='gather';reason='Next week is the planned deload. Preserve its design and review manually rather than applying this reduction rule.';}
   findings[lift]={name:ex.name,exerciseId:ex.exerciseId,decision,reason,expectedSessions:rows.length,comparedSets,overCapSets,overCapSessions,performance};
  }
  const next=p.sessions.filter(s=>s.week===week+1).map(s=>{const id=`builder:${p.id}:${s.key}`,r=current.find(r=>r.id===id);return {id,session:r||null,completed:(state.workouts||[]).some(w=>w.sessionIntent?.schedule?.id===id)};});
  return {version:1,programId,week,asOf,from,through,recovery:ci,findings,evidence:evidence.map(({workout,...r})=>r),targets:next,basis:{program:p,roles,basis},policy:'matched-effort-v1'};
 }
 function preview(report,choices){const changes=[];for(const t of report.targets){const s=t.session;if(!s||s.status!=='scheduled'||s.date<=report.asOf||t.completed)continue;const after=clone(s.prescription);let changed=false;for(const e of after.plannedExercises){const lift=lifts.find(l=>report.findings[l].exerciseId===e.exerciseId);if(!lift||choices[lift]!=='reduce')continue;if(report.findings[lift].decision!=='reduce')throw Error('Reduction is not supported for this lift');const inc=report.basis.program.config.incrementKg;for(const set of e.sets||[]){const weight=Math.round(Math.floor((set.weight*.95+1e-9)/inc)*inc*100)/100;if(!(weight>0&&weight<set.weight))throw Error('Rounded adjustment is not usable; review manually');set.weight=weight;changed=true;}}if(changed)changes.push({id:t.id,before:s,after});}return changes;}
 function validate(records){if(!Array.isArray(records)||records.length>1000)throw Error('Invalid program reviews');const seen=new Set();return records.map(r=>{if(!r||r.version!==1||typeof r.id!=='string'||!r.id||seen.has(r.id)||typeof r.programId!=='string'||!r.programId||!Number.isInteger(r.week)||r.week<1||r.week>3||!Schedule.date(r.asOf)||!stamp(r.createdAt)||!Array.isArray(r.changes)||r.changes.length>4||!r.findings||!r.choices)throw Error('Invalid program review record');seen.add(r.id);const recovery=checkin(r.recovery);for(const l of lifts)if(!['hold','gather','reduce'].includes(r.findings[l]?.decision)||!['keep','reduce'].includes(r.choices[l]))throw Error('Invalid review decision');const ids=new Set();for(const c of r.changes){if(ids.has(c.id))throw Error('Duplicate review change');ids.add(c.id);Schedule.validate([{id:c.id,revisions:[c.before,c.after]}]);if(c.after.recordedAt!==r.createdAt||c.after.context.date<=r.asOf||c.before.context.date!==c.after.context.date)throw Error('Review changes must affect future dates only');}return {...clone(r),recovery};});}
 function apply(state,report,choices,{confirmed=false,asOf,now=new Date().toISOString(),lockedSessionIds=[]}={}){
  if(!confirmed||!stamp(now)||asOf!==report.asOf)throw Error('Confirm a fresh review for today before applying');for(const l of lifts)if(!['keep','reduce'].includes(choices?.[l]))throw Error('Choose keep or reduce for every lift');
  if((state.programReviews||[]).some(r=>r.programId===report.programId&&r.week===report.week))throw Error('This week already has an accepted review');
  const fresh=analyze(state,{programId:report.programId,week:report.week,asOf,recovery:report.recovery,now});if(JSON.stringify(fresh)!==JSON.stringify(report))throw Error('Training data or schedule changed. Generate and review a fresh proposal.');
  const edits=preview(report,choices);if(lifts.some(l=>choices[l]==='reduce'&&report.findings[l].decision!=='reduce'))throw Error('Reduction is not supported for this lift');
  if(lifts.some(l=>choices[l]==='reduce')&&!edits.length)throw Error('No eligible future sessions remain');
  for(const l of lifts)if(choices[l]==='reduce'&&!edits.some(e=>e.after.plannedExercises.some(x=>x.exerciseId===report.findings[l].exerciseId)))throw Error('No eligible future sessions remain for '+l);
  if(edits.some(e=>lockedSessionIds.includes(e.id)))throw Error('A target session is open in your workout draft. Finish or clear it before applying.');
  const sessions=Schedule.validate(state.scheduledSessions||[]),changes=[];for(const edit of edits){const rec=sessions.find(r=>r.id===edit.id),before=clone(rec.revisions.at(-1)),plan=clone(edit.after);plan.capturedAt=now;const after={recordedAt:now,context:{...before.context,prescription:plan,reason:`Approved program review: week ${report.week} load adjustment`}};rec.revisions.push(after);changes.push({id:edit.id,before,after});}
  const event={version:1,id:Core.createId(),programId:report.programId,week:report.week,asOf,createdAt:now,recovery:report.recovery,findings:report.findings,evidence:report.evidence,choices:clone(choices),changes};
  return {...state,scheduledSessions:Schedule.validate(sessions),programReviews:validate([...(state.programReviews||[]),event])};
 }
 return {checkin,analyze,preview,apply,validate};
});
