(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('../core/loadnote-core'),require('./athlete-goals'),require('./decision-readiness'),require('./schedule'),require('./session-intent'),require('./programming-profile'));else root.LoadnoteBuilder=factory(root.LoadnoteCore,root.LoadnoteGoals,root.LoadnoteReadiness,root.LoadnoteSchedule,root.LoadnoteIntent,root.LoadnoteProgrammingProfile);})(typeof globalThis!=='undefined'?globalThis:this,function(Core,Goals,Readiness,Schedule,Intent,Profile){
 'use strict';
 const clone=x=>JSON.parse(JSON.stringify(x)),stamp=s=>typeof s==='string'&&Number.isFinite(Date.parse(s))&&new Date(s).toISOString()===s;
 const structures={return:{label:'Return / base · 3 days',days:3,split:[['squat','bench'],['deadlift','bench'],['squat','bench']],percent:[.65,.675,.70,.60],rpe:[6,6.5,7,6]},strength:{label:'Strength · 4 days',days:4,split:[['squat','deadlift'],['bench'],['deadlift','squat'],['bench']],percent:[.70,.725,.75,.60],rpe:[7,7.5,8,6]}};
 const move=(day,n)=>{const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
 function config(v){
  if(!v||v.version!==1||!Object.hasOwn(structures,v.structure)||!Schedule.date(v.startDate)||new Date(v.startDate+'T12:00:00Z').getUTCDay()!==1)throw Error('Choose a structure and a Monday start date');
  if(typeof v.name!=='string'||!v.name.trim()||v.name.length>120||!Array.isArray(v.days)||v.days.length!==structures[v.structure].days||v.days.some(d=>!Number.isInteger(d)||d<0||d>6)||new Set(v.days).size!==v.days.length)throw Error('Choose a name and the required distinct training days');
  if(!Number.isInteger(v.sets)||v.sets<2||v.sets>4||!Number.isInteger(v.sessionMinutes)||v.sessionMinutes<30||v.sessionMinutes>240)throw Error('Use 2–4 working sets and 30–240 available minutes');
  if(v.equipmentConfirmed!==true)throw Error('Confirm access to a barbell, plates, rack and bench');
  if(typeof v.incrementKg!=='number'||!Number.isFinite(v.incrementKg)||v.incrementKg<.1||v.incrementKg>10)throw Error('Enter a load increment between 0.1 and 10 kg');
  const lifts={};for(const lift of ['squat','bench','deadlift']){const x=v.lifts?.[lift];if(!x||typeof x.exerciseId!=='string'||!x.exerciseId||typeof x.name!=='string'||!x.name.trim()||x.name.length>160||typeof x.trainingMaxKg!=='number'||!Number.isFinite(x.trainingMaxKg)||x.trainingMaxKg<10||x.trainingMaxKg>1000)throw Error('Confirm all three lift identities and positive training maxes (10–1000 kg)');lifts[lift]={exerciseId:x.exerciseId,name:x.name.trim(),trainingMaxKg:x.trainingMaxKg};}
  if(new Set(Object.values(lifts).map(x=>x.exerciseId)).size!==3)throw Error('Each competition lift needs its own exercise identity');
  return {version:1,name:v.name.trim(),structure:v.structure,startDate:v.startDate,days:[...v.days].sort((a,b)=>a-b),sets:v.sets,sessionMinutes:v.sessionMinutes,equipmentConfirmed:true,incrementKg:v.incrementKg,lifts};
 }
 function build(raw){const c=config(raw),s=structures[c.structure],sessions=[];
  for(let w=0;w<4;w++)for(let d=0;d<s.days;d++){
   const deload=w===3,sets=deload?Math.max(1,Math.ceil(c.sets/2)):c.sets;
   const exercises=s.split[d].map(lift=>{const lighter=c.structure==='strength'&&((d===2&&lift==='squat')||(d===0&&lift==='deadlift')),pct=s.percent[w]-(lighter&&!deload?.05:0),weight=Math.floor((c.lifts[lift].trainingMaxKg*pct+1e-9)/c.incrementKg)*c.incrementKg;
    if(weight<=0)throw Error('Load increment is too large for the entered training max');
    return {lift,exerciseId:c.lifts[lift].exerciseId,name:c.lifts[lift].name,type:'strength',trackBy:'reps',percentOfTrainingMax:Math.round(pct*1000)/10,sets:Array.from({length:sets},()=>({weight:Math.round(weight*100)/100,reps:deload||w===2?3:5,targetRpe:s.rpe[w]-(lighter&&!deload?.5:0)}))};});
   const estimatedMinutes=15+exercises.reduce((n,e)=>n+e.sets.length*5,0);if(estimatedMinutes>c.sessionMinutes)throw Error('This structure exceeds your time budget. Reduce sets or increase available minutes.');
   sessions.push({key:`w${w+1}d${d+1}`,date:move(c.startDate,w*7+c.days[d]),week:w+1,name:`Week ${w+1} · Day ${d+1}${deload?' · Deload':''}`,estimatedMinutes,exercises});
  }
  const warnings=['Template proposal, not an individually validated coaching prescription.','Percentages use your chosen training max, not a known 1RM or estimated capacity.','RPE targets are effort caps, not a prediction. If effort exceeds the cap or technique changes, reduce load or stop and review.','Weeks 2–3 are proposed loading steps, not automatic permission to progress. Review actual training before each week.','Week 4 is a planned lower-volume week. No meet taper, test singles or attempt selection is generated.','Session time is a rough planning allowance, not a guarantee. Warm-up and rest needs vary.'];
  if(c.days.some((d,i)=>i&&d-c.days[i-1]===1)||c.days[0]+7-c.days.at(-1)===1)warnings.push('Some sessions are on adjacent days. Review recovery and the combined squat/deadlift workload.');
  return {config:c,sessions,warnings};
 }
 function prepare(state,raw,{goalId,asOf}={}){
  if(!Schedule.date(asOf))throw Error('A current date is required');const proposal=build(raw),c=proposal.config;
  if(c.startDate<asOf)throw Error('Choose a start date today or later');
  const roles=Readiness.list(state.exerciseRoles||[]);for(const lift of Object.keys(c.lifts)){const mapped=roles.filter(r=>r.role==='competition'&&r.competitionLift===lift);if(mapped.length!==1||mapped[0].exerciseId!==c.lifts[lift].exerciseId)throw Error('Confirm exactly one competition exercise for each lift in Decisions first');const entry=(state.exerciseCatalog||[]).find(e=>e.id===mapped[0].exerciseId);if(entry?.name!==c.lifts[lift].name)throw Error('Exercise names changed; rebuild the preview');}
  const goal=goalId?Goals.list(state.athleteGoals).find(g=>g.id===goalId):null;if(goalId&&!goal)throw Error('Goal no longer exists');
  if(goal){if(goal.status!=='active'||!/^powerlifting$/i.test(goal.sport.trim()))throw Error('Choose an active powerlifting goal');if(goal.availableDays.length&&c.days.some(d=>!goal.availableDays.includes(d)))throw Error('Selected days fall outside goal availability');if(goal.sessionMinutes&&c.sessionMinutes>goal.sessionMinutes)throw Error('Time budget exceeds the selected goal; edit the goal or reduce the budget');if(goal.eventDate&&goal.eventDate<=move(c.startDate,34))throw Error('The target event is too close for this base/strength builder. Use an individually reviewed meet-preparation plan.');}
  const profileSnapshot=Profile.current(state.programmingProfiles||[]);proposal.warnings.push(...Profile.assess(profileSnapshot,c));
  return {...proposal,profileSnapshot,goalSnapshot:goal?{id:goal.id,updatedAt:goal.updatedAt,context:Goals.context(goal)}:null};
 }
 function validate(records){if(!Array.isArray(records)||records.length>200)throw Error('Invalid reviewed programs');const ids=new Set();return records.map(r=>{if(!r||r.version!==1||typeof r.id!=='string'||!r.id||ids.has(r.id)||!stamp(r.createdAt)||!stamp(r.review?.recordedAt)||r.review.recordedAt!==r.createdAt||!['athlete','coach-reported'].includes(r.review.by)||typeof r.review.name!=='string'||r.review.name.length>120||r.review.by==='coach-reported'&&!r.review.name.trim()||typeof r.review.notes!=='string'||r.review.notes.length>1000)throw Error('Invalid program review');ids.add(r.id);const p=build(r.config);if(JSON.stringify(r.sessions)!==JSON.stringify(p.sessions))throw Error('Program sessions do not match the reviewed configuration');let goalSnapshot=null;if(r.goalSnapshot){if(typeof r.goalSnapshot.id!=='string'||!stamp(r.goalSnapshot.updatedAt)||r.goalSnapshot.updatedAt>r.createdAt)throw Error('Invalid goal snapshot');goalSnapshot={id:r.goalSnapshot.id,updatedAt:r.goalSnapshot.updatedAt,context:Goals.context(r.goalSnapshot.context)};}let profileSnapshot=null;if(r.profileSnapshot!=null){profileSnapshot=Profile.validate([r.profileSnapshot])[0];if(!profileSnapshot.context||profileSnapshot.recordedAt>r.createdAt)throw Error('Invalid programming-profile snapshot');Profile.assess(profileSnapshot,p.config);}
  if(r.scheduledAt!=null&&(!stamp(r.scheduledAt)||r.scheduledAt<r.createdAt))throw Error('Invalid program schedule time');return {version:1,id:r.id,createdAt:r.createdAt,config:p.config,sessions:p.sessions,goalSnapshot,...(r.profileSnapshot?{profileSnapshot}:{}),review:clone(r.review),scheduledAt:r.scheduledAt||null};});}
 function save(state,proposal,review,{asOf,now=new Date().toISOString(),id=Core.createId()}={}){
  if(!stamp(now)||!review?.confirmed)throw Error('Review the full plan and confirm before saving');const fresh=prepare(state,proposal.config,{goalId:proposal.goalSnapshot?.id,asOf});if(JSON.stringify(fresh)!==JSON.stringify(proposal))throw Error('Goal, exercise or programming-profile context changed. Generate and review a fresh preview.');
  const record={version:1,id,createdAt:now,config:fresh.config,sessions:fresh.sessions,goalSnapshot:fresh.goalSnapshot,profileSnapshot:fresh.profileSnapshot,review:{by:review.by||'athlete',name:review.name||'',notes:review.notes||'',recordedAt:now},scheduledAt:null};return {...state,reviewedPrograms:validate([...(state.reviewedPrograms||[]),record])};
 }
 function schedule(state,id,{asOf,now=new Date().toISOString()}={}){
  const records=validate(state.reviewedPrograms||[]),r=records.find(r=>r.id===id);if(!r||r.scheduledAt)throw Error('Program unavailable or already scheduled');if(!Schedule.date(asOf)||r.sessions.some(s=>s.date<asOf))throw Error('Program start has passed; create a fresh reviewed plan');
  const fresh=prepare(state,r.config,{goalId:r.goalSnapshot?.id,asOf});if(JSON.stringify(fresh.profileSnapshot)!==JSON.stringify(r.profileSnapshot||null))throw Error('Programming profile changed since review; build and review a fresh program');
  if(JSON.stringify(fresh.goalSnapshot)!==JSON.stringify(r.goalSnapshot))throw Error('Goal changed since review; build and review a fresh program');
  const existing=Schedule.list(state.scheduledSessions||[]);if(existing.some(s=>s.status==='scheduled'&&r.sessions.some(p=>p.date===s.date)))throw Error('A scheduled session already uses one of these dates. Resolve calendar conflicts first.');
  let sessions=state.scheduledSessions||[];const links=[];for(const s of r.sessions){const sid=`builder:${r.id}:${s.key}`;links.push(sid);sessions=Schedule.create(sessions,{name:r.config.name+' · '+s.name,date:s.date,role:s.week===4?'deload':'mixed',goal:r.goalSnapshot?.context.name||r.config.name,prescription:Intent.createPrescription(s.exercises,{type:'program',referenceId:r.id,label:r.config.name+' · '+s.name},now)},{id:sid,now});}
  let goals=state.athleteGoals||[];if(r.goalSnapshot){const goal=Goals.list(goals).find(g=>g.id===r.goalSnapshot.id);goals=Goals.upsert(goals,{...goal,sessionIds:[...new Set([...goal.sessionIds,...links])]},{id:goal.id,now});}
  r.scheduledAt=now;return {...state,reviewedPrograms:validate(records),scheduledSessions:sessions,athleteGoals:goals};
 }
 return {structures,config,build,prepare,validate,save,schedule};
});
