(function(){
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let busy=false;
 function render(){if(!window.LoadnoteSchedule)return;for(const [id,week] of [['week-plan',true],['calendar-plan',false]]){const host=document.getElementById(id);if(!host)continue;
  const now=today(),d=new Date(now+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);const from=week?d.toISOString().slice(0,10):`${calCursor.getFullYear()}-${String(calCursor.getMonth()+1).padStart(2,'0')}-01`;d.setUTCDate(d.getUTCDate()+6);const to=week?d.toISOString().slice(0,10):new Date(Date.UTC(calCursor.getFullYear(),calCursor.getMonth()+1,0)).toISOString().slice(0,10);
  const a=LoadnoteSchedule.summary(data.scheduledSessions||[],data.workouts,{from,to,asOf:now});
  host.innerHTML=`<h2>${week?'This week':'Scheduled sessions'}</h2><button type="button" class="btn-secondary" data-new-session>Schedule workout</button><p>${a.counts.completed} completed · ${a.counts.skipped} skipped · ${a.counts.cancelled} cancelled · ${a.counts.unconfirmed} unconfirmed · ${a.counts.scheduled} scheduled</p><p>Resolved-session adherence: ${a.adherence==null?'Not enough data':a.adherence+'% ('+a.counts.completed+'/'+a.resolved+')'}. ${esc(a.definition)}</p>${a.sessions.map(s=>`<article class="schedule-row"><b>${esc(s.date)} · ${esc(s.name)}</b><p>${esc(s.state)}${s.retrospective?' · Retrospectively entered':''}${s.lateChange?' · Changed after the scheduled date':''}${s.reason?' · '+esc(s.reason):''}</p>${s.state!=='completed'?`<button class="btn-secondary" data-start="${esc(s.id)}" ${s.status!=='scheduled'?'disabled':''}>Start</button> <button class="btn-secondary" data-change="${esc(s.id)}">Change / reschedule</button>`:''}</article>`).join('')||'<p>No sessions scheduled in this period. Unscheduled logging still works normally.</p>'}`;
  host.querySelector('[data-new-session]').onclick=()=>open();host.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>start(b.dataset.start));host.querySelectorAll('[data-change]').forEach(b=>b.onclick=()=>open(b.dataset.change));
 }window.renderAthleteGoals?.();}
 function sourceOptions(){return '<option value="current">Current logger prescription</option>'+(data.templates||[]).map((t,i)=>`<option value="template:${i}">${esc(t.name)}</option>`).join('')+(data.programs||[]).flatMap((p,i)=>(p.days||[]).map((d,j)=>`<option value="program:${i}:${j}">${esc(p.name)} · ${esc(d.day||'Day '+(j+1))}</option>`)).join('');}
 function source(value){if(value==='current'){if(!pendingPrescription)throw Error('Capture a plan in the logger first, or choose a template/program day');return LoadnoteIntent.prescription(pendingPrescription);}
  const [kind,i,j]=value.split(':');if(kind==='template'){const t=data.templates[Number(i)];return LoadnoteIntent.createPrescription(t.exercises,{type:'template',referenceId:t.id,label:t.name});}
  const p=data.programs[Number(i)],state=getProgramMesocycleState(p),decision=state.currentWeek>1?getProgramWeekDecision(p).action:'progress',profile=LoadnoteAthlete.inferProfileFromData(data,LoadnoteCore),s=LoadnoteMesocycle.buildSession(p,data.workouts||[],profile,currentUnit(),state.currentWeek,decision,LoadnoteCore,LoadnoteAthlete,Number(j));
  return LoadnoteIntent.createPrescription(s.exercises.map(e=>({name:e.name,type:'strength',trackBy:e.duration?'duration':'reps',sets:Array.from({length:e.sets||1},()=>({reps:e.reps||0,duration:e.duration||0,weight:e.weight||0,rpe:e.targetRPE}))})),{type:'program',referenceId:p.id,label:(p.days[Number(j)].day||'Program day')+' · Week '+state.currentWeek});
 }
 function open(id){const s=LoadnoteSchedule.list(data.scheduledSessions||[]).find(s=>s.id===id),opened=JSON.stringify(data.scheduledSessions||[]);let dialog=document.getElementById('schedule-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='schedule-dialog';dialog.className='card schedule-dialog';document.body.append(dialog);}
  dialog.innerHTML=`<form><h2>${id?'Change scheduled session':'Schedule workout'}</h2><label>Name<input id="schedule-name" class="input" maxlength="160" required value="${esc(s?.name)}" ${id?'disabled':''}></label><label>Date<input id="schedule-date" class="input" type="date" required value="${esc(s?.date||today())}"></label>${id?`<label>Status<select id="schedule-state" class="input"><option value="scheduled">Scheduled / rescheduled</option><option value="skipped">Explicitly skipped</option><option value="cancelled">Cancelled</option></select></label><label>Reason<input id="schedule-reason" class="input" required maxlength="500"></label>`:`<label>Plan source<select id="schedule-source" class="input">${sourceOptions()}</select></label><label>Session role<select id="schedule-role" class="input">${Object.entries(LoadnoteIntent.SESSION_ROLES).map(([k,v])=>`<option value="${k}">${esc(v)}</option>`).join('')}</select></label><label>Goal<input id="schedule-goal" class="input" maxlength="300"></label><label>Training block (optional)<select id="schedule-block" class="input"><option value="">Use date association</option>${LoadnoteBlocks.list(data.trainingBlocks||[]).map(b=>`<option value="${esc(b.id)}">${esc(b.name)}</option>`).join('')}</select></label>`}<p>The captured prescription stays unchanged. Past dates are labeled retrospective. Starting does not mark completion; saving the linked workout does.</p><p id="schedule-error" role="alert"></p><button class="btn-primary" type="submit">Save schedule</button> <button class="btn-secondary" type="button" id="schedule-cancel">Cancel</button></form>`;
  if(id)document.getElementById('schedule-state').value=s.status;
  dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const buttons=[...dialog.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{if(opened!==JSON.stringify(data.scheduledSessions||[]))throw Error('Schedule changed. Cancel and reopen.');if(id&&(data.workouts||[]).some(w=>w.sessionIntent?.schedule?.id===id))throw Error('Completed sessions cannot be rescheduled');const v=id=>document.getElementById(id).value;
   const records=id?LoadnoteSchedule.change(data.scheduledSessions||[],id,{date:v('schedule-date'),status:v('schedule-state'),reason:v('schedule-reason')}):LoadnoteSchedule.create(data.scheduledSessions||[],{name:v('schedule-name'),date:v('schedule-date'),prescription:source(v('schedule-source')),role:v('schedule-role'),goal:v('schedule-goal'),blockId:v('schedule-block')||null},{id:LoadnoteCore.createId()});
   const next={...data,scheduledSessions:records};clearTimeout(saveTimer);await persistNow(next);data.scheduledSessions=records;invalidateViews();render();dialog.close();showToast('Schedule saved on this device','success');
  }catch(error){document.getElementById('schedule-error').textContent=error.message;}finally{busy=false;buttons.forEach(b=>b.disabled=false);}};
  document.getElementById('schedule-cancel').onclick=()=>dialog.close();dialog.oncancel=e=>{if(busy)e.preventDefault();};dialog.showModal();
 }
 function start(id){try{const s=LoadnoteSchedule.list(data.scheduledSessions||[]).find(s=>s.id===id);if(!s||s.status!=='scheduled')throw Error('Session is not scheduled');if(data.workouts.some(w=>w.sessionIntent?.schedule?.id===id))throw Error('This session already has a saved workout');
  const intent={role:s.role,goal:s.goal,prescription:s.prescription,schedule:{id:s.id,revisionAt:s.revisionAt}};
  if(fillWorkoutForm(s.prescription.plannedExercises,'Scheduled: '+s.name,false,{restore:intent})===false)return;
  document.getElementById('wo-date').value=today();showTab('workouts');showSubTab('workouts','wo-log');saveLoggerDraft();showToast('Scheduled plan loaded. Record actual work, then review and save.','success');
 }catch(error){showToast(error.message,'error');}}
 window.renderSchedule=render;
})();
